### ISSUE TITLE
Hover entities

### ISSUE THREAD

**Issue by fernandojsg** [aframevr/aframe-inspector#1]
Implement hover event over each instance on the scene, both using cursor or mouse.
It should highlight the object (using a different color or shape than the selected status) and show some simple attributes on top, like for example ID or entity type.

**Comment by fernandojsg** [comment]
I'm thinking about it and probably will result in a messy UX as you'll see constantly the ID over the entities and if we use the same raycaster that we use for the click events you'll get just the topmost entities affected. Also performance-wise need to try on using raycast on every mousemove.
/cc @feiss do you think it's an important feature? I don't remember having this feature in any other DCC

**Comment by fernandojsg** [comment]
Related to https://github.com/aframevr/aframe-inspector/issues/61

**Comment by feiss** [comment]
Nope, I don't think it's important. You don't have that feature in typical 3d packages. Imagine you have hundreds or thousands of objects, that could be a highlighting party :D

**Comment by fernandojsg** [comment]
Yep, let's close it, thanks!:)
