### ISSUE TITLE
The command menu of the component should appear below the three dots

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe-inspector#10]
I clicked on the three dots icon and remove the component by mistake. The non reversible operations should be harder to trigger to avoid unintented results.

![component menu](https://s3.amazonaws.com/f.cl.ly/items/3b371W001V0k2O0Q1913/Image%202016-06-30%20at%204.26.42%20PM.png?v=f5e911c9)

**Comment by cvan** [comment]
We can keep it in this issue. But I think the three dots are very easy to miss. Can we change to show icons with tooltips (with text and/or `title`)? Or improve the icon at least?

**Comment by fernandojsg** [comment]
Maybe show icons for each action instead a context menu, but showing them just when you have the mouse over the component`s header?

**Comment by cvan** [comment]
As I mentioned before (and there's an issue on file: #18), I would never hide any functionality behind a context menu. Any feature accessible from a context menu should also be accessible from left-clicking somewhere in the UI.

**Comment by dmarcos** [comment]
Can you propose a way to place the operations asociated to each component that scales to any arbitrary number of actions in the future and does not clutter the UI? The three dots is a common pattern to indicate additional options.

The editor packs already a bunch of different workflows (and it will get more complex over time) it's not realistic to expose all the functionality on screen.

**Comment by dmarcos** [comment]
The original issue refered to the position where the menu appears after clicking on the three dots icon. The first option overlaps with the icon and I clicked it by mistake.

**Comment by cvan** [comment]
Do we expect users will want "Reset all"? I haven't seen that option in DevTools/DOM inspectors, and at least from my experience and the literature I've read, "Reset" buttons in forms most of the time just lead to users accidentally clearing form data.

Instead perhaps it's better to allow each individual component property to be reverted individually (or at least indicate that it's been user-overridden by the editor), like so:

<img src="https://cloud.githubusercontent.com/assets/203725/16677597/7167c242-448c-11e6-85f8-85eb922d4f14.png" width="50%">

Here's a screencast I made showing me toggle the rows in the sidebar:

https://drive.google.com/file/d/0B52bDqlwf1F9NUFsWWlwd2wtZGM/view?usp=sharing

![screen shot 2016-07-07 at 10 20 24 pm](https://cloud.githubusercontent.com/assets/203725/16678219/d71cd4b0-4491-11e6-9e97-9e2475217360.png)
![screen shot 2016-07-07 at 10 20 26 pm](https://cloud.githubusercontent.com/assets/203725/16678220/d71f5b90-4491-11e6-9d7e-bebc600eb449.png)

**Comment by dmarcos** [comment]
Destructive operations should have some friction so they're not triggered accidentally. Specially now we still don't have undo/redo. Deleting a component is a fairly uncommon operation and seeing that icon present on the screen all the time for every component adds unnecessary clutter.

**Comment by cvan** [comment]
> Destructive operations should have some friction so they're not triggered accidentally. Specially now we still don't have undo/redo. Deleting a component is a fairly uncommon operation and seeing that icon present on the screen all the time for every component adds unnecessary clutter.

I agree with that. But 

I tend to agree with that. But it can also be a hassle and/or undiscoverable to know how to delete something.

I like how GitHub handles the list of branches, with trash can icons _with_ tooltips to Delete:
1. 
   ![image](https://cloud.githubusercontent.com/assets/203725/16679219/b5a63660-449a-11e6-9267-ca82a78a7f08.png)
2. 
   ![image](https://cloud.githubusercontent.com/assets/203725/16679221/b9224aea-449a-11e6-8f90-7e69f6fb0d5e.png)
3. 
   ![image](https://cloud.githubusercontent.com/assets/203725/16679230/bc363174-449a-11e6-9e9a-2737f63506b4.png)
4. ![image](https://cloud.githubusercontent.com/assets/203725/16679219/b5a63660-449a-11e6-9267-ca82a78a7f08.png)

We have #21 on file to handle undo/redo.

Does this flow look kosher to folks?

**Comment by ngokevin** [comment]
_[deleted...]_

I personally prefer just the icons for now and not assume we're going to be adding 10 things to it. In my mind for me, the most common operation would be Copy to Clipboard, I don't imagine Deleting/Resetting often.

**Comment by cvan** [comment]
Comics are cool. But, hey, I took the time to think about it and mock something functionally up and record a screencast of it - instead of _talking_ about what I like, don't like, what I think users like, don't like. Let me know if you'd prefer me to convey things in another way.

> the most common operation would be Copy to Clipboard, I don't imagine Deleting/Resetting often.

👍 yes to this

**Comment by ngokevin** [comment]
It was just a joke. I thought it was funny and relevant. Sorry.

**Comment by fernandojsg** [comment]
I like the look of the icons on the on github too. I don't really like to add options below the title of the component, It could be better if they're accessible even when the component is collapsed. 
So as so far we have just delete, copy to clipboard and reset, maybe we could just add those icons the same explicitly and remove the three dots. And add a tooltip in the same way github does.

Doing that we could also get rid of this bug -> https://github.com/aframevr/aframe-editor/issues/30

**Comment by dmarcos** [comment]
are you adding a dialog for the remove component icon? Removing things by mistake and not being able to recover is very frustrating.

**Comment by fernandojsg** [comment]
@dmarcos yep, I'll add a confirm dialog for the remove and the reset buttons. When we'll have the undo functionality we could remove them.

**Comment by dmarcos** [comment]
Thinking about it. The reset button is not very useful if the component is collapsed. You won't have the feedback of the property values changing. Many components won't have a visual representation on the entity and you won't see anyrthing happening unless the component is expanded.

**Comment by fernandojsg** [comment]
But do you think it worth to have two lines of toolbars (one in the title and one below it once the component is expanded) if right now we've just these three options? I was thinking about adding them in the same level, and if we add something more redesign it to fit the new functionality.

**Comment by fernandojsg** [comment]
Well, in fact I've found a problem with reset/delete component when using mixins. If you've mixin that applies one component, it won't affect anything if you try to reset or delete that component. Probably it should checks the applied mixins to know which components they apply to prevent showing the reset/remove buttons on these components :\

**Comment by dmarcos** [comment]
The reset button is also destructive. Do we need also a confirmation dialog?

**Comment by dmarcos** [comment]
Should we show properties that come from a mixin in a different color in thhe component panel?

**Comment by fernandojsg** [comment]
re the reset button I was thinking to add a confirmation dialog too.
re the properties color I've opened another issue https://github.com/aframevr/aframe-editor/issues/186

**Comment by cvan** [comment]
I just wanted to say, nice work on this 👍 thanks for fixing this
