### ISSUE TITLE
Toggle scenegraph and attributes

### ISSUE THREAD

**Issue by fernandojsg** [aframevr/aframe-inspector#102]
Toggle the panels with a shortcut, icon and/or menu options

**Comment by arturitu** [comment]
I suggest something about this on #61

**Comment by feiss** [comment]
my 2 cents:

`tab` for toggling both scenegraph and attributes (like in Photoshop)
`1` for toggling scenegraph
`2` for toggling attributes

(so we can use other numbers for future panels)

**Comment by fernandojsg** [comment]
What about `a` for `attributes` panel and `s` for `scenegraph` and they're quite close to each other. I'm not sure about `1,2`because I always feel that they're like too sensitive shortcuts maybe for something more "important" or that you'll be doing more often?

**Comment by feiss** [comment]
I don't feel they are sensitive shortcuts, they aren't usually used as shortcuts really, are they?

`a` and `s` are visually reversed of where the panels are :/   ..what about `o` `p` (outliner, properties)?
