### ISSUE TITLE
Add helper for positional audio

### ISSUE THREAD

**Issue by fernandojsg** [aframevr/aframe-inspector#11]
Probably something like a wireframe speaker

**Comment by ngokevin** [comment]
This could be its own component, rather than an editor feature.

**Comment by fernandojsg** [comment]
Do you mean to include on each component a "rendeable" version? Like for lights, cameras and so on?

**Comment by ngokevin** [comment]
Yeah. Lights, cameras, raycaster, sound. Could work in sync with the debug component. Then the editor could just expose that, so I guess editor could have special UI for that.

**Comment by fernandojsg** [comment]
Yep, that could be nice to have the possibility to use the same helpers on debug mode without the editor, and everyone could implement a helper for theirs custom components, let's say a particle system, or whatever :)

**Comment by ngokevin** [comment]
Yeah, was thinking about a `registerDebug`.

**Comment by fernandojsg** [comment]
It could expose an object3D, and it could be also nice, later on, to have a `tick` function in case the helper have some behaviour, for example change the color and opacity of the sound`s speaker mesh when playing.

**Comment by ngokevin** [comment]
wontfixing for now unless three.js comes out with one
