### ISSUE TITLE
Set <a-scene> debug to true and call flushToDOM

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe-inspector#110]
so component changes are reflected on the DOM

**Comment by fernandojsg** [comment]
Just adding `debug=true` should be enough right? Or do I need to explicitly call `flushToDOM` in some cases?

**Comment by dmarcos** [comment]
debug = true makes DOM attributes reflect the component state but it's not retroactive. You still have to flushToDOM to write down all the compoents. Maybe that should be the behavior in a-frame

**Comment by fernandojsg** [comment]
Added a fix for that https://github.com/aframevr/aframe-editor/pull/177, but probably a-frame should care about calling `flushToDOM` after setting `debug=true` for the first time?

**Comment by ngokevin** [comment]
Alternatively, explicitly call `flushToDOM` for each update that the Editor does. This way, we don't have to check for existence of `debug` component beforehand, and in case we end up adding more properties to `debug`, it doesn't break the Editor.

**Comment by fernandojsg** [comment]
Closed by https://github.com/aframevr/aframe-inspector/issues/110
