### ISSUE TITLE
Increase the step on the rotation slider

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe-inspector#116]
I move my mouse from side to side of my display and the object only rotates 15 degrees. Small movement make imperceptible rotations.
![slider](https://s3.amazonaws.com/f.cl.ly/items/3K1J262O0d3F1R1o1U1k/Screen%20Recording%202016-07-06%20at%2011.05.34%20PM.gif?v=67464b6d)

**Comment by ngokevin** [comment]
dupe https://github.com/aframevr/aframe-editor/issues/91
