### ISSUE TITLE
Do not select value when number input fields are focussed

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-inspector#118]
![image](https://cloud.githubusercontent.com/assets/203725/16645555/9cde255a-43d9-11e6-84b1-c561334506fb.png)
1. Click on a `<input class="number">`. Notice that the field is highlighted focusses. (Any subsequent keypress will erase the value of that field. This makes things very error prone.)
2. Click on any other type of filed. Notice that the field is not highlighted upon focus.

IMO, we should remove this behaviour. I'm unclear of [what this is for](https://github.com/aframevr/aframe-editor/blob/c43aacb/src/components/widgets/NumberWidget.js#L62-L65).

**Comment by fernandojsg** [comment]
Actually I find it quite useful, as I found more useful to click on objects to completely modify the number by default, lets say number of sides in a cylinder or whatever than to replace just the last decimal on the number. So without this selection I will need to delete the whole number and enter another one.
Also this is the common way to go in most of the DCC out there, for example 3dstudio max, unity or blender use this way so I also believe is the way to go.
<img width="289" alt="screenshot 2016-07-07 12 54 48" src="https://cloud.githubusercontent.com/assets/782511/16651093/106c26d0-4442-11e6-9767-d6574d163036.png">
<img width="174" alt="screenshot 2016-07-07 12 49 43" src="https://cloud.githubusercontent.com/assets/782511/16651094/106c8b0c-4442-11e6-9bd5-b71a2105229d.png">

**Comment by cvan** [comment]
I don't know. I'm split here. if a placeholder/default value is there, I can expect to want to rewrite it. but otherwise, I can see myself accidentally rewriting values (and I have already - numerous times). I know this is also how the DOM inspector works. But we're comparing something our Editor which uses native HTML5 forms to native GUIs. Not sure it's a fair comparison. We can keep this open and see what people say.

**Comment by arturitu** [comment]
In my case, I always appreciate that they can edit this way, and especially the possibility of scrolling (now works). But now you can edit values when they are not selected, I think is better only can edit the selected field.
![issue118](https://cloud.githubusercontent.com/assets/5744112/16676682/2cdf1756-44cd-11e6-8762-9aacf414432d.gif)

**Comment by ngokevin** [comment]
think it's fine, able to directly modify value, and if you drag another number still works.
