### ISSUE TITLE
Cannot tell when input[type=checkbox]/input[type=radio] is focussed

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-inspector#124]
Compare to `<select>`:

![image](https://cloud.githubusercontent.com/assets/203725/16646450/0422ea8e-43df-11e6-9e8b-efb6c06b7076.png)

**Comment by fernandojsg** [comment]
Related to https://github.com/aframevr/aframe-inspector/issues/282

**Comment by ngokevin** [comment]
<img width="38" alt="screen shot 2018-12-20 at 3 27 53 am" src="https://user-images.githubusercontent.com/674727/50282335-47f48480-0407-11e9-9433-a21dae38d9f5.png">
