### ISSUE TITLE
Editor's CSS should be scoped

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-inspector#129]
I can imagine a ton of conflicts with other content if `<a-scene>` is not the only child of `<body>` in the document.

**Comment by ngokevin** [comment]
https://github.com/css-modules/css-modules ?

**Comment by cvan** [comment]
if we can use it with postcss (which it looks like [we can](https://github.com/outpunk/postcss-modules-example)), this seems like the right way to do it. thanks.

**Comment by evanaubrey** [comment]
What is the status on this?

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe-inspector/commit/cf20d46b382f738eb88f443046cd726e15c365b6
