### ISSUE TITLE
Purpose of "Edit" menu?

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-inspector#13]
I don't see anything in Denys' mocks. Will this "Edit" drop-down menu be used for something?

**Comment by caseyyee** [comment]
I would just remove it.   You already are "editing" when you an item, so the verbiage may be confusing.

I imagine that there will need to be a place for tools like copy/paste when it comes.   eg https://github.com/aframevr/aframe-editor/issues/36

**Comment by fernandojsg** [comment]
Closing as we got rid of the menu (https://github.com/aframevr/aframe-inspector/pull/221)
