### ISSUE TITLE
Gracefully degrade (and use JS) to inject font-awesome and Google Fonts CSS

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-inspector#136]
If maxcdn/Google Fonts takes a while or if I'm offline, the Editor will take a long time/forever to load.

![image](https://cloud.githubusercontent.com/assets/203725/16649060/df468a2e-43eb-11e6-97ac-26e50dca5d9c.png)

[This](https://github.com/MozVR/iswebvrready/blob/7974601/src/_base.html#L12) is one approach (using https://github.com/typekit/webfontloader). Also, there's now a [Font Loading API](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/webfont-optimization#optimizing-font-rendering-with-the-font-loading-api) that ships with Chrome.

**Comment by fernandojsg** [comment]
@cvan this was fixed on https://github.com/aframevr/aframe-inspector/pull/272 right?

**Comment by fernandojsg** [comment]
Fixed by https://github.com/aframevr/aframe-inspector/pull/272

**Comment by cvan** [comment]
Now, the `.css` file isn't a blocking request. But, still, with how the code's set up right now, the `.css` file plus all the font files (e.g., `.woff2) still have to still fetch.

Because of the two issues mentioned below, the browser renders all the text as blank until all the requests finish. FWIW, modern browsers recently added a new Font Loading API (but the [Web Font Loader](https://github.com/typekit/webfontloader) JS prolyfill was already added in PR #272, which works fine), but it doesn't handle Google Fonts well (because of the various character sets served, varied based on the HTTP request headers).

Anyway, when the Inspector gets injected, wherever `Roboto` and `Robot Mono` (which is everywhere), the text is invisible until all the font assets load, at which point the text is then rendered using the loaded respective web fonts.

* When the `WebFont` loader was added (in PR #272), it was added for [`Roboto Mono`](https://github.com/aframevr/aframe-inspector/blob/521a0ec/src/components/Main.js#L131), but not for [`Roboto` (sans-serif)](https://github.com/aframevr/aframe-inspector/blob/521a0ec/src/components/Main.js#L22) (and `Roboto` is used in [`main.css`](https://github.com/aframevr/aframe-inspector/blob/521a0ec/src/css/main.css) [here](https://github.com/aframevr/aframe-inspector/blob/521a0ec/src/css/main.css#L3) and [here](https://github.com/aframevr/aframe-inspector/blob/521a0ec/src/css/main.css#L3)).
* `font-family: Roboto Mono` is used for [`.Select`](https://github.com/aframevr/aframe-inspector/blob/521a0ec/src/css/main.css#L698), before the `Roboto Mono` font is loaded (i.e., `wf-active` is set), causing the entire document to hang until `Roboto Mono` loads.

Anyway, I opened up PR #468 to address the issues. I used the "Network Link Conditioner" on macOS to simulate flaky connections, and the difference is noticeable. (I recorded a few videos with QuickTime, but as I was about to edit them, I figured there wasn't much point since I've already opened the PR.)

**Comment by fernandojsg** [comment]
@cvan cool! thanks for the explanation and the PR! ;)
