### ISSUE TITLE
Stray horizontal line in wireframe view

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-inspector#137]
1. Load the example scene in the editor mode.
2. Reduce the height of your browser.
3. Notice the stray gray.

![image](https://cloud.githubusercontent.com/assets/203725/16649167/728ec9c2-43ec-11e6-8d06-87846ee11407.png)

**Comment by fernandojsg** [comment]
This is from the far plane clipping of the camera helper:
<img width="723" alt="screenshot 2016-07-07 19 14 28" src="https://cloud.githubusercontent.com/assets/782511/16662304/1dc13d18-4477-11e6-8678-6adde3b8ee7e.png">

Anyway this will be removed if the camera is not selected, see: https://github.com/aframevr/aframe-editor/issues/45
