### ISSUE TITLE
Add a collapse all to be able to easily see all the components

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe-inspector#14]
![collapse](https://s3.amazonaws.com/f.cl.ly/items/1Z3t2Z2K3H3J220F281S/Image%202016-06-30%20at%204.33.54%20PM.png?v=52470206)

**Comment by fernandojsg** [comment]
Yes, I was thinking about adding it, but not sure if to include it on the `ATTRIBUTES` bar so you could collapse all the panels including `COMMONS` and `COMPONENTS` or add it to `COMPONENTS` so it will collapse just all the components.
Probably first option makes more sense.

**Comment by fernandojsg** [comment]
We should add it to the curent <A-ENTITY> header probably. Or maybe below the "Add component" section where all the components will appear. Any ideas /cc @feiss

**Comment by dmarcos** [comment]
Can we keep the `common` / `default`  entity components uncollapsed?

**Comment by fernandojsg** [comment]
@feiss could you help here with some feedback on where to put the collapse/uncollapse all icon? I guess on the top bar of the A-Entity?

**Comment by feiss** [comment]
Mm.. I don't see any good place to put it, honestly :/

What about shift+click (or middle click)?  If you shift+click on a collapsed header, it opens all headers. If you shift+click on a opened header, it closes all headers. It would be a feature not available in touchscreens, but it's not an important feature..

**Comment by ngokevin** [comment]
i've defaulted to collapsed to better see the components and select one you are interested in

**Comment by feiss** [comment]
You could also close all but the first two..
