### ISSUE TITLE
Improve keyboard navigation for scenegraph using radio buttons

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-inspector#141]
I filed #7 and #12 for arrow navigation. #7 was addressed in PR #63, but my suggestion in #7 was to use hidden `<input type="radio">`s (because of built-in keyboard accessibility). When a row is selected (i.e., its child radio field is `checked`), you can go up/down or left/right, and you can cycle through the rows/fields as expected.

The two issues that stick out for me are that the keyboard navigation waits for [`keyup`](https://github.com/aframevr/aframe-editor/pull/63/files#diff-3b7a9eae122de25fe81baef8e1835b1cR133) (instead of radio's `keypress`) and that you can loop through forward/backward from the top/bottom of the list with radios.

**Comment by cvan** [comment]
Also see http://alistapart.com/article/radio-controlled-web-design

**Comment by ngokevin** [comment]
arrows work
