### ISSUE TITLE
Plugin API

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe-inspector#143]
Something like `AFRAME-EDITOR.registerPlugin(...)` so 3rd parties can add panels to the editor UI. The same way you drop a script tag on an AFRAME app you could drop a script also to augment the editor with new functionality

**Comment by AnnCaryn** [comment]
This would be AWESOME.

**Comment by fernandojsg** [comment]
Closed by https://github.com/aframevr/aframe-inspector/pull/459
