### ISSUE TITLE
Add status bar and remove scenegraph title

### ISSUE THREAD

**Issue by fernandojsg** [aframevr/aframe-inspector#147]
Adding status bar to place the common transforms icons, the grid visibility options, and add some stats too.
<img width="1438" alt="screenshot 2016-07-07 20 51 07" src="https://cloud.githubusercontent.com/assets/782511/16667989/57f6b040-448f-11e6-9cac-6f9bae9cc7a9.png">
I've also deleted the `SCENEGRAPH` title and move the icons for the scenegraph to the top. In that scenegraph-bar we'll include also options to search or filter the scenegraph.

**Comment by cvan** [comment]
Awesome! Btw, I filed #159 for search and #157 for toggling visibility of items in the scene graph.

**Comment by cvan** [comment]
The icons may be a bit close together to the icons in the sidebar, but what do you think of this treatment? Top vs. bottom:

![aframe-editor-bars-only](https://cloud.githubusercontent.com/assets/203725/16681826/de0efcde-44ab-11e6-9278-c71dc2d0d98f.png)

**Comment by fernandojsg** [comment]
Yep, I initially moved the icons from the scenegraph to the top as I thought that they maybe look bad so close to each other.
I believe we will still need an status bar to show info that is doesn't need to be highly accesible like to be on top, for example stats, # entities, drawcalls, whatever, and grid options like snap to grid, enable/disable, and so on.
I agree that the transforms options are the most used probably so they could go on the top as you suggested. It come to my mind if we will need to add a icon bar on the top and include them there, just below the menubar.

In the scenegraph toolbar we should also include a filter options that could be a searchbox like the one Dennis included in the following mockup:
![mo_v2_shot](https://cloud.githubusercontent.com/assets/782511/16681962/1f38a506-44f8-11e6-8914-25122f896963.png)

Initially I thought it was a good idea to remove the `scenegraph` title as it takes a lot of space, but to kee consistency we should also remove the `attributes` title, and we'll have potentially more panels in the future, so it could be hard to refer to the users as `Please open the "attributes" panel and ...`. So I was looking at Unity and they always have a title on each panel, but it's very small:
<img width="1440" alt="screenshot 2016-07-08 12 11 03" src="https://cloud.githubusercontent.com/assets/782511/16684374/0d45f30a-4505-11e6-971d-ad010ab216a6.png">

What do you think in keeping the title in both sidebars but making it much smaller that the one we have right now?
<img width="1437" alt="screenshot 2016-07-08 12 09 19" src="https://cloud.githubusercontent.com/assets/782511/16684339/d5810a36-4504-11e6-9fa8-8704f9feed1c.png">

**Comment by arturitu** [comment]
I have made a rough sketch to test some things commented together:
- I only use blue color for interactive elements of the interface.
- I change the near 'add' and 'delete' buttons for a 'cross' icon on every entity on the scene graph and a 'Add' top menu.
- I have added a search field on scenegraph (#159)
- I have tested to add text labels to some icons (#66)

![image](https://cloud.githubusercontent.com/assets/5744112/16685652/d9b2602a-450c-11e6-9a35-707f72046010.png)

**Comment by fernandojsg** [comment]
Cool! The only thing I don't really like it is the menu color. The icons with the text looks nice, but for those so common icons I don't know if it's a real benefit over add some tooltips for example, as it takes a lot of space to place them. Probably we could align them to the left and skip the rest of the toolbar until we'll have more icons? I mean, not using the full width of the viewport if we just have 3 icons now.

**Comment by fernandojsg** [comment]
I've done some changes following the idea of @arturitu in the PR https://github.com/aframevr/aframe-editor/pull/148:
<img width="1436" alt="screenshot 2016-07-08 18 18 33" src="https://cloud.githubusercontent.com/assets/782511/16694029/6669921a-4538-11e6-9a04-9e78eddc39f1.png">

I've included the filter and the transforms gizmos:
Transforms gizmos:
https://www.dropbox.com/s/zck3dfwqyrunwto/transforms_gizmos.mov?dl=0

And filters:
https://www.dropbox.com/s/x1715fjtkz239q3/filter_entities.mov?dl=0

**Comment by fernandojsg** [comment]
Closed by https://github.com/aframevr/aframe-editor/pull/173 and https://github.com/aframevr/aframe-editor/pull/172
Let's keep the discussion about the labels here -> https://github.com/aframevr/aframe-editor/issues/166
