### ISSUE TITLE
Consider moving "Create" to "Scene Graph"

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-inspector#15]
1. I was surprised to learn that "Create" meant _add_ items to my scene graph.
2. Can we have an "+ Add" button in the scene graph sidebar (perhaps flush left of the trash can)?

![image](https://cloud.githubusercontent.com/assets/203725/16507701/a69349d4-3ee0-11e6-8d14-c705bd80ab97.png)

**Comment by fernandojsg** [comment]
@cvan do you think that this button should add just an empty entity, select it by default and you could start adding components? Or the button should act similar to the create button where you could choose between presets?

**Comment by cvan** [comment]
good question. I'm not sure; I'd have to try it out or think about it. probably look at Chrome DevTools for inspiration too.

**Comment by fernandojsg** [comment]
@cvan I've added a create button in the scenegraph (https://github.com/aframevr/aframe-editor/pull/86) to include an empty entity to the scene, then you could keep adding components to it. Probably we should keep the larger list of presets in the menu?

**Comment by fernandojsg** [comment]
Close as we removed the menubar and moved the + icon to the scenegraph
