### ISSUE TITLE
Scene versus File Menu

### ISSUE THREAD

**Issue by AnnCaryn** [aframevr/aframe-inspector#152]
Expected behavior:
Expected this to be File Menu based on its contents
Expected that a scene menu would list all components in the scene

Actual Behavior:
Scene menu has ability to save and export to clipboard, this might become problematic when later on there is the ability to connect multiple scenes.

Visual:
<img width="327" alt="file" src="https://cloud.githubusercontent.com/assets/737515/16673614/a2e15fe0-4464-11e6-91ae-1174a0f860c7.png">

**Comment by dmarcos** [comment]
What about `Export` instead of `Scene`

**Comment by cvan** [comment]
Good catch, yeah. This issue is addressed in #33. Shall we consider this a dupe and move the discussion there?

**Comment by fernandojsg** [comment]
Yep, duplicated, let's talk there
