### ISSUE TITLE
Creation Components and their Attributes

### ISSUE THREAD

**Issue by AnnCaryn** [aframevr/aframe-inspector#153]
Expected Behavior:
I expected the Create Menu to mirror the organization of components to create consistency.  I expected that the attributes - the things you can do to a component like directional lighting or adding animations would be attributes of that component.

Expected Visual:
One idea- 
<img width="1434" alt="create1" src="https://cloud.githubusercontent.com/assets/737515/16673944/ad85b952-4467-11e6-8676-df302dcf984e.png">

Actual Behavior:
List shows entity - not sure what that could be from the look of the menu
a list of some of the components
a list of lights without the text of lights just shows directional - listing this out is probably not needed considering that there is a dropdown on the right under the attributes.
Actual Visual:
<img width="487" alt="screen shot 2016-07-07 at 5 10 09 pm" src="https://cloud.githubusercontent.com/assets/737515/16673737/b3361f88-4465-11e6-93e7-f9b88432b70f.png">

For example--

THINGS YOU CAN CREATE: (on the left)
SCENE
Canvas
Plane
Camera

OBJECTS
collada-model
obj-model
geometry
material
cone
curved-image
cylinder
image
plane
ring
sky
light
fog
sphere
torus
video
videosphere

CONTROLS
cursor
ray caster
keyboard shortcuts
look controls
look-at
WASD controls

OVERLAYS
vr-mode-ui
stats

---

You can change the attributes of the things you create: (on the right)

TRANSFORM
material
mesh 
position
rotation
scale
opacity
visible

EFFECTS
animation
mixins
shaders
sound

**Comment by dmarcos** [comment]
`Create` creates an empty entity or an entity pre-populated with a set of components to produce what you selected: camera, lights or simple shapes. Similar to the `Game Object` menu in Unity. 

![Unity](https://s3.amazonaws.com/f.cl.ly/items/2D432b2I1u0c2k1S2h3p/Image%202016-07-07%20at%209.57.37%20PM.png?v=2288f741)

The problem is the name collision between the name of the components and the name of the primitives. People will conflate them as we can see here.

**Comment by cvan** [comment]
If we're adding entities to the scene graph, IMO any buttons to `Create`/`Edit`/`Delete` (including ability to rearrange) should belong in the scenegraph sidebar. That seem kosher?

**Comment by AnnCaryn** [comment]
@dmarcos One thing I don't love about Unity is that it makes me choose things from drop downs more than twice to get what I want.  How could we help the user make the choice that they want faster?

**Comment by ngokevin** [comment]
Currently focusing on Inspector to complement dev workflow, versus being a full creation tool focused on creating simple shapes and such. So creation won't be frequent (though we could add like Blocks) and just have empty entity or cloning for now.
