### ISSUE TITLE
Edit Menu and Keyboard Shortcuts

### ISSUE THREAD

**Issue by AnnCaryn** [aframevr/aframe-inspector#154]
Expected behavior:
Expected that these menu items would appear under the Edit menu on dropdown -  
- Undo 
- Cut 
- Copy
- Paste

and that keyboard controls for undo, cut, copy and paste would work in the editor

Actual Behavior: No menu items on dropdown and keyboard controls were not working to undo, cut, copy or paste

**Comment by cvan** [comment]
👍 to this. Undo/Redo will get tricky, but I imagine.

And we have to be careful to not hijack the browser's keyboard shortcuts for word jumping, undoing, redoing, copying, etc. These menu items should be active when an entity is selected and no other form field is focussed. Additionally, it'd be nice to add all these same options as context-menu options when right-clicked.

I like how Sketch handles this:

![image](https://cloud.githubusercontent.com/assets/203725/16679413/53dcaa84-449c-11e6-8a40-0b721742c9fb.png)

**Comment by fernandojsg** [comment]
Closed by https://github.com/aframevr/aframe-inspector/issues/298
