### ISSUE TITLE
Adding an environment map

### ISSUE THREAD

**Issue by AnnCaryn** [aframevr/aframe-inspector#155]
Steps to repro:
Open an object with a material on the object
Tap the square next to env map to change the texture
Upload a file (tried jpg, png and gif) 

Expected behavior:
Would show the environment map in the preview window 
or if there was an error tell me the state of my error (wrong file type etc)

Actual Behavior:
Showed as broken in the texture window preview and upon submission did not change the texture file

Visual:
<img width="863" alt="screen shot 2016-07-07 at 5 41 48 pm" src="https://cloud.githubusercontent.com/assets/737515/16674200/92e2a080-446a-11e6-995c-2eb55c3355da.png">

**Comment by cvan** [comment]
This is a WIP and will likely be hidden for v1. We of course eventually want this though and soon. We'll likely be using an UploadCare-powered widget (à la the [A-Frame Asset Uploader](https://aframe.io/aframe/examples/_uploader/)'s), which handles all this quite nicely.

**Comment by fernandojsg** [comment]
Fixed by https://github.com/aframevr/aframe-inspector/pull/376
