### ISSUE TITLE
Not obvious that sound component added to scene

### ISSUE THREAD

**Issue by AnnCaryn** [aframevr/aframe-inspector#156]
Steps to repro:
Under components tap the dropdown
Add a sound component
Press the plus button
Nothing happens

Expected:
A sound component would likely be added as an additional entity to an object - child attribute?
When a component is added I would expect for it to be highlighted and selected on the left menu.

**Comment by dmarcos** [comment]
The component gets added for me but you have to scroll down to see it (components are sorted alphabetically). Two ideas to solve this:
1.  Scroll automatically to the newly added component.
2. Collapse all the components except the created one.

**Comment by cvan** [comment]
This seems like a dupe of #140. Can we close in favour of that issue?

**Comment by fernandojsg** [comment]
Yes, it's duplicated from #140, let's keep talking there
