### ISSUE TITLE
Determine whether the editor should multiple scenes on the same page

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-inspector#158]
Could be handled not so terribly:

![image](https://cloud.githubusercontent.com/assets/203725/16679646/fef014c8-449d-11e6-96a7-3f396749cd16.png)

![image](https://cloud.githubusercontent.com/assets/203725/16679642/fbb5d298-449d-11e6-97f8-fe8989e5e6f3.png)

**Comment by dmarcos** [comment]
If there are multiple scenes on the same page and the editor is injected an edit button will appear on each of them. You will edit one at a time.

**Comment by cvan** [comment]
Okay, cool - I assume that functionality is on its way? Want to repurpose this issue to add support for that?

**Comment by cvan** [comment]
Also, that makes #129 ever important too

**Comment by fernandojsg** [comment]
I close the issue as the expected behaviour by now is as @dmarcos says: Edit one scene at a time. For that we'll need to expand the canvas fullsize but we can open another issue with that
