### ISSUE TITLE
Dim the delete icon (trash can) in scenegraph sidebar when nothing is selected

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-inspector#164]
1. Load a scene with the editor mode.
2. Notice the trash can appears clickable even though no entity is selected in the scene-graph sidebar:

![image](https://cloud.githubusercontent.com/assets/203725/16681883/43b75fc2-44ac-11e6-88ec-39687f7c7f0f.png)

<hr>

Proposal (when nothing is selected, add these styles to the delete icon: `pointer-events: none; opacity: 0.5`):

![image](https://cloud.githubusercontent.com/assets/203725/16681914/65a17f96-44ac-11e6-940c-abc3de870a8d.png)

**Comment by fernandojsg** [comment]
Close as we don't have this icon anymore in the scenegraph. It will appear on the selected entity
