### ISSUE TITLE
Primary CTA buttons w/ icons should have text labels

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-inspector#166]
The plus sign and trash are quite common icons to indicate add and remove (although it's unclear why exactly).

(An aside: this has been brought up elsewhere, but it seems a bit odd that you have to first click a row and then move your cursor all the way back up to the header to click the delete icon.)

But the other three icons - I 100% don't know what the other three primary icons represent.

Look at this screen (from #147):

<img width="100%" alt="screenshot 2016-07-07 20 51 07" src="https://cloud.githubusercontent.com/assets/782511/16667989/57f6b040-448f-11e6-9cac-6f9bae9cc7a9.png">

And my mock of the icons all up top:

<img width="100%" src="https://cloud.githubusercontent.com/assets/203725/16681826/de0efcde-44ab-11e6-9278-c71dc2d0d98f.png">

<hr>

IMO adding text labels (they can be small) below these icons I think will help a ton. Like so:

![image](https://cloud.githubusercontent.com/assets/203725/16681578/5cead6a6-44aa-11e6-9d5c-a5ba649b0e3e.png)

<hr>

The icons should be immediately (and repeatedly) recognizable. Also icons should be universal; that is, we should be mindful of international users with cultural differences where some icons may not potentially make sense.

The fact is most icons are not universal. The back button is a universal icon. The trash can is a universal icon. An "×" can ambiguous. The three-lined hamburger icon has most recently become a universal icon. 

> To help overcome the ambiguity that almost all icons face, a text label must be present alongside an icon to clarify its meaning in that particular context. (And even if you’re using a standard icon, it’s often safer to include a label, especially if you slightly altered the icon to match your aesthetic preferences or constraints.)
> Icon labels should be visible at all times, without any interaction from the user. For navigation icons, labels are particularly critical. Don’t rely on hover to reveal text labels: not only does it increase the interaction cost, but it also fails to translate well on touch devices.

**We should test:**

> - **Use the 5-second rule**: if it takes you more than 5 seconds to think of an appropriate icon for something, it is unlikely that an icon can effectively communicate that meaning.
> - Test the icons for **recognizability**: ask people what they expect the icons to stand for.
> - Test the icons for **memorability**: ask a repeat set of users if they can remember the icon’s meaning after being told what it represented a couple weeks earlier.

Sources:
- http://www.lukew.com/ff/entry.asp?1945
- https://www.nngroup.com/articles/icon-usability/

<hr>

**Note:** This issue is different from #37 because here icons are being used not as supplementary indicators (signposts) but as _replacements_ for (English/localisable) text.

**Comment by dmarcos** [comment]
I have my own opinion on this. The specific image that an icon represent becomes irrelevant quickly after a few uses because you will operate using spatial and muscle memory once the action is learned. The most important thing is to have icons that can be discriminated visually from one another. Many people just don't even try to analize the meaning of an icon and just learn by experimentation. It's important to design tools where mistakes are not permanent and quick to recover from. 

In very dense UIs where space is at a premium a label for all icons might no be a realistic option. Labels are also useful for novices that are discovering the tool but clutter once you learn your way around. When people think about usability always consider a complete newbie profile wich is important to gain adoption but also can compromise
efficiency for more advanced users and make you feel that the tool gets in the way.

**Comment by cvan** [comment]
Compare these two Sketch windows:

### icons + labels

<img width="1552" alt="screen shot 2016-07-08 at 2 29 52 am" src="https://cloud.githubusercontent.com/assets/203725/16683298/e4859e80-44b3-11e6-8d1e-286b17609f42.png">

### icons only

<img width="1552" alt="screen shot 2016-07-08 at 2 29 42 am" src="https://cloud.githubusercontent.com/assets/203725/16683299/e48a002e-44b3-11e6-9bf9-8f0b6cd6b71d.png">

I've used Sketch for nearly five years, and I still need the labels to remember which toolbar button does what. And, even after all these years, I still use the toolbar icons, not keyboard shortcuts. And sometimes (often?) icons aren't quicker to identify than reading a word (or the shape of the letters in the word).

<hr>

Not that I think these are the best examples of intuitive interfaces that use icons (there are in fact many issues on file in both browsers' trackers for confusing iconography), it's interesting to look at Chrome's and Firefox's Developer Tools:

![image](https://cloud.githubusercontent.com/assets/203725/16683404/85e59f78-44b4-11e6-9a82-265e99277c63.png)

![image](https://cloud.githubusercontent.com/assets/203725/16683434/b189ae12-44b4-11e6-9254-ad9292776779.png)

![image](https://cloud.githubusercontent.com/assets/203725/16683448/ca7eaa08-44b4-11e6-832d-41b7411a939c.png)

![image](https://cloud.githubusercontent.com/assets/203725/16683462/dc065eec-44b4-11e6-8089-572eb10ad9ec.png)

**Comment by fernandojsg** [comment]
Linking the test from @arturitu in https://github.com/aframevr/aframe-editor/issues/147
![d9b2602a-450c-11e6-9a35-707f72046010](https://cloud.githubusercontent.com/assets/782511/16698867/e449ecee-4550-11e6-9b65-88039bc5d133.png)

Right now we've just some obvious icons/actions for this kind of software (translate, rotate, scale, delete). Even if we still doesn't have the final version of those icons.
Maybe we could take a look at the amount of actions we'll have to come back to discuss about it? Just adding the label as @arturitu did makes the toolbar already quite huge, I'm afraid we could end up with something like MSOffice toolbars :)
In any case we'll always have the menu will all the options that we've in the UI

**Comment by cvan** [comment]
I proposed a solution here in https://github.com/aframevr/aframe-inspector/issues/265#issue-170785084:

(And use this copy instead:)
- `Copy to clipboard`
- `Download HTML`
- `Insert`

![image](https://cloud.githubusercontent.com/assets/203725/17610694/690573ea-5ff5-11e6-93ef-be0e2edc275a.png)

You can keep whichever issue open you'd like.

**Comment by cvan** [comment]
Relevant: I'd recommend using https://frend.co/components/tooltip/

**Comment by ngokevin** [comment]
it's ok for now. may swap to a menu bar later, but right not there's not many critical icons, and those that exist are not super frequently used. may be done if a menu bar and status bar are ever implemented.
