### ISSUE TITLE
"Enter VR" tooltip is borked

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-inspector#168]
1. Load https://aframe.io/aframe-editor/example/
2. Click "Exit"
3. Click the "Enter VR" button
4. Notice the positioning of the tooltip is all off:

![image](https://cloud.githubusercontent.com/assets/203725/16683662/e79d6aec-44b5-11e6-98df-9d7e00381469.png)

**Comment by Coder206** [comment]
I would like to fix this.

**Comment by fernandojsg** [comment]
Perfect!, It's all yours ;)

**Comment by Coder206** [comment]
@fernandojsg It looks like it is just the online version that is corrupted. I ran it locally (opened /examples/index.html and it worked great. Still looking into this.

**Comment by Coder206** [comment]
@fernandojsg I don't think this is an issue any more. It seems that it was solved recently. Can we close it?

**Comment by fernandojsg** [comment]
@Coder206 I just tried on chrome 51 osx and it still there :\ In which browser are you trying?
<img width="687" alt="screenshot 2016-08-02 19 08 55" src="https://cloud.githubusercontent.com/assets/782511/17337776/937dfef2-58e4-11e6-87be-722cd2f652b2.png">

**Comment by Coder206** [comment]
@fernandojsg FireFox 47.0.1 on Fedora:

**Comment by Coder206** [comment]
![screenshot from 2016-08-02 13-11-21](https://cloud.githubusercontent.com/assets/7758155/17337873/a59b3f46-58b2-11e6-901e-ab76fa06da9c.png)

**Comment by fernandojsg** [comment]
Yep, on firefox on osx it seems to works right too. So it looks like a problem with chrome, could you try it on fedora?

**Comment by Coder206** [comment]
@fernandojsg On it.

**Comment by Coder206** [comment]
@fernandojsg Make that Windows 10 FireFox 47.0.1 and 48.0 both work (I just updated). It seems to be Chrome specific as Version 52.0.2743.82 (64-bit) on Fedora 24 is not working like your screen shot shows.

**Comment by Coder206** [comment]
@fernandojsg Do you mind testing it on Safari as I do not have a Mac to try it out there?

**Comment by fernandojsg** [comment]
@Coder206 safari shows it correctly aligned.

**Comment by Coder206** [comment]
@fernandojsg Thanks, so this is a Chrome specific issue.

**Comment by Coder206** [comment]
@fernandojsg Btw, is there an IRC for A-Frame contributors?

**Comment by fernandojsg** [comment]
We've a slack: https://aframevr-slack.herokuapp.com/

**Comment by Coder206** [comment]
@fernandojsg Thanks!

**Comment by Coder206** [comment]
@fernandojsg Chrome seems to be complaining about use of XMLHttpRequest in "aframe-inspector.js" code (line 24). 

Error message:

"Synchronous XMLHttpRequest" on the main thread is deprecated because of its detrimental effects on the user's experience. For more help, check https://xhr.spec.whatwg.org/."

This error is not visible on FireFox 48.0

**Comment by Coder206** [comment]
This code is throwing an error:

e.open("GET", "https://raw.githubusercontent.com/aframevr/aframe-components/master/components.json", !1),

**Comment by fernandojsg** [comment]
Yes, but that's just a warning and we'll remove the feature that uses that (third-party components) until next version. I don't think the CSS error is related to this, maybe we could just open another issue with this warning to take care of this in the future.

**Comment by Coder206** [comment]
@fernandojsg That makes sense.

**Comment by Coder206** [comment]
@fernandojsg It appears as though when running the example code locally it works well. See below:

![screenshot from 2016-08-02 16-15-47](https://cloud.githubusercontent.com/assets/7758155/17343580/676c6d84-58cc-11e6-83a6-655a7e51cf16.png)

**Comment by fernandojsg** [comment]
@Coder206 I don't see the icon in the screenshot, is cropped

**Comment by Coder206** [comment]
@fernandojsg Try refreshing the page, sorry.

**Comment by Coder206** [comment]
(I updated the comment)

**Comment by Coder206** [comment]
@fernandojsg I isolated the CSS code that made the error. There was a "display:block;" in the element.style of the affected button. I am tracing back the code to a file now.

**Comment by Coder206** [comment]
@fernandojsg I think it's this line causing the issue: https://github.com/aframevr/aframe/blob/master/src/style/aframe.css#L206

**Comment by ngokevin** [comment]
@Coder206 Thanks for the investigation. Though the latest version of A-Frame has removed that modal/tooltip (at least for now).

**Comment by Coder206** [comment]
@ngokevin Oh ok. My pleasure, it was an interesting hunt with @fernandojsg! :) Thanks.
