### ISSUE TITLE
Common, components and the list of components are different but look the same

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe-inspector#17]
![component panel](https://s3.amazonaws.com/f.cl.ly/items/3z1C0M0t3O0M271C3t13/Image%202016-06-30%20at%204.36.06%20PM.png?v=71b138c5)

We can may be do common non collapsible, add a button in the common space box to add a component to the list below

**Comment by dmarcos** [comment]
They are ordered alphabetically. If a component starts with the letter `A` or `B` will show up first?

**Comment by fernandojsg** [comment]
Actually this is not the final design that we were discussing last time, do you remember that we wanted to add something like `3dsmax`'s modifiers list?

It should be similar to the following image:
<img width="192" alt="screenshot 2016-07-01 01 42 29" src="https://cloud.githubusercontent.com/assets/782511/16507809/16bb9846-3f2d-11e6-9303-573fda104566.png">
One of the doubts I have is if to have the components list inside the `COMMONS` panel, in a similar way to the `mixins` widget, so you have the list of components with the list to add a new component, and everything will be much clear.
If we include it on the `COMMONS` panels it looks more clear but It will collapse together with the panel, that if you're working with components you usually don't care about the commons attributes. So probably it makes sense to use a separate panel.

Regarding the order, they're ordered alphabetically yep.

**Comment by cvan** [comment]
Can we list "Common" under "Components"?

**Comment by fernandojsg** [comment]
Fixed on https://github.com/aframevr/aframe-inspector/pull/339
