### ISSUE TITLE
Shortcut to change entity ID in scene graph panel.

### ISSUE THREAD

**Issue by caseyyee** [aframevr/aframe-inspector#174]
Pressing enter on the entity to change it's ID name would make it much easier to label and identify items in the scene graph.   This saves you from going to the opposite side of attributes panel to change the ID.

**Comment by dmarcos** [comment]
We have to handle name collisions if we're changing the ID

**Comment by ngokevin** [comment]
Alternatively, prompt for an ID on create:
1. Press create.
2. Input field automatically focused (with `entity` as default placeholder), start typing.
3. Press enter to confirm.

Collisions are manageable, that's more of a factor to whether the extra code/effort is appropriate for the milestone.

**Comment by fernandojsg** [comment]
I already have a function to handle ID collision on a WIP entity clone branch so it won't be a problem.
Regarding the workflow that @ngokevin proposes, I could see it ok if most of the users will add an ID to each entity, as this is probably not the case I wouldn't highlight the input by default, but as it will be selected, the user can just press enter and modify its default name.

**Comment by ngokevin** [comment]
not a frequent action for our workflows, IDs are usually defined beforehand in source and not edited with inspector
