### ISSUE TITLE
Vec3 doesn't reflect changes when componentChanged

### ISSUE THREAD

**Issue by fernandojsg** [aframevr/aframe-inspector#176]
When you modify the `position`, `rotation` or `scale` of an object using the transforms gizmos or directly from the DOM inspector, they don't change the value of their `vec3` widgets.
This is something we just missed on the latest changes of the `NumericWidget` as it was working properly in the early versions. /cc @ngokevin

**Comment by ngokevin** [comment]
My bad. One day, we'll have unit tests :)
