### ISSUE TITLE
consider tweaking panel heading styling

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe-inspector#178]
This is minor and purely visual, but because they're highlighted, they look like they can be clicked or interacted with. My eyes keep getting drawn to them amidst the sea of gray.

<img width="1439" alt="screen shot 2016-07-08 at 4 00 57 pm" src="https://cloud.githubusercontent.com/assets/674727/16703766/2b6330bc-4525-11e6-85c6-66ae36dcec60.png">

**Comment by fernandojsg** [comment]
Yep, my fault, in fact @arturitu version has grey text color:
![d9b2602a-450c-11e6-9a35-707f72046010](https://cloud.githubusercontent.com/assets/782511/16703956/3059296c-4572-11e6-8e47-5feb6066467c.png)

I'll change that.

**Comment by dmarcos** [comment]
Yep. UI and selection highlight colors should be different. Can we make the view scene button `a-frame purple`?

**Comment by fernandojsg** [comment]
Closed by the latest changes in the header style while removing the menubar (https://github.com/aframevr/aframe-inspector/pull/221)
