### ISSUE TITLE
Consider adding `contextmenu`s to the entities in the scene graph

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-inspector#18]
https://davidwalsh.name/html5-context-menu

They've been in Firefox for quite some time now. Coming soon to the [other browsers](http://caniuse.com/#search=context%20menu).

**Comment by dmarcos** [comment]
With copy, delete commands.

**Comment by fernandojsg** [comment]
Yep, I find `clone` to be very useful to have in the context menu too.

**Comment by arturitu** [comment]
If the editor will be accesible for touch devices (for ex. #54) perhaps is not a good solution, and I'm not sure if context-menu will be intuitive in a near future for web-based tools users.

**Comment by cvan** [comment]
Yeah, context menus are a good fallback IMO and great for (power) users (once they discover them). 👍

**Comment by fernandojsg** [comment]
If we add a context menu, we should keep these options also accesible from the main menu too.
But I agree that for "power" users it will be more helpful

**Comment by fernandojsg** [comment]
Do you think it is worth to use `contextmenu` now even if it's not yet supported by most of the browsers? Or better to take a look at some custom made react solution?

**Comment by cvan** [comment]
> Do you think it is worth to use `contextmenu` now even if it's not yet supported by most of the browsers? Or better to take a look at some custom made react solution?

it's been supported by Firefox for, what, 5-6 years now? it'd take not very much time, and Chrome is likely going to support it very soon anyway.

enhancement/good-first-bug issue, we can leave it that way.

**Comment by ngokevin** [comment]
contextmenu has not aged well https://caniuse.com/#search=contextmenu
