### ISSUE TITLE
Use different color for the default, mixin and user properites

### ISSUE THREAD

**Issue by fernandojsg** [aframevr/aframe-inspector#186]
I was thinking about using subtle differences in the color of the label of each property depending if they're the default value, a custom modified value by the user, or if that value is inherit from a mixin.
Any ideas?

**Comment by dmarcos** [comment]
Colors are fine to tell you there's something different about the property but they're not very useful to remember exactly why. Can you rember the colors used by your IDE to hightlight your code?

I don't knoe if there's a way to also label the properties with text without adding too much clutter

**Comment by fernandojsg** [comment]
I believe that just for modified values it will be easy to understand and to learn that as soon as you modified one value it will change the color. The problem come with the mixins, because you could maybe add some extra info, an icon, a cursive, whatever but then you could have a mixin inherit value but that you also modified after, so what to do in these cases.

**Comment by ngokevin** [comment]
I don't think color is the solution. Something like the Computed Styles would work better, but don't think it's too important for now.

<img width="381" alt="screen shot 2016-07-11 at 12 49 05 pm" src="https://cloud.githubusercontent.com/assets/674727/16744408/e0f87abc-4765-11e6-9910-2877ceef3363.png">

**Comment by dmarcos** [comment]
I would start just differentiating the color of default vs user modified values. It is the most bang for the buck. It's useful as a learning tool to answer questions like: How can achieve this cool effect with the material? You can look at the attribute and at a glance see the tweaked values that make that effect.

**Comment by fernandojsg** [comment]
Right now in the "title" tooltip when you've your mouse over the attribute's name, you get:

```
depth:
 - type: 'int'
 - value: 0.3
```

I'll add also `default: 1`

**Comment by feiss** [comment]
Highlighting the difference between default and changed values can be useful. Two subtle alternatives:

Adding a bullet to the property name:
![image](https://cloud.githubusercontent.com/assets/359872/20138453/bb9df2f4-a680-11e6-96a0-b344ba26e78f.png)

Slightly different value color.
![image](https://cloud.githubusercontent.com/assets/359872/20138458/bfbebd46-a680-11e6-8452-daf8c65843c2.png)

**Comment by dmarcos** [comment]
It would be better if the changed values pop up even more. What about make the default values grayish and the modified ones blue?

**Comment by fernandojsg** [comment]
I prefer changing the color of the value instead of adding a bullet next to the name, I also agree with @dmarcos I would prefer something more strong to diferentiate the default values from the rest.

**Comment by fernandojsg** [comment]
@dmarcos @feiss maybe saving the current blue color for the changed values and use a darker color for the default values?

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe-inspector/commit/f4602627f2fd49bb1b56359cdb0c39144dc4b04c
