### ISSUE TITLE
Add tooltip text for icons

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-inspector#20]
![image](https://cloud.githubusercontent.com/assets/203725/16507770/77fdd502-3ee1-11e6-93bd-613d6323d563.png)

using `title` (and `alt`) - or use custom tooltips if you'd like

**Comment by cvan** [comment]
A dupe was filed, #37, but there's more activity there.

**Comment by fernandojsg** [comment]
Yep, I close it and we could keep talking there
