### ISSUE TITLE
Copy&Paste entity

### ISSUE THREAD

**Issue by fernandojsg** [aframevr/aframe-inspector#207]

**Comment by cvan** [comment]
Is this done? What's left here? Btw, filed #312 for some implementation issues.

**Comment by fernandojsg** [comment]
@cvan no, this is about copy and paste the entity itself on the scene (similar to clone) rather than copy the entity to the clipboard to paste in some text editor.

**Comment by cvan** [comment]
Gotcha. That naming is confusing. Can you explain to me the steps you'd take to do this action? You mean like drag-and-drop'ing text markup onto the Inspector/Editor, and it figures out where to inject it?

**Comment by fernandojsg** [comment]
Related https://github.com/aframevr/aframe-inspector/pull/426 @cvan maybe you have an idea on how to detect if it's an OSX or a Windows in order to use `CMD` or `CTRL` for the shortcut?

**Comment by fernandojsg** [comment]
Fixed on https://github.com/aframevr/aframe-inspector/pull/426 and https://github.com/aframevr/aframe-inspector/pull/435
