### ISSUE TITLE
Support analytics when Editor is loaded on non-aframe.io sites

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-inspector#213]
Even `http://localhost:*/http://127.*.*.*:*` analytics, afaict, are not getting recorded. Needs to be designated for a server such as https://aframe.io.

This will require doing creating a hidden `<iframe src="https://aframe.io/ga.html">` and then the parent window (the scene) would `postMessage` to the `<iframe>`'s content window, which would then dispatch the GA/UA events (from the correct domain).

This is how Potatolytics worked. There are probably some great npm packages out there.

**Comment by ngokevin** [comment]
I have it stood up on a temporary account on my email since I don't have access to our GA, it does record `localhost`.

Will add Potatolytics next week.

**Comment by fernandojsg** [comment]
@ngokevin do you have any updates on this? Is it working already?

**Comment by larsbergstrom** [comment]
@ngokevin Did the GA get moved over to the Mozilla GA account? Do you need help with that?

**Comment by ngokevin** [comment]
localhost is tracked ok
