### ISSUE TITLE
Rename aframe editor to aframe inspector

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe-inspector#215]
To better convey the scope similar to DOM inspector

**Comment by fernandojsg** [comment]
Done! Let's update your remotes!

**Comment by ngokevin** [comment]
![](http://vignette3.wikia.nocookie.net/deathbattlefanon/images/f/f4/Inspector_Gadget.png/revision/latest?cb=20150307202754)

**Comment by fernandojsg** [comment]
LOL
