### ISSUE TITLE
Reposition and rename "edit/exit" button

### ISSUE THREAD

**Issue by fernandojsg** [aframevr/aframe-inspector#217]
From the discussion in https://github.com/aframevr/aframe-editor/issues/214 we're removing the menubar so we need to move the `edit/exit` button too.
I was thinking about changing the name to `Edit scene/Play scene` and to put the button at the botton centered horizontally.

Something like this:
<img width="1440" alt="screenshot 2016-07-19 19 58 05" src="https://cloud.githubusercontent.com/assets/782511/16960783/2636be0a-4deb-11e6-9233-f0ff0a2524d5.png">
<img width="1436" alt="screenshot 2016-07-19 19 57 59" src="https://cloud.githubusercontent.com/assets/782511/16960784/26373218-4deb-11e6-83ec-84d6520bb0be.png">

**Comment by fernandojsg** [comment]
<img width="1433" alt="screenshot 2016-07-19 23 36 34" src="https://cloud.githubusercontent.com/assets/782511/16967533/acc3e89e-4e09-11e6-910e-80f89f482d56.png">
<img width="1430" alt="screenshot 2016-07-19 23 36 22" src="https://cloud.githubusercontent.com/assets/782511/16967534/acca6aac-4e09-11e6-951a-9f2273003790.png">
@dmarcos Following the discussion from https://github.com/aframevr/aframe-editor/pull/218

**Comment by fernandojsg** [comment]
Don't know if maybe we should make some special style for the play button? 
<img width="179" alt="screenshot 2016-07-19 23 38 14" src="https://cloud.githubusercontent.com/assets/782511/16967598/fe031a72-4e09-11e6-8e5c-60d16bc915e7.png">

**Comment by ngokevin** [comment]
It's a pretty important button. So maybe just `[Back to Scene]` in red?

**Comment by fernandojsg** [comment]
@ngokevin a text button similar to the `Edit scene` on the top of the toolbar icons?

**Comment by ngokevin** [comment]
Where you had the Play button at https://github.com/aframevr/aframe-editor/issues/217#issuecomment-233774674

**Comment by fernandojsg** [comment]
Yep but I mean that if we put "Back to scene" the rest of the icons won't fit there, so move them below right?

**Comment by fernandojsg** [comment]
Maybe so big? :D
<img width="1436" alt="screenshot 2016-07-20 01 03 32" src="https://cloud.githubusercontent.com/assets/782511/16969549/e073e002-4e15-11e6-8bee-511e5b490866.png">

**Comment by ngokevin** [comment]
I was thinking inline with the other icons at 33-50% of that space

**Comment by dmarcos** [comment]
Yeah we can add just a play icon next to those already in the toolbar

**Comment by fernandojsg** [comment]
@dmarcos but what's the difference from my previous mockups? (eg https://github.com/aframevr/aframe-editor/issues/217#issuecomment-233774674)
@ngokevin something like this? 
<img width="177" alt="screenshot 2016-07-20 01 12 45" src="https://cloud.githubusercontent.com/assets/782511/16969706/32974c42-4e17-11e6-8fa7-e4b6301eeb39.png">

**Comment by dmarcos** [comment]
What about just a fucsia play icon?

**Comment by dmarcos** [comment]
![play](https://cdn4.iconfinder.com/data/icons/ionicons/512/icon-play-128.png)

**Comment by dmarcos** [comment]
We can also wire the `escape` key to play / go back to the scene.

**Comment by fernandojsg** [comment]
@dmarcos like this?
<img width="179" alt="screenshot 2016-07-20 01 16 39" src="https://cloud.githubusercontent.com/assets/782511/16969771/a2c172b8-4e17-11e6-8888-7ba93b5d003f.png">
re `escape` yep that would be great

**Comment by ngokevin** [comment]
I think "Back to Scene" is more clear, I might not understand the action of "playing the scene" as exiting the Editor and that gets even harder to understand by repping it as an icon.

**Comment by dmarcos** [comment]
It looks weird to use a combination of icons and text based buttons.

**Comment by dmarcos** [comment]
It should be one or the other

**Comment by ngokevin** [comment]
maybe, but it's not forbidden. i think the text differentiates/highlights it as a more important action than its immediate neighbors

**Comment by dmarcos** [comment]
Well, the screenshot above does not look very consistent or aesthetically pleasant.

**Comment by dmarcos** [comment]
I actually prefer the button above the toolbar if we're going to go down that route.

**Comment by fernandojsg** [comment]
And what about adding it to the bottom left of the screen? so we could just add text `Back to scene` and leave the toolbar for scenegraph as we've right now just with icons

**Comment by dmarcos** [comment]
bottom left could be an option but it takes vertical space to see more of the scene graph.

**Comment by fernandojsg** [comment]
> I actually prefer the button above the toolbar if we're going to go down that route.

@dmarcos if we go for that one, it will take the same space in the top or at the bottom.
I prefer having icons for the actions, it will save plenty of space, but it's true that `back to scene` is probably the main action around so it should be quite easy to find, and just an icon with different color doesn't seems to mean anything special.

**Comment by fernandojsg** [comment]
re https://github.com/aframevr/aframe-editor/issues/215 for the sake of completeness `s/Edit scene/Inspect scene`?

**Comment by ngokevin** [comment]
Yeah. I would cap case `Inspect Scene`.

**Comment by fernandojsg** [comment]
Ok, I think this is the way I like the most, even if the `Inspect Scene` button size maybe is so big but I believe it looks better that way to fit the `Back to Scene`:
<img width="1430" alt="screenshot 2016-07-20 22 56 40" src="https://cloud.githubusercontent.com/assets/782511/17002782/42427b2e-4ecd-11e6-9b4a-695adb96206d.png">
<img width="1440" alt="screenshot 2016-07-20 22 56 26" src="https://cloud.githubusercontent.com/assets/782511/17002781/42413110-4ecd-11e6-8fed-b0b1d424f77e.png">
What do you think?

**Comment by fernandojsg** [comment]
Closed by https://github.com/aframevr/aframe-inspector/pull/221
