### ISSUE TITLE
Consider generating better filenames than ascene.html for exported scenes

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-inspector#22]

**Comment by arturitu** [comment]
Perhaps named with the ID of the a-scene tag?

**Comment by cvan** [comment]
Not a bad idea. I was thinking of slugifying the `window.location.host + window.location.pathname`. We could have a series of checks.

**Comment by fernandojsg** [comment]
Yep probably using the scene's id and the proposal from @cvan in the case we didn't provide one
