### ISSUE TITLE
When there's vertical scroll bar on the scenegraph and I exit the editor the bar remains

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe-inspector#227]
It happened in chrome. See below:

![scroll](https://s3.amazonaws.com/f.cl.ly/items/2M1T0s150t09431S3r27/Image%202016-07-21%20at%2010.29.48%20PM.png?v=af1ceed5)

**Comment by fernandojsg** [comment]
@dmarcos can you reproduce it? I've never been able to reproduce :|

**Comment by dmarcos** [comment]
I cant reproduce this anymore Chrome (53)
