### ISSUE TITLE
Add dropdown menu to select entity presets while adding a new entity

### ISSUE THREAD

**Issue by fernandojsg** [aframevr/aframe-inspector#228]

**Comment by fernandojsg** [comment]
I need some help here with the dropdown menu on the `+` icon on the scenegraph, basically it will show a list of presets (sphere, cube, plane, light, etc...)
/cc @feiss @nucliweb

**Comment by feiss** [comment]
I think using something like the dropdown list of components is cool enough. Dark background, blue highlighting.


![image](https://cloud.githubusercontent.com/assets/359872/22782867/64725240-eec9-11e6-80b2-2123c2f85734.png)

**Comment by dmarcos** [comment]
Should all the dropdowns be consistent? Either centered or aligned to left?

**Comment by feiss** [comment]
who said centered? ^_^

**Comment by fernandojsg** [comment]
I like it! PR please! :P

**Comment by feiss** [comment]
```
div.context-menu {
  font-family: 'Roboto', sans-serif;
  position: absolute;
  margin-left: -2px;
  margin-top: -8px;
  background: #222;
  z-index: 99999999;
  font-size: 14px;
}
div.context-menu a {
  color: #868686;
  padding: 6px 15px;
}
div.context-menu a:hover {
  background-color: #1faaf2 !important;
  color: #fff;
}
```

**Comment by fernandojsg** [comment]
I believe it needs a larger `z-index`:D

**Comment by feiss** [comment]
http://s2.quickmeme.com/img/88/88f0f2bf2507cf431bf6b63e9f15a4e5b4205bd1ce57f995016c5e75265093a5.jpg

**Comment by ngokevin** [comment]
not going to focus inspector on being a creation tool with primitives atm. although stuff like import from blocks/sketchfab would be good for dropdown
