### ISSUE TITLE
Exported scenes issues

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-inspector#23]
- shouldn't contain A-Frame injected CSS (i.e., `<style type="text/css" data-href="src/style/aframe.css">`).
- offer an option to possibly rewrite the URLs to be absolute (if I exported a scene from http://dev.fernandojsg.com/aframe-editor/example/, then `<script src="js/aframe.js">` should be written as `<script src="http://dev.fernandojsg.com/aframe-editor/example/js/aframe.js">`). I know this gets tricky. Because some people will be using the editor to inspect, edit, and fork others' scenes - while others will use it to quickly tweak their scenes
- remove the injected Editor script (i.e., `<script src="../build/aframe-editor.js"></script>`)
- remove the injected React elements from the Editor (and the `<a download>`)

**Comment by fernandojsg** [comment]
Fixed in https://github.com/aframevr/aframe-editor/pull/181
