### ISSUE TITLE
Google Chrome (52) Scenegraph Scrollbar Visible in Preview Mode When Zoomed

### ISSUE THREAD

**Issue by Coder206** [aframevr/aframe-inspector#231]
When visiting https://aframe.io/aframe-inspector/example at 250% zoom, notice the scrollbar (in [1]) that does not hide in the preview mode (in [2]):

1
![screenshot from 2016-08-02 16-57-35](https://cloud.githubusercontent.com/assets/7758155/17345126/9aca2bfc-58d2-11e6-8c29-c4d714d24fe1.png)

2
![screenshot from 2016-08-02 16-57-53](https://cloud.githubusercontent.com/assets/7758155/17345134/a0f5961a-58d2-11e6-861f-45bae6e19d21.png)

**Comment by dmarcos** [comment]
This is a dup of https://github.com/aframevr/aframe-inspector/issues/227

**Comment by Coder206** [comment]
@dmarcos Oops sorry! I tried searching for it but GitHub never yields good results...

**Comment by dmarcos** [comment]
no prob. this happens all the time. I sometimes report myself the same bug twice
