### ISSUE TITLE
Components panel does not update properly

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe-inspector#234]
1. When switching selected entities. I'm switching from an entity that has a geometry and a material to a light entity that doesn't have them. The geometry and material components still show in the panel ![switching](https://d3vv6lp55qjaqc.cloudfront.net/items/1u0M1p201g2L3q2O3K2c/Screen%20Recording%202016-08-02%20at%2006.18.18%20PM.gif?v=f47050f7)
2. If a an entity is selected and I click somewhere in the scene to deselect it the components panel is not reset: ![reset](https://d3vv6lp55qjaqc.cloudfront.net/items/3A2w1k291v1S1m2I2v2S/Screen%20Recording%202016-08-02%20at%2006.23.14%20PM.gif?v=b4da9a03)

**Comment by fernandojsg** [comment]
I've just tried on `master` and seems to works correctly :\ both on chrome and firefox on osx.
![deselect](https://cloud.githubusercontent.com/assets/782511/17367721/6f374726-5991-11e6-9681-e1d9ab43a2de.gif)
![updatepanel](https://cloud.githubusercontent.com/assets/782511/17367722/6f4c757e-5991-11e6-9165-cb73b25230f9.gif)
I'll try later on windows to see if it's some problem with chrome on windows or maybe cache?

**Comment by fernandojsg** [comment]
I've just tried on windows both on chrome and firefox and it's working correctly. Could you please check if you're on master and flush the cache?
(Btw which software do you use to record gifs on windows? :))

**Comment by fernandojsg** [comment]
@dmarcos could you try this again?

**Comment by dmarcos** [comment]
Just tried on master and works well.
