### ISSUE TITLE
Use `<label>`s where appropriate

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-inspector#24]
To improve usability and ease of use with bigger clicker targets (and the keyboard navigation you get for free with `tabindex`) - and of course for accessibility too.

Examples:

![image](https://cloud.githubusercontent.com/assets/203725/16507882/583328fc-3ee2-11e6-94ad-c1de5079f8f0.png)

**Comment by fernandojsg** [comment]
Done! thank you

**Comment by cvan** [comment]
I was going to file a separate issue, but it seems most of the labels have issues:
1. Clicking on `ID` (under `Attributes > Common`) should focus the ID field.
2. Clicking on `position` (under `Attributes > Common`) should focus the first field (`x`).
3. All `<select>`s are missing labels (e.g., `Attributes > Common > mixins`, `Attributes > Components > Add`).
4. All `<input class="number">`s are missing labels (e.g., `Attributes > Geometry > depth`).
5. All `<input type="checkbox">` fields have a tiny click area because the fields are not contained inside the labels. This makes it very easy to miss the checkbox, and it requires me to click the exact 12×12px area (see screenshot below). (This can be fixed by wrapping the contents of `<div class="row">` in a `<label>`.)

![image](https://cloud.githubusercontent.com/assets/203725/16645969/6afad4d6-43dc-11e6-8d4c-e2ba4da0e809.png)
