### ISSUE TITLE
Back to Scene button overlaps the scroll bar (Firefox / Windows)

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe-inspector#243]
The close button overlaps the scroll bar of the scene panel. ![scroll](https://d3vv6lp55qjaqc.cloudfront.net/items/0d3C43400f2B3R0H3o1j/Image%202016-08-03%20at%203.53.18%20PM.png?v=237c5a98)

**Comment by dmarcos** [comment]
I'm editing the anime-ui scene.

**Comment by fernandojsg** [comment]
Yes, the scrollbar doesn't suppose to be that way the edit button and the toolbar should be fixed and the scroll should just affect the entitylist.
I've added another issue to fix that (https://github.com/aframevr/aframe-inspector/issues/245)
