### ISSUE TITLE
Inspector trying to load assets when used in real scenes

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe-inspector#249]
Inspecting a scene via bookmarklet. Trying to load random assets:

<img width="533" alt="screen shot 2016-08-08 at 3 43 26 pm" src="https://cloud.githubusercontent.com/assets/674727/17498887/e9b732e0-5d7e-11e6-8f17-939dd20ce3e7.png">

**Comment by fernandojsg** [comment]
Yes, I'll remove the texture dialog for 0.3.0, and we'll fix it and include it again for 0.4.0
