### ISSUE TITLE
Make it more obvious that transforms can be edited

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-inspector#25]
![image](https://cloud.githubusercontent.com/assets/203725/16507897/7602b780-3ee2-11e6-84ae-2e77da0d8076.png)

I know it's like this in the mocks, but because there are no borders around the numbers, they look readonly. Especially since `Type: A-ENTITY` actually is read only.

**Comment by dmarcos** [comment]
Flat design and usability don't like each other

**Comment by cvan** [comment]
A [simple underline](https://getmdl.io/components/index.html#textfields-section) could suffice:

![image](https://cloud.githubusercontent.com/assets/203725/16508239/f913279c-3ee5-11e6-8801-946e968bfcec.png)

![image](https://cloud.githubusercontent.com/assets/203725/16508238/f497b9f8-3ee5-11e6-9821-ea974fca014d.png)
