### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe-inspector#255]
With `a-frame` master. Open the anime-ui scene and click on the `a-collada-model` entity. I see the error above.

**Comment by fernandojsg** [comment]
@dmarcos can you give it a try on master? I've just tried and it seems to be solved with the latests PRs
![selectcollada1](https://cloud.githubusercontent.com/assets/782511/17609093/0b08f0d6-6032-11e6-88cf-657f2abbc8ea.gif)

**Comment by fernandojsg** [comment]
I'm closing it as I can't reproduce it anymore with the latest changes
