### ISSUE TITLE
The inspector is somewhere doing `stopPropagation` and capturing all the `keyDown` events

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe-inspector#257]
AFrame cannot capture `ctrl-alt-e` to close the editor

**Comment by fernandojsg** [comment]
I'm looking around and I've just found that I do stop propagation on the scenegraph but just for arrow cursors up and down :\

```
  onKeyDown = event => {
    switch (event.keyCode) {
      case 38: // up
      case 40: // down
        event.preventDefault();
        event.stopPropagation();
        break;
    }
  }
```

**Comment by fernandojsg** [comment]
Closing this one, as the problem it comes from removing the keydown listener when the component is paused, and when the editor is running the whole scene is paused.
