### ISSUE TITLE
Can we allow folks to edit the entity Type?

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-inspector#26]
![image](https://cloud.githubusercontent.com/assets/203725/16507910/96791716-3ee2-11e6-9f98-46291e7b1710.png)

**Comment by dmarcos** [comment]
I would call it `HTML Element` or just `Element`. Better than type

**Comment by ngokevin** [comment]
Or `Node`.

But it wouldn't be editable.

**Comment by cvan** [comment]
`Entity Name`?

**Comment by ngokevin** [comment]
It's trying to communicate the HTML element tag name.

**Comment by cvan** [comment]
> It's trying to communicate the HTML element tag name.

I know that. And, I posted a related issue with a comment here: https://github.com/aframevr/aframe-editor/issues/41#issuecomment-229827314

**Comment by ngokevin** [comment]
ok sorry

**Comment by ngokevin** [comment]
The `ID` serves as the Entity Name.

Name (connoting instance) is different from type (connoting class).

**Comment by cvan** [comment]
yeah, gotcha. if this verbiage is confusing for me, it'll likely be confusing for others. that's why I'd suggest going with this treatment - makes it pretty unambiguous IMO:

![image](https://cloud.githubusercontent.com/assets/203725/16508699/8fca4356-3eea-11e6-9618-c3e5e1ffb6f1.png)

**Comment by cvan** [comment]
if I could see all the different combinations with a complex scene, I'd probably be able to give a better recommendation. hard to make judgements here.

**Comment by ngokevin** [comment]
Agreed it's not the best name and the style helps. Node/Element, or just flush left `<a-entity>` without a label would help. `<a-entity>` alone with that styling might do it

**Comment by dmarcos** [comment]
I like `<a-entity>`. It reinforces the relationship between the DOM and what you see in the editor

**Comment by fernandojsg** [comment]
Yep, I like the `<a-entity>` solution too, and about the description does `HTML Element` work for you?
<img width="313" alt="screenshot 2016-07-02 01 57 41" src="https://cloud.githubusercontent.com/assets/782511/16536868/76313fd0-3ff8-11e6-8000-53fa650914b9.png">

**Comment by dmarcos** [comment]
Maybe just `<a-entity>` aligned to the left with no `HTML Element` label.

**Comment by fernandojsg** [comment]
It breaks a bit the `label - value` widgets, isn't it?, maybe adding it to the right on the `COMMON` title? similar to how the multiple component instanceId are displayed right now?

**Comment by ngokevin** [comment]
I think it's good to break the pattern since it shows that it's not editable like everything else.

**Comment by fernandojsg** [comment]
Ok, so here you have it!
<img width="297" alt="screenshot 2016-07-02 10 57 11" src="https://cloud.githubusercontent.com/assets/782511/16539439/c2d5e37c-4043-11e6-852b-281e2a13bd08.png">
