### ISSUE TITLE
Entity clone icon is ambiguous

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-inspector#262]
![image](https://cloud.githubusercontent.com/assets/203725/17610340/f0e670c4-5ff1-11e6-878c-49d7721350ed.png)

**Comment by cvan** [comment]
I like Vizor's "Duplicate" icon:

![image](https://cloud.githubusercontent.com/assets/203725/17803942/39c58cbe-65ae-11e6-9d3a-e3d1dcc37cd9.png)

**Comment by ngokevin** [comment]
merging the multiple icon threads
