### ISSUE TITLE
"Save" (Download HTML) action is misleading - use different icon?

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-inspector#264]
I expected the icon of the floppy disk to save my scene. Instead, it downloaded the exported HTML of my scene.

![image](https://cloud.githubusercontent.com/assets/203725/17610522/b5ecef8c-5ff3-11e6-9d8b-d1e6c75c16e0.png)

**Comment by fernandojsg** [comment]
@cvan what do you think about using a `download` icon instead? Something like http://fontawesome.io/icon/download/

**Comment by cvan** [comment]
yep, I think that one works well
