### ISSUE TITLE
Consider making scenegraph actions larger

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-inspector#265]
Suggested changes:
- Add descriptive text to each
- Have each action be on its own line

This is what the action icons look like now:

![image](https://cloud.githubusercontent.com/assets/203725/17610522/b5ecef8c-5ff3-11e6-9d8b-d1e6c75c16e0.png)

I'd suggest some treatment like this:

![image](https://cloud.githubusercontent.com/assets/203725/17610694/690573ea-5ff5-11e6-93ef-be0e2edc275a.png)

**Comment by cvan** [comment]
You could even abbreviate the copy:
- Copy to clipboard
- Download HTML
- Insert

**Comment by cvan** [comment]
Also, the "clipboard" icon looks like two sheets of paper to me. I know it's fontawesome's, but it just doesn't look like "copy to clipboard" to me.

**Comment by feiss** [comment]
GitHub's clipboard icon looks more evident: 

![image](https://cloud.githubusercontent.com/assets/359872/17771420/1916cbce-6543-11e6-9b55-ad79fd40bd8f.png)

"Insert" is not very descriptive, you don't know what you are going to insert. I think the term "Entity" or "Item" is needed, I suggest "New entity", "Add entity" or "Add new entity"

**Comment by feiss** [comment]
I would also rename "Back to Scene" and "Inspect Scene" button to "VR MODE" and "EDIT MODE"

**Comment by cvan** [comment]
good feedback 👍

**Comment by ngokevin** [comment]
they are infrequent actions so better to preserve vertical space for seeing more of the scene
