### ISSUE TITLE
Add tagName for every entity in scenegraph

### ISSUE THREAD

**Issue by fernandojsg** [aframevr/aframe-inspector#266]
This will reinforce the relation between the DOM and the scenegraph, but I'm not sure about the size it could get. I believe it's not common to have very long names for ID, but still..
We could define a `max-width` for the sidebar both the ID or the components icons could be truncated using `text-overflow: ellipsis` or similar.
What do you think?
<img width="1419" alt="screen shot 2016-08-12 at 18 09 29" src="https://cloud.githubusercontent.com/assets/782511/17628938/fb41cdfe-60b7-11e6-884f-0a087573fcec.png">

**Comment by feiss** [comment]
I know it's pretty different, but what about something like this?

![image](https://cloud.githubusercontent.com/assets/359872/19689505/ea9cfc12-9acd-11e6-8164-ce7d4ba9b23f.png)

Sorted in a table seems much more legible, you could use column headers for sorting, and it's easy to add more information in new columns without breaking the ui. For example, I added visibility and collapse icons.

The drawback is that it needs much more space. Solutions: Flexible scenegraph sidebar and smaller font size.

**Comment by fernandojsg** [comment]
I like it a lot even if it's a little bit too wide maybe? What about including some buttons on the top to toggle the visibility of the `type` and `components` columns so we could save some space if needed?

**Comment by dmarcos** [comment]
componente might be missleading because no all of them will be represented in the icon list

**Comment by fernandojsg** [comment]
Maybe we could encourage the components creators to provide an icon when registering theirs components on the `aframe-registry`.
In any case we could add a random color icon for the unknown components or even create a "gravatar" random style icon to associate with these unknown components.

**Comment by ngokevin** [comment]
That's a neat idea! The primary purpose of the scene graph is to find an entity, which puts emphasis showing primarily the ID/class. The type shouldn't take much space; every thing is inherently `<a-entity>`. The detail of the entity can be delegated to the right panel. Adding toggles to hide columns further complicates things (the visibility toggle is important though).

I do like the idea of mirroring the HTML though, perhaps:

![](https://cloud.githubusercontent.com/assets/782511/17628938/fb41cdfe-60b7-11e6-884f-0a087573fcec.png)

keep the brackets, but exclude the tag name?

**Comment by feiss** [comment]
that's the same screenshot from above, @ngokevin

**Comment by fernandojsg** [comment]
@feiss he was so impressed! :P

**Comment by ngokevin** [comment]
Yeah, I just re-posted to say I like that one.

**Comment by fernandojsg** [comment]
I really like the proposal by @feiss my main concern is about a real use case, where most of the components won't have an `ID`. Maybe having both in the same column similar to:
![image](https://cloud.githubusercontent.com/assets/782511/22784420/4164ad8c-eed0-11e6-92e1-7db2892f62ff.png)

**Comment by fernandojsg** [comment]
a WIP version messing with @feiss 's idea
![image](https://cloud.githubusercontent.com/assets/782511/22797818/0602cae6-ef00-11e6-8420-b142578fc1ed.png)

**Comment by fernandojsg** [comment]
Using light grey instead of white for the IDs
![image](https://cloud.githubusercontent.com/assets/782511/22798090/00f8ff1a-ef01-11e6-95c0-5f81a6a020f5.png)

**Comment by fernandojsg** [comment]
Darker color for non-visible entities
![image](https://cloud.githubusercontent.com/assets/782511/22800304/2f64adce-ef09-11e6-92f7-fecc4e2c1c53.png)

**Comment by feiss** [comment]
cool, I think it's a nice solution. Are you going to include all the other component icons?

**Comment by ngokevin** [comment]
Do we need the tag name if everything is pretty much `<a-entity>` and that's what we promote using? Or maybe only show the tag name for primitives.

**Comment by fernandojsg** [comment]
@ngokevin I like that idea, i've removed all the `<a-entity>`, showing them just in the cases where the entity doesn't have an ID:
![image](https://cloud.githubusercontent.com/assets/782511/22806086/b5a9379e-ef20-11e6-8d7c-c1e6efc1beb4.png)

@feiss I'll add them in a similar way as you proposed but I didn't have time to add the columns. Maybe we could remove them in this release and work on that for the next release including the icons for the next of the sensitive components?

**Comment by fernandojsg** [comment]
Fixed in https://github.com/aframevr/aframe-inspector/pull/437
