### ISSUE TITLE
Posibility to save the scene to codepen or other hosting service

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe-inspector#27]
That would allow for quick iteration and easy sharing of derivative work.

**Comment by dmarcos** [comment]
Besides saving the scene locally.

**Comment by fernandojsg** [comment]
Some info: https://blog.codepen.io/documentation/api/prefill/

**Comment by cvan** [comment]
Check out https://react.rocks/example/esnextbin - it uses anonymous GitHub Gists well. If you have questions, let me know.

**Comment by dmarcos** [comment]
This is a differentiation with respect to native tools like Unity. Open, Edit and Share workflow is much harder in native

**Comment by cvan** [comment]
Check out http://hyperdev.com/ too

**Comment by jsantell** [comment]
How would this work (along with #382) when using local assets or scripts/components?

**Comment by cvan** [comment]
With [budo](https://github.com/mattdesl/budo), browsersync, webpack, etc. dev tools, a local dev server could rewrite the routes.

[Gomix](https://gomix.com/) (formerly Hyperdev) offers a nice integrated Assets uploader that lets you reference assets locally and rewrites the paths to use absolute URLs on its CDN. Check out this boilerplate project: https://devilish-hip.gomix.me

Something similar to that approach would be the easiest. I've got a few ideas if someone wants to help tackle this workflow in Q1.

**Comment by ngokevin** [comment]
Local scripts can be XHRed and be turned into a script tag with innerHTML.

**Comment by dmarcos** [comment]
I would not handle local stuff for V1. The use case would be similar to codepen. Open an existing online scene, tweak it and share it.  We can later look at more advanced stuff

**Comment by Utopiah** [comment]
Had a similar discussion this morning, definitely needed. Newcomers have usually no sysadmin skills so being able to visually edit a scene get them very excited until they try to save their result and get completely lost.

What about sending UploadCare then referring to it like with Apainter?

**Comment by cvan** [comment]
A few services to point to:

* https://gomix.com/community supports backend + frontend, with a built-in Asset uploader
* https://esnextb.in/ supports ES6, npm packages, etc.
* https://runkit.com/docs/endpoint is similar
* http://requirebin.com/ is similar
* https://thimble.mozilla.org/ and https://codepen.io/ use [CodeMirror](https://codemirror.net/)
    * Thimble has a kind-of file manager
    * CodePen has an asset uploader (albeit with low filesize limits) for paid pier accounts
* https://c9.io/ is a built-in IDE, like Sublime Text, in the browser/cloud

**Comment by Utopiah** [comment]
Naive version https://www.youtube.com/watch?v=CFH7cK1tJME

**Comment by dmarcos** [comment]
@Utopiah nice! Can you describe a bit the approach?

**Comment by Utopiah** [comment]
@dmarcos shamefully basic 

1. endpoint that saves the HTML to an .html file then sends back the URL to the inspector
1. inspector send the HTML to the endpoint then open pages with received URL

cf https://vatelier.net/MyDemo/aframe-inspector/saving/doc.html

PS: can use <a-scene inspector="url:https://vatelier.net/MyDemo/aframe-inspector/saving/js/aframe-inspector.js"> for testing (make sure to go in and out of the inspector once on the saved scene, older bug from inspector, solved using `document.getElementById('camera').setAttribute("camera", "active:true")`)

**Comment by Utopiah** [comment]
With all the recent work on fixing saveSceneToHTML() and cleaning up the resulting HTML #482 #485 #443 #487 #488 #489 #490 #478 this could be worked on again.

Investigating for JSBin https://jsbin.com/help/api#writeapi and glitch https://twitter.com/utopiah/status/827193459937271810 cf prior exploration.

**Comment by ngokevin** [comment]
not a common workflow and saving the scene without having access to source is pretty impossible. glitch has worked well for remixing
