### ISSUE TITLE
Style selectbox and checkbox

### ISSUE THREAD

**Issue by fernandojsg** [aframevr/aframe-inspector#282]

**Comment by fernandojsg** [comment]
Selectbox done in https://github.com/aframevr/aframe-inspector/pull/339

**Comment by fernandojsg** [comment]
@nucliweb do you mind helping us with this issue? Basically is styling the checkboxes similar to the rest of the widgets (dark grey and light blue)

**Comment by nucliweb** [comment]
Yes 😉

**Comment by feiss** [comment]
Neat radio styling using css: http://codepen.io/triss90/pen/XNEdRe

**Comment by nucliweb** [comment]
I just saw it yesterday in Codepen's mailing ;)

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe-inspector/commit/e516f87d68d4b53f3bd29db62fec1a427c85e9cb
