### ISSUE TITLE
add component default option should be blank

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe-inspector#291]
It currently shows `blend-character-model`.

<img width="356" alt="screen shot 2016-08-17 at 2 39 29 pm" src="https://cloud.githubusercontent.com/assets/674727/17754250/73087846-6488-11e6-908f-929ff9f21fdb.png">

**Comment by fernandojsg** [comment]
Fixed on https://github.com/aframevr/aframe-inspector/pull/339
