### ISSUE TITLE
Style scrollbar

### ISSUE THREAD

**Issue by fernandojsg** [aframevr/aframe-inspector#297]

**Comment by cvan** [comment]
Are you suggesting hijacking the native scrollbar/scrolling? If you're suggesting just pushing it to the side so it's not visible, and maybe showing a custom one, that's fine.

**Comment by fernandojsg** [comment]
I think so, I don't have much experience styling scrollbars so any help will be more than welcome. Current scrollbar style ruins the UI quite a bit :)

**Comment by cvan** [comment]
Check out http://theculturetrip.com/europe/greece/articles/spotlight-on-the-stavros-niarchos-cultural-center/ or http://www.apple.com/mac/ at a mobile width for an example. There's a little hackery involved (you need a parent element, need to add some extra padding, and then clever cosmetic styling to simulate the scrollbar).

**Comment by cvan** [comment]
Also, I'm sure there is at least _one_ proper solution on CodePen: https://codepen.io/search/pens?q=scrollbar&limit=all&type=type-pens

**Comment by ngokevin** [comment]
wontfixing for now. only chrome supports, and don't feel like maintaining hacks / faked scrollbars
