### ISSUE TITLE
More subtle grid

### ISSUE THREAD

**Issue by feiss** [aframevr/aframe-inspector#299]
I find the grid very bright and distracting. I suggest flipping its two colors:

**Secondary grid lines:** Use the current darker gray color of the main axes 
**Main axes lines (x,z):** Lighter gray (the current used in the secondary lines of the grid)

**Comment by fernandojsg** [comment]
Good point! Sadly we should update the current threejs used on aframe as the current release that we're using doesn't support coloring the Grid helper :(

**Comment by feiss** [comment]
I see... What about drawing the grid by ourselves? It's pretty trivial, I guess..

**Comment by fernandojsg** [comment]
Yep, I think that finally we'll need to create our own helper. In fact I really like the vizor's grid style.

**Comment by feiss** [comment]
That one with circles? nope nope please :sweat_smile: I think a grid of parallel lines helps to better perceive the distance and the relation between objects, and gives a better spatial understanding.

**Comment by fernandojsg** [comment]
You can switch from circles to squares! :P and they have written the distance in the corner.
<img width="1020" alt="screenshot 2016-08-18 13 36 56" src="https://cloud.githubusercontent.com/assets/782511/17772401/dfa715be-6548-11e6-80fd-4ba33f8887dd.png">

**Comment by feiss** [comment]
ok, that's better :D

**Comment by feiss** [comment]
you can change colors, apparently!
http://stackoverflow.com/questions/30162023/gridhelper-axis-different-colours

**Comment by fernandojsg** [comment]
@feiss Yep, it was a legacy code from the previous versino of threejs where we couldn't change the color, but in the current version is possible to change the color. Just let me know which colors do you prefer and I'll change them ^_^ or feel free to do a PR: https://github.com/aframevr/aframe-inspector/blob/master/src/lib/viewport/index.js#L40

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe-inspector/commit/1434c2001f1bee785b3479a062096f4a68048dc7
