### ISSUE TITLE
Add support to create Mixins

### ISSUE THREAD

**Issue by fernandojsg** [aframevr/aframe-inspector#3]
Mixins could be created directly from an entity by selecting the components and attributes we would like to add to the mixin.

**Comment by ngokevin** [comment]
Mixin creation through the editor is sort of scope creep, IMO. Mixins support not having to repeat code. Having them in the editor is sort of exposing code internals.

**Comment by fernandojsg** [comment]
The original idea was to create a simple modal with the list of components and attributes that you've modified, so you could click which components and attributes you would like to add to your mixin in a "blackbox" way. 
<img width="234" alt="screenshot 2016-07-01 02 18 01" src="https://cloud.githubusercontent.com/assets/782511/16508314/10d22030-3f32-11e6-9ac1-d003de6aef78.png">
What do you think? In any case if you don't like the possibility to add new mixins, would you also propose to remove the features to add a mixin to the entity or see the list of mixins already attached?

**Comment by ngokevin** [comment]
I guess it would help if you wanted to repeat a set of values across multiple entities. Though it adds a lot of complex UI and concepts. It's not something I would use since I'd rather code the mixin (and I'm working on mixin stylesheets), but I don't speak for everyone. Your call, just my input.

**Comment by ngokevin** [comment]
not a common workflow. mixins created from source
