### ISSUE TITLE
Unable to select items in components menus

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-inspector#30]
They keep collapsing when I try to hover over them, because they're overlapping the components below:

![component_menus](https://cloud.githubusercontent.com/assets/203725/16508092/3ef4b05c-3ee4-11e6-91bf-946bbad4831a.gif)

**Comment by fernandojsg** [comment]
Yep, in fact I should make them clickable, to be ready for touch devices.

**Comment by cvan** [comment]
It's visible in the animation above, but I wanted to reiterate that the `z-index` of the drop-down menu needs to be adjusted such that the vertical dots aren't on top. (Personally, I would opt for icons w/ tooltips instead of the drop-down.)

**Comment by fernandojsg** [comment]
Removed the contextmenu in https://github.com/aframevr/aframe-editor/pull/189
