### ISSUE TITLE
Multiple selection support

### ISSUE THREAD

**Issue by feiss** [aframevr/aframe-inspector#301]
Multiple selection is a complex issue, but it could be simplified and limited to basic operations like transforms and simple edits:

S= list of current selected objects
- If user LMB on empty space, S=[ ]
- If user LMB on an item,  S= [item]
- If user ctrl+LMB on an item that is not selected, it adds the item to S
- If user ctrl+LMB on a selected item, it removes from the item from S
- ctrl+a selects all objects in the scene

If more than one object is selected:
- The center of transformation (the helper axis) is in the average position of all the selected objects, and all transforms (translation/rotation/scale) are relative to that position.
- No data is shown on the inspector panel (panel on the right), just "Multiple selection"
- Copy/paste/duplicate/delete/scenegraph operations affect all selected objects

**Comment by ngokevin** [comment]
I wonder if we'd think about this differently if we framed this tool as complementary to code rather than a end-to-end tool. If so, then we could prescribe developers group their entities if they want to do a batch transform. This is a good prescription because if we are trying to do the same transform operations to multiple entities, then they probably belong in a group in code.

``` html
<!-- Grouping in code. -->
<a-entity position="5 0 0">
  <a-box></a-box>
  <a-box></a-box>
  <a-box></a-box>
</a-entity>
```

vs:

``` html
<-- Output of multi-select and applying individually. -->
<a-box position="5 0 0"></a-box>
<a-box position="5 0 0"></a-box>
<a-box position="5 0 0"></a-box>
```

**Comment by cvan** [comment]
FWIW, with Chrome's Developer Tools, you can pretty sloppily copy and paste anything from the Styles inspector and the resulting clipboard output is correct. Can we do something similar?

**Comment by ngokevin** [comment]
best practice to group entities?

**Comment by feiss** [comment]
Multiple selection and grouping are different things, you may want to modify multiple entities (ie. Moving the same distance) that are completely unrelated among them..

But it's ok, I didn't miss this feature much.

**Comment by feiss** [comment]
"It's ok" as in "yeah ok, we can live without this --although any serious app have this feature" :oD
