### ISSUE TITLE
Front/Left/Top/Perspective views

### ISSUE THREAD

**Issue by feiss** [aframevr/aframe-inspector#302]
Current perspective view is perfectly convenient and useful, but some users may want to view the scene from top/front/left orthographic views. I suggested in #298 keys 1,2,3,4 for switching to those views. 

These orthographic views are useful for aligning and setting the layout of objects with more precision, and having a different perspective of the scene.

The position of these 4 cameras should be remembered, so when the user switch back to the perspective camera, it stays in the same position as before.

Please note I'm not talking about having many simultaneous 3d views. Just one. 

The grid should be seen in all orthographic views, in its own axis.

The name of the current camera should be displayed in a corner of the 3d view, and clicking/tapping on it  would display a list with the available cameras:

![image](https://cloud.githubusercontent.com/assets/359872/17772146/6b70ddac-6547-11e6-9537-b1a417bf4fa0.png)

![image](https://cloud.githubusercontent.com/assets/359872/17772155/74f02662-6547-11e6-955f-cab8f29518e4.png)

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe-inspector/commit/26eb77f76b58fe9ae7a2e90cb2455161c57c181f
