### ISSUE TITLE
Smarter organization of component properties

### ISSUE THREAD

**Issue by feiss** [aframevr/aframe-inspector#303]
Component properties are currently displayed in the order defined in the schema. That's fine, so smart ordering of properties can be set. But now they are pretty random. I propose ordering them from "most useful/used" to "less useful/used".

Also, it would be very interesting to add little additions to the schema spec (aside, apart from the official spec, as a very optional and cosmetic addition to the schema for the editor) so properties could be arranged in groups:

Now:
![image](https://cloud.githubusercontent.com/assets/359872/17773141/32881a40-654d-11e6-95ad-e97e8248e7be.png)

After (just a quick sketch):
![image](https://cloud.githubusercontent.com/assets/359872/17773154/40335f24-654d-11e6-9ac4-1f73c9438581.png)

The improvement in legibility would also allow to have less vertical margin between the fields.

**Comment by fernandojsg** [comment]
Yes, we could include a way to define this groups without modifying the current schema.
The user could define it, otherwise the attributes will be shown in the same order as defined in the schema.
The way to define the groups could be something like:

``` json
[
  {
    "name": "size",
    "attributes": [
      "width",
      "height",
      "width"
    ]
  },
  {
    "name": "segments",
    "attributes": [
      "segmentwidth",
      "segmentheight",
      "segmentwidth"
    ]
  }
]
```

**Comment by ngokevin** [comment]
I think alphabetical is the easiest. There will be many third-party components and geometries that we won't have much control over or insight into. Right now, it seems we could try to manually sort the properties given there aren't very components to choose from, but in the long run it's easiest to be agnostic and do alphabetical.
