### ISSUE TITLE
Consider adding links to the docs for each component + property

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-inspector#31]
![image](https://cloud.githubusercontent.com/assets/203725/16508115/8c4c28ee-3ee4-11e6-9389-d879410412e3.png)

Definitely could come later, but it'd be nice if there was some (?) help icon or something that could link me to the docs to learn about it.

**Comment by fernandojsg** [comment]
Considering that we should maintain those links for each attribute and they can change from time to time, I'll be more useful to add a link per component, similar to what Unity does (in the same level of the delete buttom):
<img width="287" alt="screenshot 2016-07-08 12 26 10" src="https://cloud.githubusercontent.com/assets/782511/16684793/3dcdecec-4507-11e6-8216-8296ff6ce3b9.png">

**Comment by fernandojsg** [comment]
This should be defined by the component itself right? Add some ìnfo_url`or similar parameter when calling`registerComponent`

**Comment by ngokevin** [comment]
Maybe in the `aframe-components` file where we can place metadata.

For standard components, we can hardcode more or less the docs.

**Comment by fernandojsg** [comment]
@ngokevin Right now in https://github.com/aframevr/aframe-components we've `components.json` to define third-party components with their js URL, author, doc/reference url. 
For core components we won't use that json so I'm thinking if it's better to create another json in that repo just to link the help for the core components, or if, as we'll do this special case just for the core components, it could be maybe better to just add a constant file on the editor right now.

**Comment by ngokevin** [comment]
The standard components link can be hardcoded/determined, they are predictable to link to the A-Frame site.

**Comment by fernandojsg** [comment]
I'm hardcoding them now on the editor, but just out of curiosity, why all the component's docs have the following url `https://aframe.io/docs/0.2.0/components/{componentName}.html` but it doesn't works for camera that links to `https://aframe.io/docs/0.2.0/components/` -_-

**Comment by ngokevin** [comment]
I'll create a redirect for those...it's because its the first page alphabetically so we give it index.

**Comment by fernandojsg** [comment]
Ok, right now I've created a hack for that specific case, I'll remove that once we'll have the new docs: https://github.com/aframevr/aframe-editor/pull/211/files#diff-c6971febeacec907de2b39495b6bc11dR129
