### ISSUE TITLE
"Copy HTML to clipboard" icon for entity is ambiguous and easy to miss

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-inspector#311]
I couldn't find the "copy html" button for the entity (like the buttons next to each component).

Then, I found some button at the very, very top, but I couldn't tell what it was:

![image](https://cloud.githubusercontent.com/assets/203725/17805110/b1e23216-65b2-11e6-8f45-869c0c6bc320.png)

So, I hovered over the icon to reveal its `title` to identify what it was:

![image](https://cloud.githubusercontent.com/assets/203725/17805143/daec9ba6-65b2-11e6-89bb-b5d37e15c289.png)

Whichever treatment is chosen, the "Copy HTML" action (be it icon, button, and/or text) should be consistent everywhere so users can easily identify it.

**Comment by feiss** [comment]
I'd vote for using only an icon, always the same. A more clear one, like github's clipboard icon ![image](https://cloud.githubusercontent.com/assets/359872/17812381/1a557d84-6627-11e6-9b03-0cc4d2f790e4.png) , or a new one more specific, something like ![image](https://cloud.githubusercontent.com/assets/359872/17812409/432f3f9c-6627-11e6-8cac-b7b559750866.png) or ![image](https://cloud.githubusercontent.com/assets/359872/17812426/50260406-6627-11e6-826d-f2e4a10ea6cf.png) (quick sketches)

**Comment by fernandojsg** [comment]
> @feiss congratulations, you have been promoted to `master of icons design`

![image](http://i239.photobucket.com/albums/ff166/eban666/trash/Level_Up_zpsbaf0680e.gif)

I really like these icons. I'll open an issue with the icons that we could need.

**Comment by cvan** [comment]
love them 👍

**Comment by dmarcos** [comment]
We need to consolidate all the fonts. Now we have some int SVG others from `fontawesome`... We will revisit this for 0.5.0

**Comment by ngokevin** [comment]
> I couldn't find the "copy html" button

> found some button

well looks like ya found it.

icons are used everywhere now.
