### ISSUE TITLE
Issues with "Copy HTML" functionality (partially broken?)

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-inspector#312]
![image](https://cloud.githubusercontent.com/assets/203725/17805212/316fa7f2-65b3-11e6-8d90-3b9374ecfcb1.png)

**Problem:**
It appears that only when values _change_ can I `copy html`. So, upon immediately selecting an entity, I clicked on the `Geometry` component's `copy html` button, and it added nothing to my clipboard. When I checked the `skipCache` checkbox, my clipboard now contained `skipCache:true`. But, when I changed the `primitive`, now my clipboard was empty again. I'm confused.

**Proposed solutions:**
- Hide "Copy HTML" button if there are no changes to make.
- Rename "Copy HTML" to "Copy HTML changes" (or "patches" as Vizor calls them).
- Change the functionality so that "Copy HTML" for a Component always copies the entire HTML. (I assume it's on the roadmap eventually to enable granular copy-and-paste functionality for each property? I saw some discussion in issue #301 filed by @feiss. Should a separate issue be filed? This seems important to either allow "Copy all HTML to clipboard" or enable granular singular/multiple copying à la the checkboxes that appear in browsers' Dev Tools' Style manipulation tools).

<hr>

**Problem:**
I change a few values on the `Material` component. I click `copy html` and the resulting text in my clipboard is this:

``` css
flatShading:true;transparent:true;color:#F16745
```

**Proposed solution:**
Can we add spaces between the `:` and `;` delimiters so it's more readable?

I was thinking perhaps actually the output should contain the originating parent Component, like so:

``` html
material="flatShading: true; transparent: true; color: #F16745"
```

But, then I realised that a developer may accidentally replace the other properties in the Component that weren't included

<hr>

**Problem:**
Without modifying any values, if I select an entity and immediately press its `click html` button, the Inspector thinks I modified the colour and this appears in my clipboard:

``` css
color:#F16745
```

**Proposed solution:**
Fix whatever's causing `color` to think it's been changed.

**Comment by dmarcos** [comment]
We should rename `Copy HTML` to `Copy Attribute` and the string result should be:

``` html
geometry="primitive: cylinder; height: 2"
```

This way you can just copy and past in your html
