### ISSUE TITLE
ComponentLoader should not do a synchronous XHR

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-inspector#313]
Never use sync XHRs; they peg the browser.

You could simply make the XHR async, and let `this.components` get set when the XHR loads, as you're doing already. Is there any other reason why it needs to be synchronous? If there is a reason, can you just use a `Promise` that resolves/rejects on load/error?

**Comment by fernandojsg** [comment]
Already fixed with the latest changes from the registry
