### ISSUE TITLE
Consider using Web Worker for XHRs that need to lazy-load metadata (e.g., for components)

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-inspector#314]
If you're worried about XHRs causing pauses in the scene/editor rendering, consider moving all your XHRs to Web Workers and just `postMessage` the JSON back. Wouldn't be more than a few lines of code to shove all the necessary XHRs to a Worker to add some smooth lazy loading.

(Filed because of #313.)

**Comment by fernandojsg** [comment]
@ngokevin do you think we need it with the current implementation?
