### ISSUE TITLE
Raycaster/helpers not working well on embedded scenes

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe-inspector#320]
Embedded scenes in my slides, open up the inspector, select an object, try to use the helper handles https://ngokevin.github.io/aframe-presentation-kit/#/3/1

**Comment by ngokevin** [comment]
This was because my slides has a `zoom` CSS property that was messing things up.

**Comment by fernandojsg** [comment]
https://github.com/aframevr/aframe-inspector/pull/400 :)
