### ISSUE TITLE
Cloning a cloned entity clones the initial entity, not the new modified one

### ISSUE THREAD

**Issue by Utopiah** [aframevr/aframe-inspector#322]
I clone object1 I get object1cloned that I can then modify. 
When I try to clone object1cloned though I get a clone of object1 , not the modified object1cloned

**Comment by caseyyee** [comment]
Yes, I just ran into this issue.

![clone](https://cloud.githubusercontent.com/assets/1560884/19980319/c36090d4-a1ba-11e6-8ca1-0e9daa503c54.gif)

In this image, i'm cloning the blue cone.  When I click the clone button, I get the original entity.

**Comment by fernandojsg** [comment]
@Utopiah @caseyyee could you give it a try using `master` branch? It seems it's fixed already and probably you were using an older version

**Comment by Utopiah** [comment]
@fernandojsg yes fixed here on master (still the case on aframe@0.4.0 though)

**Comment by fernandojsg** [comment]
@Utopiah I believe it should be fixes right, could just give it a try? ;)

**Comment by Utopiah** [comment]
@fernandojsg confirm, works on master/0.4.0 too now
