### ISSUE TITLE
Add a Service Worker

### ISSUE THREAD

**Issue by Coder206** [aframevr/aframe-inspector#323]
Having the code for the Inspector cached on the user's device would decrease loading times but more importantly reduce bandwidth.

**Comment by ngokevin** [comment]
The Inspector actually isn't loaded on devices unless you inject it (e.g., with the shortcut). Service Workers won't work here I think because the domain at which the Inspector is injected will vary.

**Comment by Coder206** [comment]
@ngokevin I understand. I'll close this then.
