### ISSUE TITLE
Add more complete monospace `font-family`

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-inspector#324]
`font-family: Consolas, Andale Mono, Monaco, Monaco, Lucida Console, Liberation Mono, DejaVu Sans Mono, Bitstream Vera Sans Mono, Courier New, monospace;`

**Comment by Coder206** [comment]
@cvan Is this a continuation of the RobotoMono code? (#272)

**Comment by cvan** [comment]
@Coder206 nope, your PR just reminded me that we should have a more verbose `font-family` that covers the default monospace fonts on the popular platforms. so thanks!
