### ISSUE TITLE
Consider making the Scene options more prevalent

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-inspector#33]
![image](https://cloud.githubusercontent.com/assets/203725/16508157/25225d22-3ee5-11e6-8982-6e275bec14a0.png)

if right now, all we have is "Save to HTML" and "Copy to clipboard" - can we pull those out of a drop-down menu and make them more visible? We have the horizontal real estate.

**Comment by fernandojsg** [comment]
From https://github.com/aframevr/aframe-editor/issues/152 we could use `Export` by now and just reword it in the future if we keep adding other functionality that doesn't fit there.
