### ISSUE TITLE
Introduce a keyboard shortcut to toggle the Editor

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-inspector#34]
If the Editor is opened and no form field or anything is focussed, perhaps just pressing `Esc` or `e` or whatever should dismiss the Editor.

And when I'm in non-Editor mode, I should be able to easily invoke the Editor by pressing `option` + `e` or something (again, when only `document.activeElement` is not a form field, `contexteditable`, etc.).

**Comment by fernandojsg** [comment]
WIP by @dmarcos: https://github.com/aframevr/aframe/pull/1599

**Comment by cvan** [comment]
when the aframe-inspector `<script>` gets injected in the page, and the A-Frame shortcut is _not_ invoked, what is the expected behaviour?
