### ISSUE TITLE
Add a link next to "Add component" to the aframe-registry ghpages

### ISSUE THREAD

**Issue by fernandojsg** [aframevr/aframe-inspector#341]
It should link to https://aframe.io/aframe-registry/
I tried to use the same logo, but it doesn't fit with the overall aesthetics.
![image](https://cloud.githubusercontent.com/assets/782511/19396723/bd9c89a8-9244-11e6-86a7-94e72186e7d9.png)

Any idea what to use here? Maybe just the `?` icon as with the components but bigger?
/cc @ngokevin @feiss

**Comment by feiss** [comment]
I can make an icon, remind me next week if I forget

And what about an option in the component list select box? At the end, always visible, that reads "A-Frame Registry components" or sth like that

**Comment by fernandojsg** [comment]
@feiss reminder is here! :P
