### ISSUE TITLE
Add a picture-in-picture view of the scene whilst editing

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-inspector#35]
It'd be nice to see how my scene is changing as I move the camera, for example. The editor wireframe view is nice, but I can imagine it becoming cumbersome going back and forth.

**Comment by caseyyee** [comment]
You can do this by exiting the editor and then using the bookmarklet to re-enter?   I think we could probably add some UI to make this flow more obvious.    I definitely agree that having a scene view would be a better solution.

**Comment by cvan** [comment]
> You can do this by exiting the editor and then using the bookmarklet to re-enter?

yeah, that's my point. having to do that is cumbersome. imagine if the browser Developer Tools took over your entire page and you couldn't see the changes on your page until you exited.

**Comment by caseyyee** [comment]
Gotcha.  I think have a separate view control will help.  Switch between iso view and scene camera.

**Comment by cvan** [comment]
> Gotcha. I think have a separate view control will help. Switch between iso view and scene camera.

that'd be nice, agreed

**Comment by ngokevin** [comment]
can just move camera, orbit controls is more flexible the FPS one. can double click entities to focus. this would also cause perf loss in double rendering.
