### ISSUE TITLE
Change camelCase events to dash-separated for consistency

### ISSUE THREAD

**Issue by fernandojsg** [aframevr/aframe-inspector#357]

**Comment by fernandojsg** [comment]
Btw I've just noticed that Aframe has `componentchanged` and `child-attached` which one should we use? dash-separated right? /cc @ngokevin @dmarcos

**Comment by ngokevin** [comment]
It's been moving to all lower case, no dashes / spaces. A-Frame codebase is like 50/50 right now, so we just chose one.

**Comment by fernandojsg** [comment]
Without dashes and lowercase it could looks a little bit ugly for long events:

```
selected-entity-component-changed => selectedentitycomponentchanged
entity-id-changed => entityidchanged
```

**Comment by ngokevin** [comment]
@dmarcos Go dash convention everywhere?

**Comment by dmarcos** [comment]
I would not use dashes to keep consistency with DOM event names:

https://developer.mozilla.org/en-US/docs/Web/Events

**Comment by fernandojsg** [comment]
Ok, I'll remake the PR to change that way 😢

**Comment by fernandojsg** [comment]
Done! https://github.com/aframevr/aframe-inspector/pull/358
