### ISSUE TITLE
Prettier demo scene

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe-inspector#359]
For when we show off Inspector features / create GIFs

**Comment by Coder206** [comment]
@ngokevin You are referring to: https://aframe.io/examples/showcase/helloworld/ ?

**Comment by fernandojsg** [comment]
I'm sure @feiss could help on this!

**Comment by feiss** [comment]
Cool! Directly to the to-do list

@Coder206 they talk about the example scene in the inspector :)

**Comment by feiss** [comment]
mm what about the default scene in aframe.io website? the A with the trees and all that.

**Comment by fernandojsg** [comment]
@feiss I would prefer something adhoc, with more components to play with, like text, some skybox, jsonmodels and basic primitives around, so simple but looking good
Also the default scene in aframe.io is using a camera that imitates isometric view and I would prefer more first person view
