### ISSUE TITLE
Clone entity

### ISSUE THREAD

**Issue by caseyyee** [aframevr/aframe-inspector#36]
It would be super useful to be able to clone a entity.

**Comment by fernandojsg** [comment]
Should we clone the entity in the same level of the previous entity?

``` xml
<a-scene>
  <a-house>
    <a-door/>
  </a-house>
</a-scene>
```

If I clone `<a-door>` should the new created entity be placed next to the cloned item inside the `a-house` or just added at the end of `a-scene` ?

**Comment by caseyyee** [comment]
I would expect it to show up adjacent to the cloned entity.   

So it would look like:

``` html
<a-scene>
  <a-house>
    <a-door/>
    <a-door/><!-- copy of a-door -->
  </a-house>
</a-scene>
```

This is also consistent with other layer based aops i've used.
