### ISSUE TITLE
component icons on entities are not clear

### ISSUE THREAD

**Issue by caseyyee** [aframevr/aframe-inspector#37]
![image](https://cloud.githubusercontent.com/assets/1560884/16508404/6f0c6106-3ee7-11e6-8137-045c2ea32fac.png)

The camera one is obvious, but the rest are really hard to understand.   I think we could probably do away with them if the components are already present in the attributes panel and just rely on entity labeling/ID.

**Comment by dmarcos** [comment]
Those icons are useful to quickly overview what components an entity contains. We can also make them clickable or show a tooltip with the component properties.

**Comment by caseyyee** [comment]
Those icons are ambiguous.  How is anyone supposed to know what they are?    Removing them would be a better choice.   Clarity matters.

**Comment by fernandojsg** [comment]
I do believe that the icons are quite helpful too, it doesn't mean that the current style or the current icon should be the one used of course, it's just the one I choose from fontawesome while waiting for designs from dennis.
I think arguing that they're not meaningful right now doesn't make much sense as most of the software we're using right now doesn't have an incredible meaningful icons, you just get used of what they mean, even the universal icons like a floppy/hard disk to save, how any people know what is it? or the icon to download from the "cloud+arrow down"...
Like @ngokevin says, for simple cases like the ones we have right now and just supporting 4 types can be seems as not the most helpful feature, but if we've the icons for the core components I truly believe they'll be helpful.
For example, imagine that you've a big scene with a lot of geometry like cubes or so, and you've added some lights to some cubes, and also you've attached the handcontrols to some of the cubes. If you go to the scenegraph you can easly spot which ones has the lights (a bulb) and which ones the hand controls (maybe a hand icon or whatever).
It will also works as a quickaccess to that component. Instead of click the entity going to the attributes panel and find the specific component, you could click directly on the component icon and it will show up on the attributes panel, collapsing the rest or so.
I believe not everyone will add Ids to every entity so you'll end up with a huge list of `a-entity` nodes that won't be useful at all.

**Comment by cvan** [comment]
I'm confused about why the `yellowSphere` has a box icon next to it. Am I missing something?

![image](https://cloud.githubusercontent.com/assets/203725/16642617/aa0cad68-43c1-11e6-8699-19c7d223d2c9.png)

**Comment by dmarcos** [comment]
The icons are a temporary placeholder. They are taken from the fontawesome. The box represents the geometry component regardless of the primitive and the picture the material.

**Comment by dmarcos** [comment]
Copied from the comments of an old PR:

> The icons help you understand and navigate the scene. You could click on the camera or material icon and directly expand and highlight the corresponding component. They also help to visually discriminate the entities that have a visual representation vs those that are just structural or for layout purposes.  It's not guaranteed either that all the entities are going to have IDs or a mixin. You will often see just a tree of a-entity elements, the icons are useful to differentiate them. They can also give you info about the component by just hovering on them to reveal their properties on a tooltip panel without having to click on the entity or go to the component list.
> 
> Those icons are learned from experimentation and become familiar once you acquire experience with the tool. A UI feature that is not immediately obvious for a novice it doesn't have to be synonym of bad usability or clutter. Good tools are learnable and while accessible to novices they also provide convenience flows for expert users. The scene graph icons fall in this bucket. As a complete novice you won't probably understand or use them but overtime they are learned and become a more efficient way to do certain operations. I recommend reading all the research on marking menus (http://www.billbuxton.com/MMUserLearn.html) and how good UIs can grow and accommodate to the level of expertise of the user

**Comment by caseyyee** [comment]
Let's think about what the scene graph is for: 

It's to help users understand (and perhaps change) the hierarchy and structure of the scene and how entities relate to each-other.   Anything outside of this can be considered secondary or a responsibility of another interface component altogether (like the attributes panel).    

With that said, let's take a look at what you are proposing:

>  You could click on the camera or material icon and directly expand and highlight the corresponding component
- You aid accessibility of the components by ordering the components in the attributes panel so that your not hunting for them in the first place.  This is covered by  https://github.com/aframevr/aframe-editor/issues/71  

> They also help to visually discriminate the entities that have a visual representation vs those that are just structural or for layout purposes.
- The structure and layout hierarchy is represented by the indentation and parent/child relationship of the entities.   Icons do nothing to help this. 

>  It's not guaranteed either that all the entities are going to have IDs or a mixin. You will often see just a tree of a-entity elements, the icons are useful to differentiate them.

![image](https://cloud.githubusercontent.com/assets/1560884/16664630/c350920c-4435-11e6-82e6-d916dfd8cfa6.png)

Do the icons help here?   I would say no.  The entities are just as ambiguous as they are without the icons.

I covered this issue here https://github.com/aframevr/aframe-editor/issues/108

> They can also give you info about the component by just hovering on them to reveal their properties on a tooltip panel without having to click on the entity or go to the component list.

This is what the attributes panel is for.  This is just clutter and adds complexity where it's not needed.   

Reduce duplicate and redundant design:  https://www.nngroup.com/articles/reduce-redundancydecrease-duplicated-design-decisions/

> Those icons are learned from experimentation and become familiar once you acquire experience with the tool. 
> 
> The scene graph icons fall in this bucket. As a complete novice you won't probably understand or use them but overtime they are learned and become a more efficient way to do certain operations. 

You are trying to use an icon to discern component types.   This becomes difficult very quickly since Icons are known to be very difficult to remember and understand and as such is a terrible association point for components -- even for experts.

There is plenty of research to back-up why icons are in-general, not good for UX:  http://uxmyths.com/post/715009009/myth-icons-enhance-usability

>  Good tools are learnable and while accessible to novices they also provide convenience flows for expert users. 

Intuitive interface > learnable.  Coherency and clarity in the interface are paramount.

**Comment by dmarcos** [comment]
Hovering over component icons is more efficient to inspect a large number of entities without having to click on them and go and see the component panel.

**Comment by caseyyee** [comment]
Just use the arrow keys.  Far quicker than trying to mouse over a bunch of tiny icons.   What problem are you trying to solve for exactly?

**Comment by dmarcos** [comment]
> There is plenty of research to back-up why icons are in-general, not good for UX: http://uxmyths.com/post/715009009/myth-icons-enhance-usability

The visual aspect of each icon is not as important as having a way to quickly overview an entity and efficiently discriminate between them (a light vs camera vs visible entities vs structural entities). In most cases entities won't have IDs and mixins applied.

From the article you mentioned. 

> the team of UIE observed that people remember a button’s position instead of the graphic interpretation of the function

I agree than the positioning of the icons is more important more than their visual aspect. It's a learned skill and spatial memory is faster than visual pattern matching.

**Comment by caseyyee** [comment]
I'm not saying we need no icons.   We need less.   It's a sea of icons right now.

I agree that there are certain components that should be easily identifiable.   But even then, its optional.  Just look at Unity.   No icons in the scene graph.   Does anyone complain about it?    Nope.

![image](https://cloud.githubusercontent.com/assets/1560884/16667204/1d9e3f70-4440-11e6-9fe3-de97aabe79d2.png)

Simple, straightforward, clear.

**Comment by dmarcos** [comment]
> You aid accessibility of the components by ordering the components in the attributes panel so that your not hunting for them in the first place. This is covered by #71

Ordering components how? They are currently sorted alphabetically. What criteria do you use? Determining an order that is clear for everybody is a hard task, specially when considering 3rd party components. If you have good sorting method that it's more efficient and universal than alphabetical order I would like to hear. We talked about having a `collapse all` feature and a free text search box on the top to filter the list of components and make easier to search for something specific you're looking for.

**Comment by fernandojsg** [comment]
> Just look at Unity. No icons in the scene graph. Does anyone complain about it? Nope.

You can always find software that validate your argument, just look at 3dstudio max, cinema4d, etc. Also I wouldn't take Unity as the master of UX out there, but for sure we could take things from it.
Regarding ordering the components, it's probably the easiest way to find the one you want with the current alphabetical order, trying to order "most important" component first, it's something that doesn't makes sense as you don't know which one will be the most important for the user, we've just the common components already on the top.

Another assumption here is that the attributes panel will be always visible but it will be possible to hide it or to have another kind of panel being shown in that sidebar so you can't rely just on the attributes panel to have an overview of the scene.

Also we don't have a current real example scene that could give us an idea of the benefits. Just let's wait until we could have something like the shooter demo for example with all the other components: sounds, hand controllers, and so, and we could discuss about the overall look.

Again, we've talked about this in the previous PR, but this discussion is very time consuming and we've plenty of issues and bugs already filed that I believe will be more important to solve for the first milestone. Why can we just focus our energy on those and leave this one to discuss after we have a stable version. It's not like it's going to change drastically the UI if we've them on or off.

**Comment by cvan** [comment]
Stealing from [this](https://chrisbracco.com/a-simple-css-tooltip/), I got some simple tooltips that take the `title` for the icons and show them on hover:

``` css
/* Add this attribute to the element that needs a tooltip. */
a.button.fa[title] {
  position: relative;
  z-index: 2;
}

/* Hide the tooltip content by default, and position tooltip above the element. */
a.button.fa[title]:after {
  background-color: #000;
  background-color: hsla(0, 0%, 20%, 0.9);
  border-radius: 3px;
  bottom: -125%;
  color: #fff;
  content: attr(title);
  font: 14px/1.2 Roboto, sans-serif;
  left: 50%;
  margin-bottom: 5px;
  margin-left: -35px;
  opacity: 0;
  padding: 7px;
  pointer-events: none;
  position: absolute;
  text-align: center;
  visibility: hidden;
  width: 70px;
}

/* Show tooltip content on hover. */
a.button.fa[title]:hover:after {
  visibility: visible;
  opacity: 1;
}
```

**Comment by cvan** [comment]
Vizor does this nicely: ![image](https://cloud.githubusercontent.com/assets/203725/17803806/851c4a5a-65ad-11e6-8520-f8a8676b0986.png)

**Comment by cvan** [comment]
Related: #262 Entity clone icon is ambiguous

**Comment by cvan** [comment]
Related: #166 Primary CTA buttons w/ icons should have text labels

**Comment by cvan** [comment]
I'd recommend using https://frend.co/components/tooltip/

**Comment by ngokevin** [comment]
icons now denote existence of mesh/camera/text in the object3D map vs. a few components
