### ISSUE TITLE
Json error

### ISSUE THREAD

**Issue by odGit** [aframevr/aframe-inspector#370]
I have a very basic setup: camera + 4 planes. Plain HTML file with aframe.min.js (v0.3.0) included in a header, running on localhost with budo. Once I am opening aframe-inspector, getting following errors. 

In **Google Chrome** ( 53.0.2785.143 (64-bit)Mas OS Serra)

> GET : https://raw.githubusercontent.com/aframevr/aframe-components/master/components.json  fails with 404 error

<img width="1215" alt="json_error_gc" src="https://cloud.githubusercontent.com/assets/1571406/19527323/e1b223ac-9627-11e6-843b-1c8d8e6346fe.png">

In **Firefox** (49.0.1 (64-bit) Mas OS Serra)

> SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 4 of the JSON data

<img width="1269" alt="jsone_error_ff" src="https://cloud.githubusercontent.com/assets/1571406/19527439/4dd7e90e-9628-11e6-8c63-e5a270bd002c.png">

**Comment by fernandojsg** [comment]
@odGit Hi, can you give it a try? I think we had a problem with the github CDN and it was caching our latest deploy. Make sure you've cleaned your browser's cache too

**Comment by odGit** [comment]
ok, I have tried again and still have the same errors (Deleted history, and in Incognito Window).
I looked a bit around and the JSON callback which fails in [aframe-inspector](https://aframe.io/releases/0.3.2/aframe-inspector.js) is this one
`xhr.open('GET', 'https://raw.githubusercontent.com/aframevr/aframe-components/master/components.json', false);`  

in code base 
https://github.com/aframevr/aframe-inspector/blob/master/src/lib/componentloader.js#L22

**Comment by ngokevin** [comment]
We can just ignore it since it's fixed. We moved the components, and it's now fixed in the latest. Will ship it out soon. Thanks for filing!
