### ISSUE TITLE
Add EditorConfig

### ISSUE THREAD

**Issue by nucliweb** [aframevr/aframe-inspector#373]
Add [EditorConfig](http://editorconfig.org/) for helps developers define & maintain consistent coding styles between different editors and IDEs

**Comment by fernandojsg** [comment]
I like it although I must admit I've never used, I just heard about this last week. Do you mind creating a PR? 👼

**Comment by fernandojsg** [comment]
Closed by https://github.com/aframevr/aframe-inspector/pull/374
