### ISSUE TITLE
Camera inside another component

### ISSUE THREAD

**Issue by jacqueslelezard** [aframevr/aframe-inspector#385]
Hi, I'm trying to make the following structure work:
```
          <a-entity wasd-controls="acceleration:75; easing:1; fly: true">
                <a-entity camera look-controls>
                </a-entity>
                <a-collada-model 
                                 src="#spacecraft"
                                 position="0 0 0"
                                 rotation="0 0 0">
                </a-collada-model>
            </a-entity>
```
The first a-entity is the main bloc the user control with his keyboard, the camera should move with it but let the user look around, the collada model should also move but shouldn't follow the camera direction.
Any idea why the camera doesn't work in this configuration ?

**Comment by ngokevin** [comment]
Which part doesn't work?

**Comment by fernandojsg** [comment]
@jacqueslelezard probably you want to include de model as a child of the camera entity?

**Comment by jacqueslelezard** [comment]
When I put the camera inside another entity it doesn't display anything (using aframe 0.3.0). I'll post the complete sample in the afternoon.
(and to be more accurate I want to move the camera and the model together, but allow the user to look around while the model stay static).

**Comment by fernandojsg** [comment]
I believe this is not related to the inspector but aframe itself? Do you mind posting it on stackoverflow?
Thanks! I'm closing it

**Comment by jacqueslelezard** [comment]
@fernandojsg Ah you are right, it's aframe itself, sorry 
I'll put this on stackoverflow as you suggested

**Comment by fernandojsg** [comment]
@jacqueslelezard cool, thanks!
