### ISSUE TITLE
Cannot select newly created entity in scene view.

### ISSUE THREAD

**Issue by caseyyee** [aframevr/aframe-inspector#386]
![select](https://cloud.githubusercontent.com/assets/1560884/19980612/f0179b8a-a1bb-11e6-9600-6321bec78b3b.gif)

Steps to reproduce:

1. Create new entity.
2. Add geometry component.
3. Try to select element in scene view.

I can select the entity only by selecting it from scene graph.

**Comment by fernandojsg** [comment]
@caseyyee are you trying on master? As this should be already fixed by https://github.com/aframevr/aframe-inspector/pull/352

**Comment by caseyyee** [comment]
Seems to be working in master.   Thanks!
