### ISSUE TITLE
Inspector CSS styles should only apply when the Inspector is open

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe-inspector#389]
I am embedding A-Frame scenes into documentation.

1. I have an embedded scene where `body { margin: 0 16px }`.
2. I open the Inspector and close it.
3. The Inspector CSS styles are still applied (it adds `margin: 0` to the body, and `font-size: 12px`.

## Before

<img width="1433" alt="screen shot 2016-11-15 at 4 10 52 am" src="https://cloud.githubusercontent.com/assets/674727/20305274/86864f22-aae9-11e6-9ecd-e9c26e6328a5.png">

## After

No longer centered.

<img width="1436" alt="screen shot 2016-11-15 at 4 09 57 am" src="https://cloud.githubusercontent.com/assets/674727/20305232/68cff19a-aae9-11e6-9356-035882f8399e.png">

**Comment by dmarcos** [comment]
Love those embedded scenes in the docs :)
