### ISSUE TITLE
Problems copying out html for individuals entities and entire scene

### ISSUE THREAD

**Issue by facultymatt** [aframevr/aframe-inspector#401]
There are a number of inconsistent behaviors my students and I are encountering when trying to use the inspector to edit scenes, some are listed below. I can provide some more details / screen grabs / etc.  

- When copying the entire scene html (the top left button)
  - There is a google analytics script included 
  - The inspector js file is included as a script tag AND as a property on a-scene. 
  - There is sometimes a `<canvas>` element at the bottom. What happens is that next time you open the inspector you can't zoom, scroll, pan the scene. 
  - Newly added elements appear and have the right `color`, but the `position`, `scale`, and `rotation` are missing. 

- When copying individual elements (top right button) 
  - Many of the changes are not always reflected in the copied html 
  - If color is already defined on the element via the `color` property, and you change the color in the inspector, the copied html has the updated color in the `material` property, but this gets overridden by the `color` property.

**Comment by hedgerh** [comment]
I'm also having these issues.  Surprised no one has responded to this.  I'm not sure how complex the issues are, but I'm willing to take a look into it.

**Comment by fernandojsg** [comment]
@facultymatt @hedgerh I've just deployed a new version that should have fixed the issues when copying individuals elements and common components on the entire scene (`position, scale, rotation`). Could you give it a try and let us know if it's working correctly for you? 

Still working on removing the other stuff injected on the scene.

**Comment by fernandojsg** [comment]
I've just deployed a new version fixing the list of issues you commented on the entire html scene https://github.com/aframevr/aframe-inspector/pull/482
Please review and let us know if you have any problem left!
