### ISSUE TITLE
Broken styles

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe-inspector#402]
Working on preparing slides for a meetup. I found the latest Inspector has broken styles. The CSS canvas is not covering the height and width.

I also find clicking objects doesn't work well. I often click on an object, and nothing responds, and I have to fidget with the camera to get it to be selected. (last working at 07550209aee1441f102b4dece6d7464e1867b66f)

![1](https://cloud.githubusercontent.com/assets/674727/20672230/5b0be3f6-b535-11e6-8b38-42d8d9e952d0.PNG)

**Comment by fernandojsg** [comment]
I've found the same issue on some windows machines, it seems to be related to https://github.com/aframevr/aframe-inspector/blob/master/src/css/main.css#L777
I believe we should use `zoom: 1` instead. Could you give it a try in your slides?

**Comment by ngokevin** [comment]
Yeah, we found this a while back https://github.com/aframevr/aframe-inspector/blob/master/example/embedded-zoom.html

**Comment by ngokevin** [comment]
Nevermind, different zoom issue.

**Comment by fernandojsg** [comment]
Yes, with the `embedded-zoom` example I believed that `zoom: reset` should works, but now it doesn't seems to work on highres windows. In fact I've found that using 50% zoom on these machines shows the canvas correctly, I don't know why. I should investigate a bit more

**Comment by kfarr** [comment]
I still see this issue projects with newest aframe master, for example here: 
![screenshot 12](https://cloud.githubusercontent.com/assets/470477/21704480/9da5b8b6-d36e-11e6-87cc-0762decf2785.png)

**Comment by fernandojsg** [comment]
@ngokevin @kfarr could you verify if it's already working correctly with the changes in https://github.com/aframevr/aframe-inspector/pull/421 ?

**Comment by kfarr** [comment]
I am still seeing the attached, this is using A-Frame Version: 0.4.0 (Date 09-02-2017, Commit #27713c2) on this url http://aframe-city-firebase.surge.sh/nofirebase.html
![screenshot 45](https://cloud.githubusercontent.com/assets/470477/22773905/70a970cc-ee59-11e6-9f5b-1ea7a99ab571.png) on firefox nightly and chrome (mainstream release)

**Comment by kfarr** [comment]
![screenshot 8](https://cloud.githubusercontent.com/assets/470477/23294419/3b045e82-fa20-11e6-8e9e-443e678e7c51.png)
Chromium latest webvr build (Feb 17) working!

A-Frame Version: 0.5.0 (Date 19-02-2017, Commit #7c011bd)
