### ISSUE TITLE
Gimbal mode not always changable via hotkey

### ISSUE THREAD

**Issue by jsantell** [aframevr/aframe-inspector#406]
When I hit the hot keys (W, E, R) to change the position, rotation or scale in the viewport, even though the gimbal is visible, the mode does not change. For example, select an entity to display the gimbal -- when it first appears upon a new selection, the hotkeys do not work. Selecting the components view for focus enables the functionality. When selecting an entity, and there's no previous entity selected, focus appears in the "Add Component..." filter, causing hotkeys to be entered as a component filter.

**Comment by jsantell** [comment]
The inspector decides on whether or not a shortcut should be triggered based off of `AFRAME.utils.shouldCaptureKeyEvent`, which checks that the meta key is not pressed and that the current document has focus. I think a potential improvement for this would be canceling events from hitting the window if they're not applicable (such as when the AddComponent filter has focus), so individual components can swallow events if they process them

**Comment by fernandojsg** [comment]
I agree with the `Add Component...`, sorry it was my fault O:) When I first included the new `add component` widget my main use case was creating new entities and adding components to them so it was quite easy that way, but it's true that it's quite annoying that it takes constantly the focus.
I believe it's better to disable the autofocus and just add maybe add a shortcut to focus the `Add component` select.
