### ISSUE TITLE
Change treatment of Common › Type: A-ENTITY → `<a-entity>`

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-inspector#41]
![image](https://cloud.githubusercontent.com/assets/203725/16507910/96791716-3ee2-11e6-9f98-46291e7b1710.png)

can we `tagName.toLowerCase()`?

**Comment by cvan** [comment]
maybe even put brackets around it so it's more clear? idk…

`<a-entity>`:

![image](https://cloud.githubusercontent.com/assets/203725/16508699/8fca4356-3eea-11e6-9618-c3e5e1ffb6f1.png)

**Comment by fernandojsg** [comment]
Done as discussed in #26 too

**Comment by cvan** [comment]
Can you make this monospaced per the mock?

**Comment by fernandojsg** [comment]
@cvan do you mean using `monospace` font?

**Comment by cvan** [comment]
> @cvan do you mean using `monospace` font?

yep. I opened PR #134.
