### ISSUE TITLE
Inconsistent core entity attribute ordering

### ISSUE THREAD

**Issue by jsantell** [aframevr/aframe-inspector#411]
Possibly related to #303, but the ordering for core entity properties (position, rotation, scale, etc.) are inconsistenly ordered, I think by left-to-right assignment in the element. When manually editing values between several entities, I frequently edit the wrong field (expecting the ordering to be position, rotation, scale)

![ordering](https://cloud.githubusercontent.com/assets/641267/21513779/9f254476-cc71-11e6-8e0c-331be9d857c6.gif)

**Comment by fernandojsg** [comment]
Do you mean that depending on the entity that you select the order is different?

**Comment by jsantell** [comment]
Yes, sorry; the gif above is toggling between two different entities

**Comment by fernandojsg** [comment]
@jsantell I fixed it, I forgot to sort the common components as we do with the rest of the components :angel: good catch!

**Comment by jsantell** [comment]
@fernandojsg thanks!
