### ISSUE TITLE
a-scene should not have the clone icon 

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe-inspector#414]
![clone scene](https://d3vv6lp55qjaqc.cloudfront.net/items/3s2W0t0L073K1j2W103g/Image%202017-01-04%20at%205.53.41%20PM.png?X-CloudApp-Visitor-Id=87464590404ee1db809f53b3bb358032&v=698c85eb)

**Comment by fernandojsg** [comment]
Closed by https://github.com/aframevr/aframe-inspector/commit/a96923ccec3483b0fe13e7ee6a497ea90c233fb7
