### ISSUE TITLE
Display of properties (position, scale, etc.) limited to 2 decimal places, would be nice to be 3 or user specified

### ISSUE THREAD

**Issue by kfarr** [aframevr/aframe-inspector#416]
A lot of the objects i'm working on have scales that are <0.01 and it makes adjusting them in the inspector very difficult.

**Comment by ngokevin** [comment]
An idea would be dragging horizontal would adjust the value, and dragging vertically would adjust the scale of the horizontal adjustment.

**Comment by dmarcos** [comment]
We could add `precision` to the schemas to specify the number of decimal points. e.g: `near: {default: 0.005, min: 0, precision: 3}`

**Comment by fernandojsg** [comment]
I've already changed from 2 to 3 decimals, but I agree that we could define a custom value, does it makes sense to have in the schema? being a attribute used just by the inspector? /cc @dmarcos @ngokevin

**Comment by fernandojsg** [comment]
Closing it, as we're already using 3 by default and I don't think we should add `precision` to the schema until we'll have a way to define the actual look of the attribute in the inspector, probably something like a custom schema just for the inspector.
