### ISSUE TITLE
Component panel parameter values not updating to scene graph

### ISSUE THREAD

**Issue by miquael** [aframevr/aframe-inspector#423]
When entering in a entity ID on right-side panel, it does not update the entity name in SceneGraph.  It appears this used to work in 0.3.2 but is now broke in 0.4.0

**Comment by miquael** [comment]
Also in inspector 0.4.0, after adding a new entity to the scene, and then (say for example) adding an obj model to it--when copying the entity code from the component panel, i get something like this:

`<a-entity scale="" material="normalScale:{&quot;x&quot;:1,&quot;y&quot;:1}" obj-model="obj:/images/model/Stanford_Lucy_Angel.obj"></a-entity>`

But then if exporting the entire scene as an HTML file (export option from the Scene Graph), the reference to that entity is included in the scene file, but is missing property values, like this:

`<a-entity position="" rotation="" scale="" visible="" material="" obj-model=""></a-entity>`

**Comment by miquael** [comment]
Seems there may be an underlying issue with how the right-side component panel is / is not updating property values to the scene?

**Comment by fernandojsg** [comment]
Hi @miquael the ID sync bug is already fixed on master,
Regarding the second comment, we're working on it, please keep an eye on the updates on this issue https://github.com/aframevr/aframe-inspector/issues/409
