### ISSUE TITLE
Add a "open in a new tab" button on texture modal

### ISSUE THREAD

**Issue by fernandojsg** [aframevr/aframe-inspector#428]
Add the button on every texture

**Comment by feiss** [comment]
also, a "remove" button is necessary, to remove them from <a-assets>. A check would be necessary to see if it is referenced anywhere, and ask user confirmation:

_This texture is being used entity xx. Do you want to remove it?"_

**Comment by feiss** [comment]
mockups:
![image](https://cloud.githubusercontent.com/assets/359872/22687387/193353a8-ed28-11e6-82d9-a928307eada6.png)
![image](https://cloud.githubusercontent.com/assets/359872/22687414/34f17b56-ed28-11e6-86b4-12a99bc399fb.png)

**Comment by fernandojsg** [comment]
I like the first design. Probably with a more subtle background for the icon or even just with the icon in white and without background, just a soft shadow. The second one is hard to notice

**Comment by feiss** [comment]
think that we will add another button for "delete", and it would probably be an X icon in the same corner.

Maybe a good option is to add a toolbar on top of each texture that is shown on hover, and that will have both buttons, and will be good enough for adding additional buttons

**Comment by fernandojsg** [comment]
My proposal, less distracting?
![image](https://cloud.githubusercontent.com/assets/782511/22740333/97d7f7e4-ee0f-11e6-973a-370eee9b342f.png)
