### ISSUE TITLE
saveSceneToHTML() exports with an inactive camera, making an empty looking scene

### ISSUE THREAD

**Issue by Utopiah** [aframevr/aframe-inspector#433]
It's possible to fix it starting and closing the inspector or making the camera active `document.getElementById('camera').setAttribute("camera", "active:true")` but it would be more natural to change the camera to active on export (either on `saveSceneToHTML()` or even `generateHtml()`.

**Comment by fernandojsg** [comment]
@Utopiah that should be fixed with the latest changes, do you mind giving it a try?

**Comment by Utopiah** [comment]
Tried using `master` and it works, namely the scene is visible but it's not using the existing camera as it is still marked `active:false` thus injects a new camera. Not sure if that's the intended behavior.

**Comment by fernandojsg** [comment]
Ah ok I see. I was just deleting the default camera injected by the editor, but you're right that I need to remove the `active:false` on the default camera.

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe-inspector/issues/517#issuecomment-445454902
