### ISSUE TITLE
The inspector button get stuck on "Loading inspector" when used with 0.5.0

### ISSUE THREAD

**Issue by brodavi** [aframevr/aframe-inspector#446]
Hitting Ctrl-Alt-i to open the inspector opens the inspector successfully but the "back to scene" button never appears. It remains at "Loading inspector" and does not change.

http://codepen.io/anon/pen/EZOGad?editors=1000

**Comment by kfarr** [comment]
I am seeing the same thing, for me the inspector screen is all white and the scene disappears until I press esc or ctl-alt-i again

I also see this on console:
`inspector.js:60 Uncaught DOMException:
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. at NewComponent.hideLoader (https://rawgit.com/aframevr/aframe/master/dist/aframe-master.js:68561:13)
    at HTMLScriptElement.script.onload (https://rawgit.com/aframevr/aframe/master/dist/aframe-master.js:68586:12)`

**Comment by fernandojsg** [comment]
I've just created a PR that I believe it should fix it https://github.com/aframevr/aframe/pull/2380
Thanks for reporting!
