### ISSUE TITLE
Inspector handles fire "componentchanged" event for their respective property on mouseover, even when inspector is closed

### ISSUE THREAD

**Issue by brodavi** [aframevr/aframe-inspector#447]
To reproduce:

1) View [http://codepen.io/anon/pen/VPqpjo](http://codepen.io/anon/pen/VPqpjo) and open the browser's console (logs don't fit in codepen console)
2) Hit `ctrl-alt-i`  to activate the inspector
3) Select the cylinder from the object list on the left, notice the handles appear for the cylinder (defaulted to position handles)
4) Mouseover the handles and notice the console log report that the `componentchanged` fires on mouseover
5) Remember where on the screen the handles are
![handles1](https://cloud.githubusercontent.com/assets/1271493/22863779/fed10e50-f10b-11e6-9a93-24d5e14e2733.png)
6) Close the inspector by hitting the "Back to Scene" button
7) Find the place on the screen where the handles *were*, as if the inspector were still up.
![handles2](https://cloud.githubusercontent.com/assets/1271493/22863785/0a2564a4-f10c-11e6-9950-3b8e122bb980.png)
8) Mouseover that area, and notice the console log reporting that the `componentchanged` fires on mouseover

**Comment by fernandojsg** [comment]
@brodavi thanks for reporting it with the nice steps to reproduce, really appreciate it! 
I believe it's fixed by https://github.com/aframevr/aframe-inspector/pull/449, still not deployed yet though
