### ISSUE TITLE
Inspector has "Export to HTML", would be nice to have an "Import from HTML"

### ISSUE THREAD

**Issue by brodavi** [aframevr/aframe-inspector#448]
Inspector has "Export to HTML", would be nice to have an "Import from HTML".

Not much else to say :)

**Comment by fernandojsg** [comment]
I believe the best workflow would be to open the HTML scene that you want and inject the inspector there, instead of importing on an already existing scene.
Completely remove one scene to replace for another one is not something we've considered to do it yet.
