### ISSUE TITLE
consider not showing camera helpers when not selected, or make the helpers less prominent

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe-inspector#45]
<img width="716" alt="screen shot 2016-06-30 at 5 50 07 pm" src="https://cloud.githubusercontent.com/assets/674727/16508749/18464d2e-3eeb-11e6-8413-bda5e789a186.png">

The camera lines are persistent and extend across the scene so there's some noise

**Comment by fernandojsg** [comment]
Good point. Probably change the geometry of the camera itself to show an actual camera or headset like vizor does, and just show the frustum when the camera is selected.

**Comment by dmarcos** [comment]
Unity uses a camera icon:

![unity camera](http://www.turiyaware.com/blog/wp-content/uploads/UnityCamera.jpg)

**Comment by ngokevin** [comment]
no longer showing helpers unless camera is selected
