### ISSUE TITLE
Display problem with gltf mesh

### ISSUE THREAD

**Issue by dVurpillot** [aframevr/aframe-inspector#454]
Hello,

I was wondering if I was the only one having trouble displaying glTF mesh inside the inspector viewport.
I tried with a few models and it happened each time: the bounding box appears to be "ok" but the mesh itself is "stuck" in the background.

[example](http://tof.canardpc.com/view/d298339e-b768-4c27-ad6a-8439a4a964cd.jpg)

Best,

**Comment by fernandojsg** [comment]
Hi @nazga could you post a codepen or similar with the scene in the example and the assets that you use?

**Comment by dVurpillot** [comment]
It really is a basic scene as you can see: [https://codepen.io/nazg/pen/KaQYrv](https://codepen.io/nazg/pen/KaQYrv)

I was only testing gltf implementation. I tried to use 0.3.0, 0.4.0 and 0.5.0, but error persisted.
As  for the model, you can grab it [here](https://expirebox.com/download/ecbc250540bb4b4ac220c7971ff13d75.html)

**Comment by feiss** [comment]
@nazga could you upload the model anywhere else? that link expired.

But very probably is a problem with shaders. When you export the gltf with shaders in the materials, they are not rendered correctly. Is a known issue in Threejs

I recommend you to use standard materials, exporting the asset to collada and then using `collada2gltf -f file.dae -k`. The `-k` parameter forces to use standard materials instead of shaders (and I can see in your screenshot that you are not using very complex materials nor need any shaders)

**Comment by dVurpillot** [comment]
Sorry for the delay: [gltf mesh](https://mega.nz/#!UNImjISL!Q_G__1N0kLvo7HfNvsx-Gs6yLyTHgGhR197jEf9zeBQ) and the [regular mesh](https://mega.nz/#!kZoRFQpQ!bFPN6icbrOBOlVF4sxOfpFmIpxIhQqhhUU06RaYfp3g).

I'm using the `obj2gltf` converter right now, I will give a try to your suggestion if it can fix the problem.

**Comment by donmccurdy** [comment]
@nazga I can confirm the problem is shaders in the model. Currently `obj2gltf` does not have an option to use standard materials instead of custom shaders. If you can convert to DAE, then DAE->glTF should work with the `-k` option. Otherwise, the issue has been fixed in the next version of three.js (whenever that is released and then lands in A-Frame).

**Comment by dVurpillot** [comment]
Thank you, I was again struggling with this issue yesterday.

For some reason, going from .obj -> .dae ->  .gltf through the collada2gltf never works correctly for me.

I always get a faulty gltf file (binary or not) that does not work/load with the three.js gltf viewer I am using to check my meshes.

I will just use another format and wait for it to work with  obj2gltf.
By the way, does Aframe handle quantized and oct-encoded glTF ?

**Comment by fernandojsg** [comment]
@feiss @donmccurdy @nazga so can we close this right?

**Comment by feiss** [comment]
@fernandojsg I think so, although nazga has more questions (and I don't know the answer, maybe @donmccurdy does)

@nazga did you tried opening the obj in blender, exporting to collada and then collada2gltf?
btw, the model looks too big for a vr experience, it is 200 meters long..

**Comment by dVurpillot** [comment]
Yes, I suggest we close this issue:
- For the moment, the only workaround would be the [collada2gltf](https://github.com/KhronosGroup/COLLADA2GLTF) option.
The obj to collada problem would be on my side. Also, you can't use the -k argument in [colladaobj2gltf online converter](http://cesiumjs.org/convertmodel.html) (but my problem was with desktop binaries anyway).
- The issue will be fixed soon as @donmccurdy said.

@fernandojsg @feiss I will open another thread elsewhere about quantized and oct-encoded glTF, since it's another topic.

**Comment by fernandojsg** [comment]
@nazga thanks! ;)

**Comment by donmccurdy** [comment]
Filed a request for obj2gltf to support KHR_materials_common extension here: https://github.com/AnalyticalGraphicsInc/obj2gltf/issues/52

Re: earlier questions —

- Quantized attributes: No, THREE.GLTFLoader does not yet support the WEB3D_quantized_attributes extension. If you have an example asset, I'd suggest filing an issue on the three.js repo and we'll see if that can be done for THREE.GLTF2Loader, but I don't think we're planning to add any features to THREE.GLTFLoader now.
- Oct-encoding: I'm not sure; maybe? You'd probably need to test this and let me know. :)

Also, the glTF 2.0 spec is going to be finalized soon. The tooling isn't really merged yet, but there's an experimental [`gltf2-model-next` component in A-Frame extras](https://github.com/donmccurdy/aframe-extras/commit/68eac470b532f588733e480968ce4b7dae3e7d51). That will automatically pull the latest version of THREE.GLTF2Loader from the three.js/dev branch.
