### ISSUE TITLE
A-Frame Inspector injects HTML character references into JavaScript code

### ISSUE THREAD

**Issue by crcdng** [aframevr/aframe-inspector#456]
To replicate: 

Open an A-Frame scene that contains a `<script>`, e.g [https://gist.github.com/i3games/ea009e190e5bf80c0a7ea7994f1f136f](https://gist.github.com/i3games/ea009e190e5bf80c0a7ea7994f1f136f) 

Activate the Inspector. Copy the scene to clipboard or export as HTML. The Inspector injects HTML character references into the JavaScript. Here, the result is  [https://gist.github.com/i3games/3787e7e40e5c7be98bec0a8f911edc2f](https://gist.github.com/i3games/3787e7e40e5c7be98bec0a8f911edc2f)

` for (i = 0; i < 10: i++) {`
is transformed into: 
  `for (i = 0; i &lt; 10: i++) {` 

A-Frame 0.5.0

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe-inspector/issues/517#issuecomment-445454902
