### ISSUE TITLE
Inspector canvas size not full in reveal.js/presentation context

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe-inspector#457]
This has regressed from v0.3.x where it previously worked. I don't have a hosted version of a presentation with A-Frame v0.5.0 yet, let me know if you need.

<img width="1432" alt="screen shot 2017-03-02 at 2 23 11 pm" src="https://cloud.githubusercontent.com/assets/674727/23529798/d3767abe-ff53-11e6-876c-29e9df0fcd7e.png">

**Comment by fernandojsg** [comment]
Fixed on the latest version
![ladyada](https://user-images.githubusercontent.com/782511/27074201-b67cf130-5026-11e7-8078-e17823f68f51.gif)
