### ISSUE TITLE
Cursor donut should be hidden?

### ISSUE THREAD

**Issue by caseyyee** [aframevr/aframe-inspector#46]
![image](https://cloud.githubusercontent.com/assets/1560884/16508740/04a5aa58-3eeb-11e6-82eb-7b25b0be0270.png)

Not sure if this is expected?   Or if you should be able to edit the cursor as part of the controls?

**Comment by ngokevin** [comment]
I think it's expected. Cursor isn't anything special, it's just a mesh + raycaster in front of the camera. I don't think it's important enough to warrant special treatment, and lets the editor remain a bit agnostic.

**Comment by fernandojsg** [comment]
Yes, it's expected, actually you could edit it and change the material or geometry as you want just like any other entity added to your scene.
