### ISSUE TITLE
I cannot input the number 2 in the string component properties using the component panel

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe-inspector#460]
The key `2` is used as a shortcut to close the component panel. If I click on a string property like `mergeTo` in geometry or `color` in material and type the number 2 the component panel is closed instead of modifying the corresponding input field

**Comment by fernandojsg** [comment]
Duplicated: https://github.com/aframevr/aframe-inspector/issues/458
I just forgot to deploy it O:)
