### ISSUE TITLE
Editing one transform accidentally rewrites other transforms

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-inspector#47]
1. Create an `<a-entity>`
2. Set `position` to `2.00  2.00  2.00`.
3. Set `rotation` to `0.01  0.00  0.00`.
4. Notice `position` has changed to `2.00  2.00  0.00` and `rotation` to `0.0  0.00  0.00`.

I noticed a ton of weirdness such as with this. And now when I did it again, the rotation Z value became `0.02`. Weird!

![image](https://cloud.githubusercontent.com/assets/203725/16508774/424aede6-3eeb-11e6-9bcd-19605f8bbedf.png)

**Comment by fernandojsg** [comment]
Fixed in https://github.com/aframevr/aframe-editor/pull/95
