### ISSUE TITLE
TextureWidget crashes when there are cached video textures

### ISSUE THREAD

**Issue by the-reality-engineer** [aframevr/aframe-inspector#471]
`getTextureFromSrc` from the TextureWidget assumes that each textureCache hash is simply JSON string, which is not always the case. See:
https://github.com/aframevr/aframe/blob/6a236273bfd6bd673e36ff4d376135906ba57ed6/src/systems/material.js#L207

When trying to JSON.parse() a textureCache hash that is generated from a video texture, the TextureWidget throws an "Unexpected token a in JSON" error.

**Comment by vincentfretin** [comment]
This has been fixed by #680

**Comment by vincentfretin** [comment]
@dmarcos please close this issue.
