### ISSUE TITLE
Add all data attributes and classes to details from a node

### ISSUE THREAD

**Issue by HeinPauwelyn** [aframevr/aframe-inspector#473]
I'm making a project and I've added some `data`-attributes to the `a`-nodes. Example of my data below:

```html
<a-scene>
    <a-sky src="myimage.png"></a-sky>
    <a-entity id="variables">
        <a-entity class="clickable" data-to="1"></a-entity>
        <a-entity class="clickable" data-to="0"></a-entity>
        <a-entity class="clickable" data-info="19"></a-entity>
        <a-entity class="clickable" data-info="01"></a-entity>
        <a-entity class="clickable" data-info="27"></a-entity>
        <a-entity class="clickable" data-info="20"></a-entity>
    </a-entity>
</a-scene>
```

Each node with class `clickable` got also an image but I've removed this from the snippet to improve readability. This nodes got also a `rotation`, `position` and `scale` attribute.

To make my work a bit faster, I'll like to see the data and the classes of each node inside the visual inspector.

![image](https://cloud.githubusercontent.com/assets/16222780/26104501/6b0cf112-3a3e-11e7-956b-1223bb9087c1.png)

**Comment by fernandojsg** [comment]
I think this is currently out of the scope of the editor as it's something very specific to your use case. It would be hard to differentiate between which attributes you want to be available or not and define the data type and so on.
Probably you could try to create a module for this specific behaviour and just activate on the scenes you want to use it.
