### ISSUE TITLE
Not exporting updated entities correctly

### ISSUE THREAD

**Issue by deniswvieira** [aframevr/aframe-inspector#474]
Hello,

When I open the inspector and edit the existing entities properties (as Position), the Copy Scene to Clipboard or Export to HTML are not working as expected. The generated HTML is the original HTML and not the new one corresponding to the changes I made.

My test scene:
```
<!DOCTYPE html>
<html>
  <head>
    <title>Hello, WebVR! - A-Frame</title>
    <meta name="description" content="Hello, WebVR! - A-Frame">
    <script src="https://aframe.io/releases/0.5.0/aframe.min.js"></script>
  </head>
  <body>
    <a-scene>
      <a-box position="-1 0.5 -3" rotation="0 45 0" color="#4CC3D9"></a-box>
      <a-sphere position="0 1.25 -5" radius="1.25" color="#EF2D5E"></a-sphere>
      <a-cylinder position="1 0.75 -3" radius="0.5" height="1.5" color="#FFC65D"></a-cylinder>
      <a-plane position="0 0 -4" rotation="-90 0 0" width="4" height="4" color="#7BC8A4"></a-plane>
      <a-sky color="#ECECEC"></a-sky>
    </a-scene>
  </body>
</html>
```

To reproduce: Open the inspector, modify Entity's position, click on  Copy Scene to Clipboard or Export to HTML and verify that the generated HTML does not correspond to new Position you have setted.

Best regards,
Denis Vieira

**Comment by fernandojsg** [comment]
This should be fixed with https://github.com/aframevr/aframe-inspector/pull/455 and https://github.com/aframevr/aframe-inspector/pull/478
