### ISSUE TITLE
INSPECTOR BROKEN - 'asset' type schema property objects being re-parsed as URLs

### ISSUE THREAD

**Issue by NNskelly** [aframevr/aframe-inspector#476]
re-filed from https://github.com/aframevr/aframe/issues/2662

**Description:**
The latest a-frame inspector min.js as retrieved from unpkg.com e.g. by the A-Painter demo is throwing errors whenever an entity is selected which has a material component with a src or other map (or asset?) property. The error manifests as a "e.match is not a function" js error in an obscurely nested minified block in which e appears to be the actual parsed asset object, and the function appears to be attempting to re-parse it as a URL or asset ID, e.g. comparing "#"===e[0] and then looking it up as a # id if true, or attempting to parse it as a URL (using string .match) if false.

As a side-effect, many inspector fields for map/asset properties now show as empty boxes with [object] as the source, rather than as previews with the corresponding asset #id as the source.

Edit: in fact, upon further experiments with debugging off, the errors derail the whole Inspector and Scene refresh flow to the point where any material updates in the inspector become impossible. Definitely a priority bug, I would think.

-     A-Frame Version: aframe-inspector@0.5.2
-     Platform / Device: Windows Chrome
-     Reproducible Code Snippet or URL: https://aframe.io/examples/showcase/a-painter/

a variety of other issues, likely related, also show up, some suggesting a corrupted/misfiled canvas context, others that sound like somewhere that is expecting a valid parsed object are instead getting some earlier state e.g. a raw string, although I am having difficulty isolating deterministic repro steps. Clicking between entities with different types of shader, or with and without materials, seems to re-trigger most types of error, somewhat arbitrarily.

![match_not_a_function](https://cloud.githubusercontent.com/assets/28572171/26220845/f22ad9f6-3bd9-11e7-8816-e053701f6f72.png)
![callstack](https://cloud.githubusercontent.com/assets/28572171/26220851/f5e44ea6-3bd9-11e7-819d-b9ab53ba172b.png)

A locally-linked (e.g. inspector="url: scripts/aframe-inspector.min.js" in the scene tag) inspector latest-zip-downloaded from the inspector github does not, at least initially, appear to be exhibiting this issue, so it may be tangled up in how the latest-version auto-URL is being resolved. However, latest listed release does appear to be 0.5.2, which looks like what is being remotely loaded, so... no explanation as of yet :-P

Edit 2: locally-sourced 0.5.2 just threw the match error. crisis not averted.

**Comment by fernandojsg** [comment]
@NNskelly could you give it a try with the latest deployed version 0.5.3?

**Comment by NNskelly** [comment]
@fernandojsg Current live A-Painter https://aframe.io/examples/showcase/a-painter/ looks like it is now loading 0.5.3 inspector; error still occurs.
![0_5_3_match](https://cloud.githubusercontent.com/assets/28572171/26802299/a97c1924-4a05-11e7-9634-323f8b602c91.png)

popped open the inspector, occurred right away when I clicked the <a-entity ground>.

e in this case looks like it is an HTMLImageElement img#floor

**Comment by fernandojsg** [comment]
I think I found it thanks: https://github.com/aframevr/aframe-inspector/pull/481
