### ISSUE TITLE
Does not apply transforms to values typed in

### ISSUE THREAD

**Issue by caseyyee** [aframevr/aframe-inspector#48]
When entering transform values by typing (using numeric keys), the entity does not take on these changes.

Seems to work fine when you click and drag the numbers.

**Comment by caseyyee** [comment]
Also worth noting that numerical values typed into components work fine (ie. adjusting radius of cylinder)

**Comment by cvan** [comment]
In which browser?

**Comment by caseyyee** [comment]
Chrome

**Comment by ngokevin** [comment]
I found it only works on the second try.
