### ISSUE TITLE
Inspector fails to load from a glitch sample

### ISSUE THREAD

**Issue by irwinwilliams** [aframevr/aframe-inspector#491]
I'm in a glitch sample, when I press ctrl + alt + i, the chrome console shows this: 
```
aframe-inspector.min.js:30 Uncaught TypeError: Cannot read property 'hasLoaded' of null
    at onDomLoaded (aframe-inspector.min.js:30)
```
Is something missing?

**Comment by kfarr** [comment]
Hi irwinwilliams I can load the inspector okay using the "hello world" glitch project. do you have a link to your glitch project to reproduce this error?

**Comment by ngokevin** [comment]
If provide link to Glitch I can check it out, else I think it works normally.
