### ISSUE TITLE
The inspector fails is inconsistent regarding copying a primitive with a modified attribute

### ISSUE THREAD

**Issue by delapuente** [aframevr/aframe-inspector#492]
For consistency, the inspector should serialise primitives giving priority to mapped attributes.

STR:
 1. Open the example scene
 2. Select the `<a-sky>` tag
 3. Set the radius property to 4 (`geometry` component)
 4. Click on copy

Expected:
```html
<a-sky color="#3c3c3c" radius="4"></a-sky>
```

Actual:
```html
<a-sky color="#3c3c3c" geometry="radius: 4"></a-sky>
```

**Comment by ngokevin** [comment]
the ECS syntax is the true syntax, the primitive stuff is just extra/helper, so maintaining the component property syntax is consistent
