### ISSUE TITLE
Error loading registry file for A-Frame 0.6.0

### ISSUE THREAD

**Issue by UXVirtual** [aframevr/aframe-inspector#495]
I'm getting the following console error when using the current release version of A-Frame (v0.6.0) when trying to load the inspector:

```
Error loading registry file: 404
t.onload @ aframe-inspector.min.js:31
```

The file in question is trying to load from: https://aframe.io/aframe-registry/build/0.6.0.json

**Comment by fernandojsg** [comment]
I've moved it to the aframe-registry repo. thanks for reporting!

**Comment by fernandojsg** [comment]
Well, I'll keep it open until the deploy will be done

**Comment by fernandojsg** [comment]
Done!, @HAZARDU5 please give it a try

**Comment by UXVirtual** [comment]
Looks good - thanks!
