### ISSUE TITLE
Deleting the entire `<a-scene>` does not reflect in the scene graph

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-inspector#51]
1. Load http://dev.fernandojsg.com/aframe-editor/example/
2. Select `<a-scene>` from the scene graph.
3. Press the trash can at the bottom to delete the entity.
4. Notice everything just goes blank but the entities in the scene graph seem to remain. But if I export/download the scene, I notice indeed `<a-scene>` is gone.

![image](https://cloud.githubusercontent.com/assets/203725/16508876/358e15d2-3eec-11e6-8702-5ba6b69aa8d6.png)
![image](https://cloud.githubusercontent.com/assets/203725/16508867/2404845e-3eec-11e6-9d4c-90c2196d11cf.png)

**Comment by fernandojsg** [comment]
I believe maybe it doesn't makes sense to let the user delete the `a-scene` maybe just clear it? So you'll have an empty scene?

**Comment by cvan** [comment]
> I believe maybe it doesn't makes sense to let the user delete the `a-scene` maybe just clear it? So you'll have an empty scene?

What happens when you try to edit a page with multiple scenes? We should probably make sure that the scene's canvas is focused when entering Editor mode.

Personally, I do think the user should be able to delete the `a-scene`; I can't see how it hurts.
