### ISSUE TITLE
404 https://aframe.io/aframe-registry/build/0.7.0.json

### ISSUE THREAD

**Issue by 7dir** [aframevr/aframe-inspector#521]

**Comment by dmarcos** [comment]
I don't understand this issue. It should probably be filed against the inspector repo: https://github.com/aframevr/aframe-registry

**Comment by dmarcos** [comment]
Oh I see I guess it is when loading the json from the inspector.

**Comment by 7dir** [comment]
Your guess is right!

console browser

**Comment by jafetmorales** [comment]
Any luck with this issue?

**Comment by XT3RM1N8R** [comment]
This is happening for me as well.

**Comment by micsun-al** [comment]
This reproduces for me.
MacOS 10.13.3 High Sierra
Chrome 64.0.3282.167
Firefox Quantum 58.0.2 (64 bit)
Safari 11.0.3
iMac (Retina 5K, 27-inch, Late 2014)
Processor: 4 GHz Intel Core i7
Memory: 32 GB 1600 MHz DDR3
Graphics: AMD Radeon R9 M290X 2 GB

**Comment by banada** [comment]
This happens for me as well on:
Windows
    Chrome 64.0.3282.167
    Firefox 58.0.2
Ubuntu 14.04
   Firefox 58.0.1

I suppose hosting the inspector files ourselves would prevent this issue.

**Comment by ngokevin** [comment]
This is a benign error. The solution is to remove the Registry from the Inspector.

**Comment by fernandojsg** [comment]
Closed by https://github.com/aframevr/aframe-registry/issues/78
