### ISSUE TITLE
Material not honoring the color when changing material flags

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe-inspector#522]
Try to select a color and disable / enable `depthTest`. The material color is set to the default back again.
![image](https://d3vv6lp55qjaqc.cloudfront.net/items/170E2q1W1t2K421D3602/Screen%20Recording%202017-10-09%20at%2003.12.48%20AM.gif?X-CloudApp-Visitor-Id=cfbaf47066750ce499088aa3bda2084c&v=b5284396)

**Comment by vincentfretin** [comment]
I don't reproduce with latest version. You can close.
