### ISSUE TITLE
error upon opening inspector, can't invert matrix, determinant is 0. DirectionalLightHelper has scale 0 if direction has a 0

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe-inspector#524]

**Comment by ngokevin** [comment]
Fixed by doing setting `position="1 1 0.0001"` for directional light, but we should handle because that's the default directional light without a position set.

**Comment by autuus** [comment]
Fixed by turning off warnings from console (lol)

**Comment by aas395** [comment]
I also get this if I try to set any of the values of the scale property of an entity to 0 using the animation component. Setting each value to a number above 0 stops this

**Comment by Mazertula** [comment]
@ngokevin I have the same issue using animation on scale to 0. 
workaround : scale to 0.0001.

**Comment by ngokevin** [comment]
This is just a three.js thing. Don't set any scales to 0. Set to 0.00001
