### ISSUE TITLE
Exported HTML should only contain basic scene markup.

### ISSUE THREAD

**Issue by caseyyee** [aframevr/aframe-inspector#53]
When exporting using Scene -> Export HTML:
- Entire editor interface markup + CSS is also included in the markup.
- A-Frame injected CSS.

Expected it to include only the changes that the editor made to the <a-scene> portions of the code.   Should be a copy and paste operation back into your original document.

**Comment by fernandojsg** [comment]
Duplicated from https://github.com/aframevr/aframe-editor/issues/23
