### ISSUE TITLE
404 Error from Component Registry

### ISSUE THREAD

**Issue by CBernsCode** [aframevr/aframe-inspector#535]
When trying to open the inspector on my local copy or the hosted example I see a 404 error in the console. This is preventing the tool from working properly.

![image](https://user-images.githubusercontent.com/8380478/36077170-2ca77e7a-0f35-11e8-80e4-bb84d68f9314.png)

**Comment by XT3RM1N8R** [comment]
I can confirm that this also happens for me as well.

**Comment by fernandojsg** [comment]
Closed by https://github.com/aframevr/aframe-registry/issues/78
