### ISSUE TITLE
 Copy HTML to Clipboard includes relative path to aframe-master

### ISSUE THREAD

**Issue by g0dd4rd** [aframevr/aframe-inspector#536]
I believe it should include url to the aframe.min.js instead.
now: script src="../../../dist/aframe-master.js
expected: script src="https://aframe.io/releases/${version}/aframe.min.js

**Comment by naugtur** [comment]
Seems to me it's preserving the exact url there was. If you're using your own script URL that seems desired. I'd say it's correct.

**Comment by ngokevin** [comment]
removed the whole export entire scene to HTML option
