### ISSUE TITLE
Focusing on a Text component crashes the tab requiring restart.

### ISSUE THREAD

**Issue by Adam4lexander** [aframevr/aframe-inspector#538]
Caused by Box3.setFromObject() in threejs assuming that objects use 3 numbers per vertex position. The TextGeometry only uses 2 numbers per vertex position.

I'm going to take a look at this soon, I think the fix should be in THREE.Box3.

**Comment by Adam4lexander** [comment]
https://github.com/mrdoob/three.js/pull/13622

Made a pr to three to fix this.

**Comment by ngokevin** [comment]
i think i fixed by monkeypatching the box3, but new versions of three works too now
