### ISSUE TITLE
Aframe export to GLTF and Animations

### ISSUE THREAD

**Issue by siddhartpai** [aframevr/aframe-inspector#539]
Currently GLTF Export using the THREE.GLTFExporter doesn't support Tween Animations , rather only supports THREE.AnimationClip .

Are there plans to support <a-animation> export to GLTF ?

**Comment by ngokevin** [comment]
`<a-animation>` does basic tweening. You probably want https://github.com/donmccurdy/aframe-extras/tree/master/src/loaders#animation

**Comment by siddhartpai** [comment]
Hi @ngokevin I don't think I explained the question well enough. 

So I'm using the gltf-exporter to export out entire A-Frame scenes in to a gltf model, The A-Frame scene can have animations that have been added to it via a-animation tags ; which aren't exported out when the exportToGLTF is done. Is there any way I can handle that ? 

[GLTF Exporter](https://github.com/mrdoob/three.js/issues/11951)

**Comment by ngokevin** [comment]
Not really, I would use a dedicated animation tool to handle it if possible or don't know feasible to hand code.
