### ISSUE TITLE
Unable to move while inspecting scene

### ISSUE THREAD

**Issue by edoardoo** [aframevr/aframe-inspector#542]
Hi, I'm playing a bit with aframe but while inspecting a scene with `ctrl+alt+i` I'm unable to move in the scene. The mouse pointer changes to fist while clicking but the scene, or the selected object, is not moving.   
Maybe I'm just missing something stupid (some config?).

I've set up a test scene on [glitch](https://aframe-inspector-test.glitch.me/). 

**Expected behaviour:** When inspecting a scene is possible to move the object or the scene left-clicking with the mouse. 
**Obtained behaviour:** When inspecting a scene clicking on the scene makes the pointer change to fist but the scene or the object is not grabbed while moving the mouse. 
**Steps to reproduce:** Open the linked scene, press `ctrl+alt+i` and try to move objects or the scene by grabbing them and moving the mouse.

Thanks

**Comment by goopypanther** [comment]
This sounds like the bug I submitted in December: https://github.com/aframevr/aframe-inspector/issues/528

Was the html file you're editing previously exported from the inspector? Is that additional canvas tag present in it?

**Comment by edoardoo** [comment]
I'm going to check later this week. I'll keep you posted.

**Comment by edoardoo** [comment]
@JeremyRuhland I removed the canvas from the generated html and it now pans as it should. 
In any case, it was actually exported from an inspector.
Sorry for the duplicate issue and thanks for the quick fix.
