### ISSUE TITLE
Selecting an obj changes its rotation

### ISSUE THREAD

**Issue by siddisking** [aframevr/aframe-inspector#546]
Hi,

Aframe Inspector is changing the default rotation when selecting the object very first time.

If I have a plane rotation set to `<a-plane rotation="-90 0 0">` and I select it in the inspector it puts the value in radians in the right menu which rotates the plane.

However same behavior does not happen if an object is selected first with having `0 0 0` as rotation values.

I have replicated this issue at [fiddle]( https://jsfiddle.net/gecgbqrz/) .

Follow these steps to reproduce this:

Open inspector select plane first.

-Thanks

**Comment by ngokevin** [comment]
I believe fixed now.
