### ISSUE TITLE
Avoid requesting textures until needed

### ISSUE THREAD

**Issue by donmccurdy** [aframevr/aframe-inspector#548]
When opening the inspector I see a lot of immediate requests for textures:

<img width="579" alt="screen shot 2018-05-20 at 3 27 20 pm" src="https://user-images.githubusercontent.com/1848368/40340607-b9599e0a-5d34-11e8-85c2-f558a1bf63c7.png">

When debugging something on slow wifi, this is a lot of extra requests. It would be nice if the textures were only loaded when needed.

**Comment by ngokevin** [comment]
this was a travesty! i just fixed this.
