### ISSUE TITLE
Add basic telemetry

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe-inspector#55]
We can start simple. We can measure what are the most used components

**Comment by cvan** [comment]
Could borrow some https://github.com/MozVR/mozvr-site/blob/master/assets/js/ga.js#L172

**Comment by ngokevin** [comment]
Traditional analytics will be tricky since the Editor will be running on all sorts of domains, often `localhost`.

**Comment by ngokevin** [comment]
Might work...

> Automatic cookie domain configuration sets the _ga cookie on the highest level domain it can. For example, if your website address is blog.example.co.uk, analytics.js will set the cookie domain to .example.co.uk. In addition, if analytics.js detects that you're running a server locally (e.g. localhost) it automatically sets the cookieDomain to 'none'.

**Comment by ngokevin** [comment]
OK, I think it's working fine.

I'm going to keep a running list of events and metrics to track. Feel free to add more:
- [ ] attributes.componentAdd - component name
- [ ] attributes.componentChange - component name
- [ ] attributes.componentRemove - component name
- [ ] attributes.componentCopy - component name
- [ ] attributes.componentReset - component name
- [ ] attributes.componentCollapse - component name
- [ ] attributes.mixinAdd - component name
- [ ] attributes.mixinRemove - component name
- [ ] gizmos.helperSelect - helper name
- [ ] gizmos.localToggle - on or off
- [ ] gizmos.entityChange - component name (position/rotation/scale)
- [ ] scenegraph.entitySelect
- [ ] scenegraph.entitySearch
- [ ] menu.export.html
- [ ] menu.export.copy
- [ ] menu.create - entity type

Maybe:
- [ ] scene.pan
- [ ] scene.zoom
- [ ] scene.rotate
