### ISSUE TITLE
Aframe inspector: glTF export button broken/ not working as expected

### ISSUE THREAD

**Issue by Pluto8195** [aframevr/aframe-inspector#551]
Trying to export my aframe scene using this button was not initiating a download at all,

![](https://user-images.githubusercontent.com/10274697/43224302-dc8781f4-9023-11e8-8740-15c15496a7d5.png)

Instead I selected the entity and exporting that as a glTF using the button on the right and it would download

![](https://user-images.githubusercontent.com/10274697/43224369-083b71fc-9024-11e8-9289-4efa6558a90c.png)

attempting to re-display the model in aframe was causing issue and I was advised to try viewing it on

https://gltf-viewer.donmccurdy.com/
to which the response was missing texture:

    A-Frame Version: 0.8.2
    Platform / Device: OSX chrome

**Comment by donmccurdy** [comment]
Probably related: https://github.com/aframevr/aframe-inspector/issues/547

I think the inspector should be changed to export the `.glb` variant of glTF, with embedded images by default.
