### ISSUE TITLE
how to change Aframe Gizmo for Translation the style?

### ISSUE THREAD

**Issue by xuhande** [aframevr/aframe-inspector#555]
I want change aframe Gizmo for the translate and rotation style of the below images.

![screen shot 2018-08-02 at 5 30 28 pm](https://user-images.githubusercontent.com/5135442/43623121-24110924-9712-11e8-99da-0992a9c29d1f.png)

How to change TransformControls.js for https://github.com/aframevr/aframe-inspector/tree/master/src/lib/vendor/threejs.

Thank you.

**Comment by ngokevin** [comment]
hey, i don't think we're going to change the gizmos, the current ones work
