### ISSUE TITLE
Shape Component Doesn't work in Electron

### ISSUE THREAD

**Issue by Moikapy** [aframevr/aframe-inspector#558]
Original Issue:
https://github.com/donmccurdy/aframe-physics-system/issues/113#issuecomment-427977295

Building an an electron app using aframe/aframe-inspector, and ran into an issue with a few of the components using prompt and it not being accepted by electron. Was wondering if anyone would be able to help find a work around for the error.

**Comment by ngokevin** [comment]
prompt is used on purpose. inspector doesn't officially support electron use. try overriding it for your purposes (electron-prompt).
