### ISSUE TITLE
Allow copy markup of a single entity

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe-inspector#56]
Imagine I'm inspecting a scene to learn how it works. I see an entity with a combination of components that does what I need. It would be nice to be able to copy and paste it in my editor. We could add a button on a contextual menu of the entity in the 3D view or/and a button on the entity inspector on the right.

**Comment by caseyyee** [comment]
Is what your talking about copying a fragment of markup? 

I already have this issue filed which for cloning/copy pasting:
https://github.com/aframevr/aframe-editor/issues/36

**Comment by dmarcos** [comment]
Yes. this would be copying the html fragment that corresponds to the entity so you can paste it in your text editor. It's different than clone it.
