### ISSUE TITLE
Inspector cannot be started in firefox 64.0

### ISSUE THREAD

**Issue by SwiftPengu** [aframevr/aframe-inspector#563]
I am unable to launch the inspector using the ctrl+alt+i shortcut on firefox nightly (64.0).
When reverting back to 62.0 the shortcut is registered again.

Set-up
- Windows 10
- Firefox nightly browser 64.0 vs Firefox stable 62.0
- No HMD connected

**Comment by ngokevin** [comment]
Maybe a nightly issue. comment back if you have an error log
