### ISSUE TITLE
Let the user to move the editor camera with arrow keys or WASD

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe-inspector#57]

**Comment by caseyyee** [comment]
the pan and rotate using mouse seems to work OK for this purpose. 

It would be a RPG-like 3rd person perspective control?  Could be interesting.

**Comment by dmarcos** [comment]
Pan and rotate are clunky if you want center the view in an area that you want to focus on

**Comment by caseyyee** [comment]
There are issues with the implementation.   I think pan and rotate are a sound pattern to use (see sketchup).   I don't think WASD controls will help here.   It's a bandaid solution.

**Comment by caseyyee** [comment]
Trying to figure out the exact issue (so that I can file for a specific problem), but I find that the zoom or pan control will start functioning very slowly in some cases.

**Comment by caseyyee** [comment]
Issue filed for the specific issue as per above comment:
https://github.com/aframevr/aframe-editor/issues/69

**Comment by arturitu** [comment]
I think use keys to move any object (not only the camera) is a great opportunity to move is rounded number steps (for ex. 0.1m per click or if you press shift+key move 10x (in this case 1m per click)

**Comment by ngokevin** [comment]
we have entity focusing now to zoom in on an entity (double click, or hit `f`) will do for most cases for now
