### ISSUE TITLE
Weird background on component property titles

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe-inspector#573]
Background color does not cover the whole title and blends with panel background:

![image](https://d3vv6lp55qjaqc.cloudfront.net/items/2E173s142V3F2H0f1W1D/Image%202019-01-13%20at%207.21.54%20PM.png?X-CloudApp-Visitor-Id=90208aa50e60fa43d0cbdf1f441cd2cc&v=fda59841)

**Comment by ngokevin** [comment]
Can't reproduce for me (23'' 3k monitor or razer blade or macbook).

**Comment by vincentfretin** [comment]
The image is broken. Close?
