### ISSUE TITLE
Repeating CORS warning for `http://localhost:51234`

### ISSUE THREAD

**Issue by dsinni** [aframevr/aframe-inspector#574]
I'm receiving the following recurring warning when using the inspector with A-Frame `master`. It displays approximately every 5 seconds:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:51234/. (Reason: CORS request did not succeed).
```

![image](https://user-images.githubusercontent.com/4733018/51413529-466cc800-1b3d-11e9-837f-a8ddcdcf31f1.png)

I'm currently using the latest `master`: `056b2bce5d448f0c9e9e1855397ff7a40847d4c5` and am running a local web server for development but not on port `51234`, so I'm not sure why that's being used at all.

Actually, it appears that `aframe-watcher` uses `51234` for the default port, so maybe this is intended? Just thought it was worth noting just in case.

Thanks.

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe-inspector/commit/0e3b67f667df7ea21a70f2944f061ca30b1b37b8
