### ISSUE TITLE
Unable to click an object with mouse

### ISSUE THREAD

**Issue by albirrkarim** [aframevr/aframe-inspector#575]
In aframe version 0.8.2
I can't click to select an object, instead it triggers a grabbing of view

In aframe version 0.7.0
I can click to select an object to (move, scale, rotate them) like blender 3D

But why in aframe 0.8.2 and 0.8.0 ?
Maybe this is a bug ?

**Comment by ngokevin** [comment]
Can you link to your scene, I can check it out?

**Comment by albirrkarim** [comment]
https://west-actor.glitch.me/
https://glitch.com/edit/#!/west-actor?path=views/index.html:14:7

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe-inspector/commit/51e389832e911186f90e2ac9203522a28ed9eda6

**Comment by albirrkarim** [comment]
still bug in aframe 0.8.x ? how to use it ?
