### ISSUE TITLE
"Export to GLTF" buttons not working

### ISSUE THREAD

**Issue by thedart76** [aframevr/aframe-inspector#577]
Version: A-Frame Inspector 0.8.19

I cannot export the scene by clicking directly on the dedicated buttons (Export to glTF) the same way I could in v0.7.

Error in Chrome Console:
![inspector-export-gltf-chrome](https://user-images.githubusercontent.com/30973948/52226873-0714da00-28a6-11e9-9a04-55d29767da85.png)

Error in Firefox Console:
![inspector-export-gltf-firefox](https://user-images.githubusercontent.com/30973948/52226884-0b40f780-28a6-11e9-8c0d-6a1bad087cb6.png)

I can only export to glb the camera and the lights once I select them in the left panel.

I created 2 boxes in the below scene as an example (one is a primitive, one is an entity with ECS syntax), but even if I select them I still can export neither of them.

Example:
https://torpid-squid.glitch.me/

And even if exporting single entities would be possible, it wouldn't be so useful.

Ideally, it should be possible to export the whole scene when clicking on the "Export to glTF" buttons like in version 0.7.

**Comment by kfarr** [comment]
Possibly related https://github.com/fernandojsg/aframe-gltf-exporter-component/issues/5

**Comment by karx** [comment]
I am also facing this issue when attempting to export the entity I construct using [aframe-svg-extruder](https://github.com/luiguild/aframe-svg-extruder).

The version Aframe, v0.8.0
A-frame inspector v0.8.19

Link to source: https://github.com/karx/karx.github.io/tree/master/kaaro/3d-extrude
You can try exporting the object here to see the issue: [Link to repro](http://kaaro.akriya.co.in/kaaro/3d-extrude/)

**Comment by rzr** [comment]
Then what is the recommended version for exporter  ?

**Comment by kfarr** [comment]
- Export to gltf from inspector works with A-Frame Version: 1.1.0 (Date 2020-12-03, Commit #8aefd214)
- I would vote to close this issue


To reproduce success case:
- Go to https://aframe.glitch.me/
- Press ctl + alt + i to open inspector
- Press export to gltf button (gltf logo icon)
- Open https://gltf-viewer.donmccurdy.com/
- Drag exported file to gltf viewer and see it look the same (albeit with different lighting)

**Comment by joshi22amit** [comment]
> * Export to gltf from inspector works with A-Frame Version: 1.1.0 (Date 2020-12-03, Commit #8aefd214)
> * I would vote to close this issue
> 
> To reproduce success case:
> 
> * Go to https://aframe.glitch.me/
> * Press ctl + alt + i to open inspector
> * Press export to gltf button (gltf logo icon)
> * Open https://gltf-viewer.donmccurdy.com/
> * Drag exported file to gltf viewer and see it look the same (albeit with different lighting)

Thanks a lot buddy...I could export gltf with Version 1.1.0 :)

**Comment by kfarr** [comment]
@dmarcos this can be closed, fixed

**Comment by dmarcos** [comment]
Thanks!
