### ISSUE TITLE
Open inspector pragmatically from API call

### ISSUE THREAD

**Issue by LukeTOBrien** [aframevr/aframe-inspector#586]
Hello there,

I wondered is there a way to open the inspector pragmatically instead of using shortcut?  
My scenario is that I have a A-Frame scene appear inside a `<div>` window inside my app, so the scene is not full-screen and I want to place a button underneath the scene that opens up the inspector.

So code similar to this is what I have imagined:
```Javascript
document.querySelector("a-scene").openInspector();
```
```

**Comment by awesomephant** [comment]
```AFRAME.INSPECTOR.toggle()``` does the trick for me.

**Comment by SubZtep** [comment]
Hi, I always use the command below from the dev console:
```js
AFRAME.scenes[0].inspect()
```
Made quickly a [Codepen to try](https://codepen.io/SubZtep/pen/qBNmboY) and seems the same command works for embedded A-Frame without querying its root, but the inspector becomes full screen.

**Comment by LukeTOBrien** [comment]
Hi chaps,

I have only just got around to looking at this. Is there any extra JS I need to include?  
I am  using the latest (1.1.0/aframe.min.js) and do nt see an `AFRAME.INSPECTOR` object nor a `inspect()` function on the scene.

![aframe-no-inspector](https://user-images.githubusercontent.com/16164373/104070544-0f4ac200-51ff-11eb-82ab-ebf3c3cc7059.png)

**Comment by kfarr** [comment]
Try:
`  window.postMessage('INJECT_AFRAME_INSPECTOR')`

**Comment by kfarr** [comment]
Multiple solutions have been provided, can we close this issue @dmarcos  ?
