### ISSUE TITLE
Keyboard shortcut (<ctrl> + <alt> + i) is not working as expected.

### ISSUE THREAD

**Issue by dudleyhk** [aframevr/aframe-inspector#595]
Is it known that the inspector is not longer opening using the keyboard shortcut on Windows machines? I'm running Firefox 71.0... I'm sure it's not just my computer as I had it checked by someone running the Udemy course I've been following.

Cheers.

**Comment by svenkonings** [comment]
I'm running into a similar issue on Windows. I've found out it happens when my keyboard is set to US international. It works as expected when my keyboard is set to US.

**Comment by TommyBeaton** [comment]
If this doesn't fix the issue for anyone I changed the version type in the CDN to 1.0.0
`<script src="https://aframe.io/releases/1.0.4/aframe.min.js"></script>`
Note: current release at posting is 1.0.4

**Comment by davegoopot** [comment]
The inspector shortcut is not working for me here on a UK keyboard.I've tried both the latest Firefox and Chrome without any luck.  You can see the page I'm experimenting on here: https://aframe-learning.glitch.me/
How can I help debug?

**Comment by leo-nerd** [comment]
Same issue here (Aframe 1.1.0)

**Comment by vincentfretin** [comment]
I think this one was fixed with #658
You can close @dmarcos 
If it's still an issue for some of you with aframe 1.4.1, please create a new issue.

**Comment by dmarcos** [comment]
Fixed by https://github.com/aframevr/aframe-inspector/pull/658
