### ISSUE TITLE
Wrong keyboard shortcut for MacOS

### ISSUE THREAD

**Issue by mattrossman** [aframevr/aframe-inspector#600]
The documented shortcut of Ctrl+Alt+I (which could be interpreted as Ctrl+Option+I or Cmd+Option+I) does not work on MacOS, tested on Firefox and Chrome. I thought that the inspector was simply broken. [I found out on StackOverflow](https://stackoverflow.com/a/52596978) that instead, the shortcut for MacOS is **Shift+Ctrl+Option+I**.

~~I don't know if the "issue" is the shortcut implementation or lack of documentation, but either way it's mind boggling that this basic operation has not been documented for the MacOS community.~~
Editing this to be less sassy 😅

**Comment by mattrossman** [comment]
Bumping this to note that **Shift+Option+I** now seems to be sufficient, but it still needs to be documented.

**Comment by dmarcos** [comment]
PRs always appreciated https://github.com/aframevr/aframe/blob/master/docs/introduction/visual-inspector-and-dev-tools.md

**Comment by mattrossman** [comment]
@dmarcos Is there a reason for having a separate shortcut on MacOS? I notice the shortcut is mentioned in several places in the docs -- rather than mentioning the alternate shortcut every time, maybe we can fix the shortcut to be the same across platforms?

**Comment by dmarcos** [comment]
The shortcut should be the same in both platforms. The equivalent of the alt key on the mac is the option key. Shortcut should be:

- Windows: `Ctrl + Alt + i`
- Mac: `Ctrl + Option + i`

Unless the Mac shortcut is taken for something else. 

The idea of the inspector is to be the 3D equivalent of the DOM inspector that opens with `Ctrl + Shift + i`

[Logic is in A-Frame](https://github.com/aframevr/aframe/blob/master/src/components/scene/inspector.js#L62) not in the inspector repo.

**Comment by kfarr** [comment]
`ctl + option + i` has opened a-frame inspector on mac os for the last decade, @dmarcos can you close this?

**Comment by mattrossman** [comment]
I gotchu. I actually still face this issue but it's not A-Frame's fault.

> Unless the Mac shortcut is taken for something 

This was the cause for me. It seems `Ctrl + Option + i` is a shortcut used by a couple other popular Mac applications. I don't recall which app was causing the conflict originally, but there wasn't any visual feedback so it appeared to be doing nothing. More recently I experience the conflict with the default keybinds for [Rectangle](https://rectangleapp.com/), but that one is easier to notice since it causes a window snap.

Interestingly, I only need to press `Option + i` on Mac to summon the inspector. [The line Diego shared above](https://github.com/aframevr/aframe/blob/784f900d40f59fe16aad090b2efe7d502f721318/src/components/scene/inspector.js#L62) will ignore the `evt.ctrlKey` check as long as `evt.getModifierState('AltGraph')` is satisfied, which on Mac happens when `Option` is pressed [(reference)](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/getModifierState#modifier_keys_on_gecko).

**Comment by kfarr** [comment]
@mattrossman thanks for the writeup, sorry I came off as rude in my request to close, I was going through a bunch of old tickets that were very similar. Appreciate the context and helpful to know about traps like this when helping users open the inspector.

**Comment by KokoDoko** [comment]
Sadly this issue still persists. Even after closing other mac apps that use the same shortcut / or changing the shortcuts in other mac apps. I'm sure I am missing some app, but in the mean time, Is there another way to open the a-frame inspector on mac?

**Comment by dmarcos** [comment]
@vincentfretin cc

**Comment by vincentfretin** [comment]
I don't have a mac to test. @kfarr seems to say it works correctly on macOS.

**Comment by mattrossman** [comment]
@KokoDoko The following work on my Mac:

- `Shift + Ctrl + Option + i`
- `Ctrl + Option + Cmd + i`

Interestingly the workaround key combos I mentioned earlier [here](https://github.com/aframevr/aframe-inspector/issues/600#issue-624448139) and [here](https://github.com/aframevr/aframe-inspector/issues/600#issuecomment-800672568) no longer work for me.

I have [Rectangle](https://rectangleapp.com/) installed which conflicts with the usual shortcut, typically some combination of modifier keys plus `i` does the trick for opening inspector


https://github.com/aframevr/aframe-inspector/assets/22670878/32f46db6-32fa-4d7d-b697-c4f7aac46154
