### ISSUE TITLE
979 vulnerabilities

### ISSUE THREAD

**Issue by jelmerS2** [aframevr/aframe-inspector#606]
I'm quite new to this, but upon installing aframe inspector, NPM audit warns me about 979 vulnerabilities of which 372 are high and 4 even critical. 
Should I really continue with using it like this?

**Comment by vincentfretin** [comment]
All the dependencies were updated in 1.4.0.
@dmarcos you can close this issue.

**Comment by dmarcos** [comment]
Fixed by https://github.com/aframevr/aframe-inspector/issues/641
