### ISSUE TITLE
Ability to display a-entity IDs in the 3D view

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe-inspector#61]
Something that it could be toggled on and off to quickly find the entity I want.

**Comment by caseyyee** [comment]
The scene graph highlights the entity in the tree when you click on it in the 3D view.    Conversely, the entity shows bounding box in the 3D view around the entity when it is clicked on in the scene graph.  

Makes finding stuff in the scene fairly easy.   Not sure how showing ID's in the 3D view will help improve this.

**Comment by dmarcos** [comment]
So you don't have to click one by one on the entities to find the one that corresponds in the 3D view.

**Comment by caseyyee** [comment]
Yeah, but you click on the entity in 3D view and its highlighted, showing the ID in both the attributes panel as well as the scene graph.     Seems overly redundant.

**Comment by dmarcos** [comment]
It's not redundant. You would be able to move the camera and locate visualy the entity you're interested in within the 3D view without having to click on each one.

**Comment by arturitu** [comment]
In Blender is very useful when you start the rigging to show the name of the bones. If you have a lot of elements in a scene I think is good to have an option to show them to be sure all are in the expected position. And with this, maybe the left bar with the entities tree could be hide it if you want to have more space to view the scene.

Sure is more a futurible enhancement than an issue, but a suggestion >

Perhaps if you have the left or right bar hidden, automatically show the name of the selected object:
![image](https://cloud.githubusercontent.com/assets/5744112/16677437/49c91ea8-44d6-11e6-8182-730930748fed.png)

**Comment by feiss** [comment]
I think that a hotkey for toggling **all** entity names in the 3DView can be useful for some people. It is a simple action that does not interfere with anything else in the UX, and allows future things like what @arturitu proposes.

I'd show all entity names in white/light gray, and current selection in blue. They would look at always to the camera, constant size, positioned in the local origin of the entity, and drawn on top of the 3D scene.

**Comment by fernandojsg** [comment]
I'm not sure about showing all the IDs at once, I believe it could looks quite messy as they could overlap umm I should give it a try. In any case I'll move this to 0.6.0 as I think is quite low priority feature by now

**Comment by ngokevin** [comment]
we have a filter now!
