### ISSUE TITLE
Transform controls error blocks inspector loading with A-Frame master due to three.js breaking changes

### ISSUE THREAD

**Issue by kfarr** [aframevr/aframe-inspector#625]
**Description:**

- A-Frame Version: Master (https://cdn.jsdelivr.net/gh/aframevr/aframe@d52af46565230a33c0fa23e045fb74e877df7dc9/dist/aframe-master.min.js)
- Platform / Device: Desktop Mac OS
- Reproducible Code Snippet or URL: 

Working in A-Frame 1.2: https://aframe.glitch.me/ and press ctl-alt-i
Not working in A-Frame master:
https://inspector-broken-master.glitch.me/ and press ctl-alt-i

No inspector loads, and there is a console error:
`Uncaught TypeError: Class constructor MeshBasicMaterial cannot be invoked without 'new'`

**Cause:**
This appears to be related to a breaking change in an updated version of three.js relating to the TransformControls used by the inspector. 

**Solution:**
A potential solution is to update the TransformControls in inspector to a newer version.

**Comment by kfarr** [comment]
I found the latest version of es5 transform controls here:
https://github.com/mrdoob/three.js/blob/master/examples/js/controls/TransformControls.js

I attempted to copy the entire contents of that file into this repo's src/lib/TransformControls.js file.

The inspector now loads, which is an improvement, but there is now a new issue:
- The transform gizmo does not appear as expected when an object is selected. There is an error on the console: `TransformControls.js?0d71:12 Uncaught TypeError: Class constructor Object3D cannot be invoked without 'new'`

After some google searching this appears to be related to trying to use a module intended for ES6 from an ES5 environment. I am not sure how to proceed. Next I am looking for older versions of TransformControls prior to ES6 conversion that might still work with this latest version of three.js.

**Comment by kfarr** [comment]
This may be an issue with the way that the inspector's viewport.js file imports and attempts to create a new transformControls object

Here is the legacy ES5 import: 
https://github.com/aframevr/aframe-inspector/blob/master/src/lib/viewport.js#L5

And then here is the first invocation:
https://github.com/aframevr/aframe-inspector/blob/master/src/lib/viewport.js#L51

**Comment by donmccurdy** [comment]
I haven't figured out the exact steps to fix this yet, but the general problem is that newer versions of three.js have migrated to the use of [ES6 Classes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes). Converting base classes like THREE.Object3D to an ES6 Class has downstream effects — classes that extend it, like TransformControls, also need to be ES6 Classes. 

Updating `src/lib/TransformControls.js` and other forked three.js object types to ES6 Classes will be necessary to work with newer three.js and A-Frame versions, but isn't as simple as copy/pasting from three.js if they've been modified within this project, and that appears to be the case for several files: https://github.com/aframevr/aframe-inspector/commit/26eb77f76b58fe9ae7a2e90cb2455161c57c181f. Updating them manually to ES6 Classes, without copying from three.js source files, might be easier, as long as we don't need other upstream changes from the official TransformControls.

**Comment by kfarr** [comment]
> as long as we don't need other upstream changes from the official TransformControls

From a user functionality perspective, there is nothing upstream that is needed

**Comment by dmarcos** [comment]
Thanks for the pointers. A PR to port TransformControls to classes would be appreciated. It would be a great contribution.

**Comment by donmccurdy** [comment]
Hopefully a fix on the way here: https://github.com/aframevr/aframe-inspector/pull/627
