### ISSUE TITLE
Unable to load inspector on aframe v1.2.0 + three r136

### ISSUE THREAD

**Issue by lslzl3000** [aframevr/aframe-inspector#631]
For your example: https://aframe.io/aframe-inspector/examples/
Error
```
Uncaught TypeError: Class constructor MeshBasicMaterial cannot be invoked without 'new'
Uncaught TypeError: Cannot read properties of undefined (reading 'open')
```
![Screen Shot 2022-01-06 at 17 04 00](https://user-images.githubusercontent.com/3398981/148357520-02c73d1e-1b1f-4a44-95a8-4065c1388d5d.png)

**Comment by dmarcos** [comment]
I believe this should have been fixed by https://github.com/aframevr/aframe-inspector/pull/629. Let me know if that's the case. Closing and can reopen if necessary

**Comment by lslzl3000** [comment]
@dmarcos is published online? The https://aframe.io/aframe-inspector/examples/ is still build with v1.2.0 + r136, so still the old error.

**Comment by dmarcos** [comment]
No. It's not published anywhere but you can [point the inspector component to your local build](https://github.com/aframevr/aframe-inspector#specifying-inspector-build)
