### ISSUE TITLE
Editor does not load when dropping in aframe-editor.js into A-frame scene.

### ISSUE THREAD

**Issue by caseyyee** [aframevr/aframe-inspector#64]
![image](https://cloud.githubusercontent.com/assets/1560884/16568407/b0eefd8c-41de-11e6-94f4-1ef706564a80.png)
1. Download boilerplate scene:
   https://github.com/aframevr/aframe-boilerplate
2. Include aframe-editor.js
   From  /build/aframe-editor.js
3. Load scene
   See errors in console (as per screenshot)

Tried this with both the 0.2.0 and master versions of A-Frame.

**Comment by caseyyee** [comment]
Looks like the issue is that the `aframe-editor.js` script must be included after your scene:

``` html
  <body>
    <a-scene>
      <a-assets>
        <a-asset-item id="chicken" src="models/chicken/ayam.dae"></a-asset-item>
      </a-assets>
      <a-entity collada-model="#chicken" position="0 1 0"></a-entity>
      <a-plane rotation="-90 0 0" width="4" height="4" color="#7BC8A4"></a-plane>
      <a-sky color="#ECECEC"></a-sky>
    </a-scene>
    <script src="../build/aframe-editor.js"></script>
  </body>
```

**Comment by caseyyee** [comment]
See https://github.com/aframevr/aframe-editor/commit/4d7d16c3ebc21f1de1ae937240f40ac1aeee9a2c

Should fix how the script is loaded.  Ideally the user should be able to drop this script anywhere in the doc.  There should at least be an error or hint in the console rather than errors.

**Comment by fernandojsg** [comment]
Yep, good point.

**Comment by fernandojsg** [comment]
Closed as it's already explained on the readme
