### ISSUE TITLE
Transform controls really big

### ISSUE THREAD

**Issue by vincentfretin** [aframevr/aframe-inspector#649]
There is an issue where the transform controls doesn't resize when zooming in or out, so it appears really big when the camera is far away and you focus on a small object (with f or dblclick).
![transform_controls_really_big](https://user-images.githubusercontent.com/112249/196130306-1223e224-663e-43cf-b77b-bd17ddc9a3a3.jpg)

**Comment by vincentfretin** [comment]
Normal size if I click away and reclick on the object:

![transform_controls_normal_size](https://user-images.githubusercontent.com/112249/196130788-9319252d-d5f4-4379-b767-3d4441cd70fe.jpg)

**Comment by dmarcos** [comment]
Any quick fix for this we can incorporate to 1.4.0?

**Comment by vincentfretin** [comment]
This is most probably an update method to call after using zoom.
I quickly look at it but I'm not familiar enough with the code to do a quick fix on this.
I plan to work on updating TransformControls next year, we should be able to use the latest one from three instead of our very old one in the repository (for example setScaleSnap is missing on our old version).

Also I see that in EditorControls.js we're patching `THREE.Box3.prototype.expandByObject` so overriding the one from three, that's not great.

Also I would disable the dbclick to focus behavior, it's really confusing when you do it by mistake on the ground plane, it zooms out to infinity.

**Comment by vincentfretin** [comment]
You can sponsor [vincentfretin](https://github.com/sponsors/vincentfretin) to expedite this fix. Find other work you can sponsor at https://github.com/c-frame/sponsorship
