### ISSUE TITLE
Loaded models (dae or obj) are not selectable in 3D view

### ISSUE THREAD

**Issue by caseyyee** [aframevr/aframe-inspector#66]
Works fine if you use the scene graph to select.

**Comment by fernandojsg** [comment]
Yes this is something I just realised. Right now it depends on the order in which the components are applied to the entity, for example if you have `<a-entity geometry sound>` will works but  `<a-entity sound geometry>` it won't, as the first child of the `object3D` will be a mesh on the first case and `positionalAudio` on the second.
I'll take a look to fix it asap.

**Comment by caseyyee** [comment]
Oh interesting.   I thought it might be because loaded models don't intersect with raycasts properly?

**Comment by caseyyee** [comment]
👍 Awesome!
