### ISSUE TITLE
Regressions to fix after the React upgrade

### ISSUE THREAD

**Issue by vincentfretin** [aframevr/aframe-inspector#662]
Some regressions with the upgrade #647 that was listed in the description as remaining todos:
- copy html to clipboard broken
- opening the textures modal doesn't work

**Comment by dmarcos** [comment]
Do you think we can get this in for A-Frame 1.4.0? Thanks so much for all the inspector improvements

**Comment by vincentfretin** [comment]
I'm looking into it right now.

**Comment by vincentfretin** [comment]
Ok I fixed the two issues in #664
