### ISSUE TITLE
Remaining style issues with tailwindcss in the site

### ISSUE THREAD

**Issue by vincentfretin** [aframevr/aframe-inspector#663]
Remaining todos that was listed in #640
- local checkbox and other checkboxes for boolean properties is always black
- the id/class on the top bar is not aligned with <a-entity
- in the outliner the line height change slightly if I remove or add class

**Comment by dmarcos** [comment]
Thank you. Are opening a PR soon? Let's see if we can ship A-Frame 1.4.0 before Christmas

**Comment by vincentfretin** [comment]
Yes, I should be able to work on inspector issues next week.
