### ISSUE TITLE
Update hosted examples

### ISSUE THREAD

**Issue by vincentfretin** [aframevr/aframe-inspector#668]
@dmarcos After you do the 1.4.0 release, please update the hosted examples here
https://aframe.io/aframe-inspector/examples/
that is currently all broken.

**Comment by vincentfretin** [comment]
Also please push the tag and create the release on github.
The latest release shown in this repo is v0.6.0 on Sep 21, 2017.

**Comment by vincentfretin** [comment]
It seems the examples were updated as part of the release, and the 1.4.0 tag pushed. Well if you don't want to create a release notes for aframe-inspector I also understand.

**Comment by dmarcos** [comment]
We've never done detailed release notes for the inspector. We can if you're interested on writing some. Perhaps we could add them to the A-Frame release notes. https://github.com/aframevr/aframe/releases/tag/v1.4.0
