### ISSUE TITLE
Scaling issue with pan, rotate and zoom controls.

### ISSUE THREAD

**Issue by caseyyee** [aframevr/aframe-inspector#69]
There are certain situations where the zoom, rotate and pan controls start to function strangely where I end up not being able to zoom in or pan the camera past a certain point.   This seems to happen consistently when you zoom out, pan the scene around and zoom back in to a section for detailed editing -- a common operation when working with a larger scene.

Here is an example scene where the issue can be easily replicated:
https://github.com/caseyyee/aframe-editor/blob/models/example/nature.html

**Comment by HyroVitalyProtago** [comment]
It could be also interesting to set the panSpeed, zoomSpeed and rotationSpeed of EditorControls in aframe-inspector component attributes. Personally, I find the zoom speed too slow...

**Comment by bifolu** [comment]
Hey casseyye, can you give me a link on guide in how to zoom in and out of a panorama using aframe. Thanks

**Comment by caseyyee** [comment]
This issue doesn't have anything to do with Panoramas.   Though, I don't think i've encountered this zoom issue in a while.  Testing with the standard A-Frame scenes, everything seems fine.  Might have been fixed or only occur on certain scenes only.

@HyroVitalyProtago it would probably be best to file a separate issue for the zoom speed if you do find them slow.

Will close the issue for now.  Re-open if anyone else finds this to be a problem!
