### ISSUE TITLE
revert chicken example

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe-inspector#74]
I guess this was leftover work from testing models.
- Shouldn't promote COLLADA.
- Revert back to the various geometries.

**Comment by caseyyee** [comment]
The thing is that people will use it.    What is the best alternative?  We can't just hide from what people will use anyways?

**Comment by fernandojsg** [comment]
Yep, sorry it was my fault. Fixed in https://github.com/aframevr/aframe-editor/pull/75

**Comment by ngokevin** [comment]
@caseyyee  The previous example was great because you could instantly play with multiple basic objects and lights. 

The alternative being pushed is glTF, but regardless we avoid all this model format flux altogether. People use COLLADA because that's what we've been giving them, like a self-fulfilling prophecy.

**Comment by ngokevin** [comment]
The chicken was very cute though. My favorite animal.

**Comment by caseyyee** [comment]
@ngokevin I guess in absence of a actual solution for models, people will use it.    All I am saying is that we shouldn't ignore that even if it isn't great.   Anyways, chicken example removed.   bok bok bok!

**Comment by ngokevin** [comment]
Sure, we document it and use it in some of our examples. But we shouldn't necessarily promote it either. It's not great for the default editor scene.
