### ISSUE TITLE
When selecting an image in the aframe inspector, the inspector panel disappears.

### ISSUE THREAD

**Issue by mariomorenocapon** [aframevr/aframe-inspector#773]
As you can see in the example on this page:
https://stackblitz.com/edit/stackblitz-starters-vffhv5?file=index.html

If you open the preview in another browser tab and do CTRL + ALT + I to call the A-Frame inspector, you can select any object, view its properties such as position and modify it.

But when the image object is selected, the A-Frame inspector disappears. Both the left column for selecting the object on the stage and the right column, the inspector disappears.

**Comment by vincentfretin** [comment]
Did you test a master build? This issue was fixed in #723 normally.
You can test the build I linked here
https://github.com/aframevr/aframe-inspector/pull/772#issuecomment-2374525466

**Comment by mariomorenobcn** [comment]
Indeed, with the tag `<a-scene inspector="url: https://cdn.jsdelivr.net/gh/aframevr/aframe-inspector@ddda46f4376cf696e623721d98e1c2eb3e799b73/dist/aframe-inspector.min.js">` It works! Thank you.

**Comment by vincentfretin** [comment]
Great, the fix will be in aframe 1.7.0. You can close the issue.
