### ISSUE TITLE
Objects don't smoothly follow my mouse when dragging. The faster the worse it gets

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe-inspector#8]
![Mouse drag](https://s3.amazonaws.com/f.cl.ly/items/3W2D2a2i0t410Z2M371R/Screen%20Recording%202016-06-30%20at%2004.21.11%20PM.gif)

**Comment by fernandojsg** [comment]
@dmarcos can you give it a try? I believe it was caused because we were over-repainting the UI, still it should improved in following PR as we have room for improvement in there

**Comment by ngokevin** [comment]
super smooth now
