### ISSUE TITLE
Exported scene appears broken

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-inspector#9]
￼
![image](https://cloud.githubusercontent.com/assets/203725/16507574/a022e86c-3edf-11e6-9bb0-d4ab02287a0e.png)

![screen shot 2016-06-30 at 4 27 38 pm](https://cloud.githubusercontent.com/assets/203725/16507572/9be04934-3edf-11e6-86b7-704b36f98504.png)

**Comment by fernandojsg** [comment]
Close to keep the discussion on https://github.com/aframevr/aframe-editor/issues/23
